import csv
import datetime
import io
import json
import logging
import mimetypes
import os
from functools import partial
import logging
import django_filters
import django_rq
from dal import autocomplete
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db import transaction
from django.db.models import F, ExpressionWrapper, fields, Count
from django.http import Http404, HttpResponseRedirect, HttpResponse, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import DetailView, ListView, FormView, TemplateView
from django_currentuser.middleware import get_current_user
from django_filters.views import FilterView

from connection_app.camunda_functions import start_process_return_sales_order, start_book_sales_order_camunda_process, \
	start_processes_for_return_sales_order_list
from connection_app.enums import PostInspectionStatusEnum, InspectionTypeEnum, PostInspectionActivityTypeEnum, \
	ConnectionApplicationDocumentsEnum, SalesOrderStatusEnum
from connection_app.forms import UpdateAddressForm, PostInspectionStartForm, PreviewPostInspectionForm, \
	KitchenPostInspectionForm, PostInspectionForm, UIDPostInspectionForm, ProfilePhotoPostInspectionForm, \
	SurakshaPipePostInspectionForm, CustomerProfileSearchForm, GenerateLeadForm, GenerateNonCustomerLeadForm, \
	CustomerProfileDocumentUploadForm, SalesOrderDetailViewForm, SalesOrderPortabilityForm, SDMSServiceAreaForm, \
	UploadDataForm, ImportDataForm, CancelAutoGeneratedSalesOrderForm, BookSalesOrderForm, CustomerProfileSettingsForm, \
	OverrideSalesForm, PromotionalSaleForm, PromotionalSaleSearchForm,  PromotionalSalePrizeAllocationForm, OmcCylinderConversionForm, \
	ChangeAddressForm, UpdateDistributorLoginDetailsForm, UpdateSDMSUserLoginPasswordForm
from connection_app.jobs import dialogflow_chat_assignment
from connection_app.jobs import start_sales_order_portability_process, schedule_upload_data
from connection_app.models import ConnectionApplication, PostInspection, CustomerProfile, Lead, SalesOrder, \
	SalesOrderPortability, ImportData, BookSalesOrder, CustomerProfileSettings, OverrideSale, PromotionalSale, \
	PromotionalSaleCustomer, PrizeAllocation, VaultSecret, ImportDataTemplate, OmcConversionRequest, OmcConversionRequestDetail
from domestic_app import settings
from reference_data.models import ServiceType, Distributor, Product, SDMSServiceRequest
from service_request.enums import ServiceRequestTypeEnum, ServiceRequestTypeStatusEnum
from service_request.models import ServiceRequest
from teams.models import SDMSUser, UserProfile


logger = logging.getLogger(__name__)


def My_clinder_status(unique_id,phone_number):
	from ujjwala.models import FamilyMembers
	# Validate the input
	if not unique_id or len(unique_id) not in [10,12]:
		return "कृपया एक मान्य मोबाइल या उपभोक्ता नंबर दर्ज करें।"

	if len(unique_id) == 10:
		# Try to find the customer profile based on mobile number or consumer number
		application = CustomerProfile.objects.filter(mobile_number=unique_id).first() or \
					  CustomerProfile.objects.filter(consumer_no=unique_id).first()

	if len(unique_id) == 12:
		family_member = FamilyMembers.objects.filter(uid_no=unique_id).first()
		if not family_member:
			try:
				dialogflow_chat_assignment(phone_number)
				return "हम आपके कनेक्शन का विवरण ढूंढने में असमर्थ हैं, इसलिए हम आपको व्हाट्सएप पर हमारे ग्राहक सेवा से जोड़ रहे हैं"
			except Exception as e:
				logger.error(f"the issue in chat assignment {str(e)}")
				return "आपकी ऑर्डर जानकारी उपलब्ध नहीं है, कृपया अपनी ऑर्डर स्थिति की जांच करें। +91 161 520 1005"

		# TODO
		application = CustomerProfile.objects.filter(mobile_number=family_member.parent.sdms_mobile_number).first()

	if not application:
		return "हमें इस मोबाइल और उपभोक्ता नंबर के साथ कोई एप्लिकेशन नहीं मिला, कृपया अपना आधार कार्ड नंबर साझा करें।"

	# Check if the consumer number exists in the found application
	if not application.consumer_no:
		return "उपभोक्ता संख्या मान्य नहीं है, कृपया सही विवरण प्रदान करें।"

	# Find the related sales order
	saleorder = SalesOrder.objects.filter(relationship_id=application.consumer_id).order_by("-id").first()

	if not saleorder:
		return "आपकी कोई ऑर्डर जानकारी नहीं मिली, कृपया अपनी ऑर्डर स्थिति की जांच करें।"

	# Print debug information for development purposes
	print(saleorder.delivery_boy_full_name, saleorder.delivery_boy_login,saleorder.id, "the sale order details")

	# Ensure that saleorder has the necessary details
	if saleorder.order_status not in ["COMPLETED"]:
		try:
			# Retrieve delivery boy details using the delivery boy's login
			delivery_boy_details = SDMSUser.objects.get(delivery_boy_login=saleorder.delivery_boy_login)
			if delivery_boy_details and delivery_boy_details.parent:
				return f"आपके क्षेत्र के सिलेंडर डिलीवरी बॉय का नंबर {delivery_boy_details.parent.phone_number} है, " \
					   f"आपके सिलेंडर पहुंचने के समय के बारे में जानने के लिए कृपया उससे संपर्क करें।"
			else:
				return "डिलीवरी बॉय की जानकारी उपलब्ध नहीं है, कृपया बाद में पुनः प्रयास करें।"
		except SDMSUser.DoesNotExist:
			return "डिलीवरी बॉय की लॉगिन जानकारी मान्य नहीं है, कृपया बाद में पुनः प्रयास करें।"
		except SDMSUser.MultipleObjectsReturned:
			return "डिलीवरी बॉय की लॉगिन जानकारी के लिए कई रिकॉर्ड्स पाए गए, कृपया सहायता केंद्र से संपर्क करें।"
		except Exception as e:
			# Log any unexpected exception for debugging
			print(f"Unexpected error: {e}")
			return "सिस्टम में कुछ गड़बड़ी हो गई है, कृपया बाद में पुनः प्रयास करें।"

	return "आपकी ऑर्डर जानकारी उपलब्ध नहीं है, कृपया अपनी ऑर्डर स्थिति की जांच करें। +91 161 520 1005"


def installation_upload_process_gleam_entry_gate(request):
	application_id = request.GET.get("application_id")
	response = render(request, 'connection_app/fblike.html')
	response.set_cookie('application_id_cookie', application_id)
	return response


def installation_upload_process_gleam_entry_gate_completed(request):
	application_id = request.COOKIES.get('application_id_cookie')
	return redirect('installation_start', pk=application_id)


def index(request):
	# return RedirectView.as_view(url='/connection_app/portal/user_dashboard/', permanent=False)
	return render(request, 'connection_app/index.html')


def blue_book_form_view(request):
	blue_book_banners = Banner.objects.filter(
		disabled=False, valid_from__lte = timezone.now(), valid_upto__gte = timezone.now(),
	)
	return render(request, 'connection_app/blue_book_form.html', {
		"blue_book_banners": blue_book_banners
	})


def add_on_cylinder_form_view(request):
	# return RedirectView.as_view(url='/connection_app/portal/user_dashboard/', permanent=False)
	return render(request, 'connection_app/add_on_cylinder_form.html')



def web_form_view(request):
	return render(request, "connection_app/web_form.html")
	# def get_context_data(self, **kwargs):
	#     context_data = super().get(**kwargs)
	#     form_fill_area_list = FormFillArea.objects.all()
	#     context_data = context_data.update({
	#         "form_fill_area_list": form_fill_area_list
	#     })
	#     return context_data


class ApplicationStatusView(DetailView):
	model = ConnectionApplication

	def get_template_names(self):
		return 'connection_app/status.html'


class ApplicationReuploadView(DetailView):
	model = ConnectionApplication

	def get_template_names(self):
		return 'connection_app/pendingdata.html'


class ApplicationInstallationView(DetailView):
	model = ConnectionApplication

	def get_template_names(self):
		return 'connection_app/kitchenphoto.html'


@method_decorator(login_required, 'dispatch')
class PostInspectionListView(ListView):
	model = PostInspection
	template_name = 'connection_app/post-inspection/post_inspection_listview.html'

	paginate_by = 20
	permission = 'has_view_permission'

	def get_queryset(self):
		user: User = get_current_user()
		filters = {}
		if not user.is_superuser:
			filters.update({'mechanic': user})
		return PostInspection.objects.filter(**filters).order_by('-submitted_on')


@method_decorator(login_required, 'dispatch')
class PostInspectionStartFormView(FormView):
	model = PostInspection
	template_name = 'connection_app/post-inspection/post_inspection_start_form.html'
	form_class = PostInspectionStartForm

	def form_valid(self, form):
		data = form.cleaned_data

		customer_profile: object = None

		if data.get('consumer_id'):
			customer_profile: CustomerProfile = CustomerProfile.objects.filter(
				consumer_id=data.get('consumer_id')
			).first()

		if not customer_profile:
			if data.get('mobile_number'):
				customer_profile: CustomerProfile = CustomerProfile.objects.filter(
					mobile_number=data.get('mobile_number')
				).first()
				if not customer_profile:
					messages.add_message(
						self.request, messages.ERROR, "No customer found for given mobile number"
					)
					return redirect('connection_app:post_inspection_start')
			else:
				messages.add_message(
					self.request, messages.ERROR, "No customer found for given consumer id"
				)
				return redirect('connection_app:post_inspection_start')

		pi_obj = PostInspection.objects.filter(parent=customer_profile).first()
		if not pi_obj:
			pi_obj = PostInspection.objects.create(
				parent=customer_profile,
				status=PostInspectionStatusEnum.STARTED,
				type=InspectionTypeEnum.MECHANIC,
				mechanic=get_current_user()
			)
			pi_obj.activities.create(activity_type=PostInspectionActivityTypeEnum.KITCHEN_PHOTO_UPDATE)
			pi_obj.activities.create(activity_type=PostInspectionActivityTypeEnum.MAIN_GATE_PHOTO_UPDATE)
			pi_obj.activities.create(activity_type=PostInspectionActivityTypeEnum.PROFILE_PHOTO_UPDATE)
			pi_obj.activities.create(activity_type=PostInspectionActivityTypeEnum.ADDRESS_UPDATE)
			pi_obj.activities.create(activity_type=PostInspectionActivityTypeEnum.UID_PHOTO_UPDATE)
			pi_obj.activities.create(activity_type=PostInspectionActivityTypeEnum.SURAKSHA_PIPE_UPDATE)
			pi_obj.save()

		return redirect('post_inspection_form_view', pk=pi_obj.pk)


@method_decorator(login_required, 'dispatch')
@method_decorator(csrf_exempt, 'dispatch')
class PostInspectionView(FormView):
	model = PostInspection
	template_name = 'connection_app/post-inspection/post_inspection_form.html'
	form_class = PostInspectionForm
	success_url = '.'

	def dispatch(self, request, *args, **kwargs):
		post_inspection = self.get_object()
		if post_inspection.status in (
				PostInspectionStatusEnum.SUBMITTED,
				PostInspectionStatusEnum.ACCEPTED,
		):
			return render(self.request, 'connection_app/post-inspection/post_inspection_status.html', context={
				'post_inspection': post_inspection
			})
		return super().dispatch(request, *args, **kwargs)

	def get_object(self, queryset=None):
		try:
			obj = PostInspection.objects.get(pk=self.kwargs.get('pk'))
		except:
			raise Http404(
				"No %(verbose_name)s found matching the query" %
				{'verbose_name': queryset.model._meta.verbose_name}
			)
		return obj

	def form_valid(self, form):
		return HttpResponseRedirect(self.get_success_url())

	def form_invalid(self, form):
		for error in form.errors.get('__all__'):
			messages.add_message(self.request, messages.ERROR, error)
		return HttpResponseRedirect(".")

	def get_form_kwargs(self):
		kwargs = super().get_form_kwargs()
		kwargs['post_inspection'] = self.get_object()
		return kwargs

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		post_inspection = self.get_object()
		context.update({
			'post_inspection': post_inspection,
			'customer_profile': self.get_object().parent,
			'profile_photo_update': post_inspection.activities.filter(
				activity_type=PostInspectionActivityTypeEnum.PROFILE_PHOTO_UPDATE).first(),
			'uid_photo_update': post_inspection.activities.filter(
				activity_type=PostInspectionActivityTypeEnum.UID_PHOTO_UPDATE).first(),
			'address_update': post_inspection.activities.filter(
				activity_type=PostInspectionActivityTypeEnum.ADDRESS_UPDATE).first(),
			'kitchen_photo_update': post_inspection.activities.filter(
				activity_type=PostInspectionActivityTypeEnum.KITCHEN_PHOTO_UPDATE).first(),
			'main_gate_photo_update': post_inspection.activities.filter(
				activity_type=PostInspectionActivityTypeEnum.MAIN_GATE_PHOTO_UPDATE).first(),
			'suraksha_pipe_update': post_inspection.activities.filter(
				activity_type=PostInspectionActivityTypeEnum.SURAKSHA_PIPE_UPDATE).first()
		})
		return context


@method_decorator(login_required, 'dispatch')
@method_decorator(csrf_exempt, 'dispatch')
class PostInspectionAddressUpdateView(FormView):
	model = PostInspection
	template_name = 'connection_app/post-inspection/update_address.html'
	form_class = UpdateAddressForm
	success_url = '.'

	def dispatch(self, request, *args, **kwargs):
		post_inspection = self.get_object()
		if post_inspection.activities.filter(
			activity_type=PostInspectionActivityTypeEnum.ADDRESS_UPDATE).first().completed:
			return render(
				self.request, "connection_app/response.html",
				{"heading": "Post Inspection", "message": "Address Already Updated".format(kwargs.get('pk'))}
			)
		if post_inspection.status in (
				PostInspectionStatusEnum.SUBMITTED,
				PostInspectionStatusEnum.ACCEPTED,
		):
			return render(self.request, 'connection_app/post-inspection/post_inspection_status.html', context={
				'post_inspection': post_inspection
			})
		return super().dispatch(request, *args, **kwargs)

	def get_object(self, queryset=None):
		try:
			obj = PostInspection.objects.get(pk=self.kwargs.get('pk'))
		except:
			raise Http404(
				"No %(verbose_name)s found matching the query" %
				{'verbose_name': queryset.model._meta.verbose_name}
			)
		return obj

	def form_valid(self, form):
		form.save()
		return redirect('post_inspection_form_view', pk=self.get_object().pk)

	def get_form_kwargs(self):
		kwargs = super().get_form_kwargs()
		kwargs['post_inspection'] = self.get_object()
		return kwargs

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		post_inspection = self.get_object()
		context.update({
			'post_inspection': post_inspection,
			'customer_profile': self.get_object().parent,
		})
		return context


@method_decorator(login_required, 'dispatch')
@method_decorator(csrf_exempt, 'dispatch')
class PostInspectionKitchenPhotoUpdateView(FormView):
	model = PostInspection
	template_name = 'connection_app/post-inspection/update_kitchen_photo.html'
	form_class = KitchenPostInspectionForm
	success_url = '.'

	def dispatch(self, request, *args, **kwargs):
		post_inspection = self.get_object()
		if post_inspection.activities.filter(
			activity_type=PostInspectionActivityTypeEnum.KITCHEN_PHOTO_UPDATE).first().completed:
			return render(
				self.request, "connection_app/response.html",
				{"heading": "Post Inspection", "message": "Kitchen Photo Already Updated".format(kwargs.get('pk'))}
			)
		if post_inspection.status in (
				PostInspectionStatusEnum.SUBMITTED,
				PostInspectionStatusEnum.ACCEPTED,
		):
			return render(self.request, 'connection_app/post-inspection/post_inspection_status.html', context={
				'post_inspection': post_inspection
			})
		return super().dispatch(request, *args, **kwargs)

	def get_object(self, queryset=None):
		try:
			obj = PostInspection.objects.get(pk=self.kwargs.get('pk'))
		except:
			raise Http404(
				"No %(verbose_name)s found matching the query" %
				{'verbose_name': queryset.model._meta.verbose_name}
			)
		return obj

	def form_valid(self, form):
		form.save()
		return redirect('post_inspection_form_view', pk=self.get_object().pk)

	def get_form_kwargs(self):
		kwargs = super().get_form_kwargs()
		kwargs['post_inspection'] = self.get_object()
		return kwargs

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		post_inspection = self.get_object()
		context.update({
			'post_inspection': post_inspection,
			'customer_profile': self.get_object().parent,
		})
		return context


@method_decorator(login_required, 'dispatch')
@method_decorator(csrf_exempt, 'dispatch')
class PostInspectionMainGatePhotoUpdateView(FormView):
	model = PostInspection
	template_name = 'connection_app/post-inspection/update_main_gate_photo.html'
	form_class = PreviewPostInspectionForm
	success_url = '.'

	def dispatch(self, request, *args, **kwargs):
		post_inspection = self.get_object()
		if post_inspection.activities.filter(
			activity_type=PostInspectionActivityTypeEnum.MAIN_GATE_PHOTO_UPDATE).first().completed:
			return render(
				self.request, "connection_app/response.html",
				{"heading": "Post Inspection", "message": "Main Gate Photo Already Updated".format(kwargs.get('pk'))}
			)
		if post_inspection.status in (
				PostInspectionStatusEnum.SUBMITTED,
				PostInspectionStatusEnum.ACCEPTED,
		):
			return render(self.request, 'connection_app/post-inspection/post_inspection_status.html', context={
				'post_inspection': post_inspection
			})
		return super().dispatch(request, *args, **kwargs)

	def get_object(self, queryset=None):
		try:
			obj = PostInspection.objects.get(pk=self.kwargs.get('pk'))
		except:
			raise Http404(
				"No %(verbose_name)s found matching the query" %
				{'verbose_name': queryset.model._meta.verbose_name}
			)
		return obj

	def form_valid(self, form):
		form.save()
		return redirect('post_inspection_form_view', pk=self.get_object().pk)

	def get_form_kwargs(self):
		kwargs = super().get_form_kwargs()
		kwargs['post_inspection'] = self.get_object()
		return kwargs

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		post_inspection = self.get_object()
		context.update({
			'post_inspection': post_inspection,
			'customer_profile': self.get_object().parent,
		})
		return context


@method_decorator(login_required, 'dispatch')
@method_decorator(csrf_exempt, 'dispatch')
class PostInspectionUIDPhotoUpdateView(FormView):
	model = PostInspection
	template_name = 'connection_app/post-inspection/update_uid_photo.html'
	form_class = UIDPostInspectionForm
	success_url = '.'

	def dispatch(self, request, *args, **kwargs):
		post_inspection = self.get_object()
		if post_inspection.activities.filter(
			activity_type=PostInspectionActivityTypeEnum.UID_PHOTO_UPDATE).first().completed:
			return render(
				self.request, "connection_app/response.html",
				{"heading": "Post Inspection", "message": "UID Photos Already Updated".format(kwargs.get('pk'))}
			)
		if post_inspection.status in (
				PostInspectionStatusEnum.SUBMITTED,
				PostInspectionStatusEnum.ACCEPTED,
		):
			return render(self.request, 'connection_app/post-inspection/post_inspection_status.html', context={
				'post_inspection': post_inspection
			})
		return super().dispatch(request, *args, **kwargs)

	def get_object(self, queryset=None):
		try:
			obj = PostInspection.objects.get(pk=self.kwargs.get('pk'))
		except:
			raise Http404(
				"No %(verbose_name)s found matching the query" %
				{'verbose_name': queryset.model._meta.verbose_name}
			)
		return obj

	def form_valid(self, form):
		form.save()
		return redirect('post_inspection_form_view', pk=self.get_object().pk)

	def get_form_kwargs(self):
		kwargs = super().get_form_kwargs()
		kwargs['post_inspection'] = self.get_object()
		return kwargs

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		post_inspection = self.get_object()
		context.update({
			'post_inspection': post_inspection,
			'customer_profile': self.get_object().parent,
		})
		return context


@method_decorator(login_required, 'dispatch')
@method_decorator(csrf_exempt, 'dispatch')
class PostInspectionProfilePhotoUpdateView(FormView):
	model = PostInspection
	template_name = 'connection_app/post-inspection/update_profile_photo.html'
	form_class = ProfilePhotoPostInspectionForm
	success_url = '.'

	def dispatch(self, request, *args, **kwargs):
		post_inspection = self.get_object()
		if post_inspection.activities.filter(
			activity_type=PostInspectionActivityTypeEnum.PROFILE_PHOTO_UPDATE).first().completed:
			return render(
				self.request, "connection_app/response.html",
				{"heading": "Post Inspection", "message": "Profile Photo Already Updated".format(kwargs.get('pk'))}
			)
		if post_inspection.status in (
				PostInspectionStatusEnum.SUBMITTED,
				PostInspectionStatusEnum.ACCEPTED,
		):
			return render(self.request, 'connection_app/post-inspection/post_inspection_status.html', context={
				'post_inspection': post_inspection
			})
		return super().dispatch(request, *args, **kwargs)

	def get_object(self, queryset=None):
		try:
			obj = PostInspection.objects.get(pk=self.kwargs.get('pk'))
		except:
			raise Http404(
				"No %(verbose_name)s found matching the query" %
				{'verbose_name': queryset.model._meta.verbose_name}
			)
		return obj

	def form_valid(self, form):
		form.save()
		return redirect('post_inspection_form_view', pk=self.get_object().pk)

	def get_form_kwargs(self):
		kwargs = super().get_form_kwargs()
		kwargs['post_inspection'] = self.get_object()
		return kwargs

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		post_inspection = self.get_object()
		context.update({
			'post_inspection': post_inspection,
			'customer_profile': self.get_object().parent,
		})
		return context


@method_decorator(login_required, 'dispatch')
@method_decorator(csrf_exempt, 'dispatch')
class PostInspectionSurakshaPipeUpdateView(FormView):
	model = PostInspection
	template_name = 'connection_app/post-inspection/update_suraksha_pipe.html'
	form_class = SurakshaPipePostInspectionForm
	success_url = '.'

	def dispatch(self, request, *args, **kwargs):
		post_inspection = self.get_object()
		if post_inspection.activities.filter(
			activity_type=PostInspectionActivityTypeEnum.SURAKSHA_PIPE_UPDATE).first().completed:
			return render(
				self.request, "connection_app/response.html",
				{"heading": "Post Inspection", "message": "Suraksha Pipe Already Updated".format(kwargs.get('pk'))}
			)

		if post_inspection.status in (
				PostInspectionStatusEnum.SUBMITTED,
				PostInspectionStatusEnum.ACCEPTED,
		):
			return render(self.request, 'connection_app/post-inspection/post_inspection_status.html', context={
				'post_inspection': post_inspection
			})
		return super().dispatch(request, *args, **kwargs)

	def get_object(self, queryset=None):
		try:
			obj = PostInspection.objects.get(pk=self.kwargs.get('pk'))
		except:
			raise Http404(
				"No %(verbose_name)s found matching the query" %
				{'verbose_name': queryset.model._meta.verbose_name}
			)
		return obj

	def form_valid(self, form):
		form.save()
		return redirect('post_inspection_form_view', pk=self.get_object().pk)

	def form_invalid(self, form):
		print(form.errors)
		return redirect('post_inspection_form_view', pk=self.get_object().pk)

	def get_form_kwargs(self):
		kwargs = super().get_form_kwargs()
		kwargs['post_inspection'] = self.get_object()
		return kwargs

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		post_inspection = self.get_object()
		context.update({
			'post_inspection': post_inspection,
			'customer_profile': self.get_object().parent,
		})
		return context


@method_decorator(login_required, 'dispatch')
class CustomerProfileSearchView(FormView):
	template_name = "connection_app/customer_profile_search.html"
	form_class = CustomerProfileSearchForm

	def get(self, request, *args, **kwargs):
		# Check if there are any GET parameters (e.g., consumer_id or mobile_number)
		consumer_id = request.GET.get('consumer_id')
		mobile_number = request.GET.get('mobile_number')

		if consumer_id or mobile_number:
			# If parameters exist, bypass form rendering and search directly
			cp_obj = None
			if consumer_id:
				cp_obj = CustomerProfile.objects.filter(consumer_id=consumer_id).first()
			elif mobile_number:
				cp_obj = CustomerProfile.objects.filter(mobile_number=mobile_number).first()

			if not cp_obj:
				messages.add_message(
					request, messages.ERROR, "No Record Found For Given Consumer Id or Mobile Number"
				)
				# This will be changed To New Lead Creation Form
				return HttpResponseRedirect(reverse('customer_profile_search'))

			# Redirect to customer profile view if a match is found
			return redirect('customer_profile', pk=cp_obj.pk)

		# If no parameters, render the form normally
		return super().get(request, *args, **kwargs)

	def form_valid(self, form):
		data = form.cleaned_data

		cp_obj = None
		if data.get('consumer_id'):
			cp_obj = CustomerProfile.objects.filter(consumer_id=data.get('consumer_id')).first()
		elif data.get('mobile_number'):
			cp_obj = CustomerProfile.objects.filter(mobile_number=data.get('mobile_number')).first()
		# elif data.get('customer_profile_id'):
		# 	cp_obj = CustomerProfile.objects.filter(pk=data.get('customer_profile_id')).first()

		if not cp_obj:
			messages.add_message(
				self.request, messages.ERROR, "No Record Found For Given Consumer Id or Mobile Number"
			)
			return HttpResponseRedirect(".")

		return redirect('customer_profile', pk=cp_obj.pk)


@method_decorator(login_required, 'dispatch')
class CustomerProfileView(TemplateView):
	template_name = 'connection_app/customer_profile.html'

	def get_object(self, queryset=None):
		try:
			obj = CustomerProfile.objects.get(pk=self.kwargs.get('pk'))
		except:
			raise Http404(
				"No Customer Profile Exist For Given Id"
			)
		return obj

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)

		obj: CustomerProfile = self.get_object()
		context.update({
			"obj": obj,
		})
		return context


class CustomerProfilePublicView(TemplateView):
	template_name = 'connection_app/customer_profile.html'

	def get_object(self, queryset=None):
		try:
			obj = CustomerProfile.objects.get(pk=self.kwargs.get('pk'))
		except:
			raise Http404(
				"No Customer Profile Exist For Given Id"
			)
		return obj

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)

		obj: CustomerProfile = self.get_object()
		context.update({
			"obj": obj,
		})
		return context


@method_decorator(login_required, 'dispatch')
@method_decorator(csrf_exempt, 'dispatch')
class GenerateLeadFormView(FormView):
	# model = CustomerProfile
	template_name = 'connection_app/generate_lead_form.html'
	form_class = GenerateLeadForm
	success_url = '/success/'  # Update to the correct success URL or leave as is

	def get_object(self, queryset=None):
		pk = self.request.GET.get('pk')
		if pk:
			return get_object_or_404(CustomerProfile, pk=pk)
		return None

	def form_valid(self, form):
		data = form.cleaned_data
		customer_profile = self.get_object()

		# Create Leads based on the selected service types
		service_types = data.get('service_types', [])
		for service_type in service_types:
			Lead.objects.create(
				parent=customer_profile,
				generated_by=self.request.user,  # Assuming you have a current user context
				service_type=service_type,
				name=data['name'],
				mobile_number=data['mobile_number']
			)

		# Optionally, process products and SDMS service requests if included in the form
		# (Implement additional processing logic as needed)

		messages.success(self.request,
						 f"Generated Lead Successfully for {', '.join([st.name for st in service_types])}")
		return redirect(reverse("customer_profile", kwargs={'pk': customer_profile.pk}))

	def get_form(self, form_class=None):
		form = super().get_form(form_class)

		# If customer_profile exists, set fields to readonly
		if self.get_object():  # Assuming `self.customer_profile` holds the profile
			form.fields['name'].widget.attrs['readonly'] = True
			form.fields['mobile_number'].widget.attrs['readonly'] = True
			form.fields['address'].widget.attrs['readonly'] = True

		return form

	def get_form_kwargs(self):
		# Get the default form kwargs
		kwargs = super().get_form_kwargs()

		# Get the primary key (pk) from the request's GET parameters
		customer_profile = self.get_object()  # Assuming `self.get_object()` fetches the relevant object

		if customer_profile:
			kwargs['initial'] = {
				'customer_profile': customer_profile,
				'name': customer_profile.name,
				'mobile_number': customer_profile.mobile_number,
				'address': customer_profile.address
			}

		return kwargs

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context.update({
			'customer_profile': self.get_object() ,
			'service_types': ServiceType.objects.filter(enabled=True),
			'products': Product.objects.filter(enabled=True),
			'sdms_service_requests': SDMSServiceRequest.objects.filter(enabled=True),
		})
		return context


@method_decorator(login_required, 'dispatch')
@method_decorator(csrf_exempt, 'dispatch')
class GenerateNonCustomerLeadFormView(FormView):
	template_name = 'connection_app/generate_non_customer_lead_form.html'
	form_class = GenerateNonCustomerLeadForm
	success_url = '.'

	def form_valid(self, form):
		data = form.cleaned_data
		for service_type in data['service_list']:
			Lead.objects.create(
				parent=self.get_object(),
				generated_by=get_current_user(),
				service_type=ServiceType.objects.get(name=service_type),
				name=data['name'],
				mobile_number=data['mobile_number'],
				remarks=data['remarks']
			)
		messages.add_message(self.request, messages.INFO,
							 message="Generated Lead Successfully For {}".format(", ".join(data['service_list'])))
		return redirect("customer_profile", pk=self.get_object().pk)

	def get_form_kwargs(self):
		kwargs = super().get_form_kwargs()
		kwargs['service_type_choices'] = tuple(ServiceType.objects.all().values_list('name', 'name'))
		return kwargs


@method_decorator(login_required, 'dispatch')
@method_decorator(csrf_exempt, 'dispatch')
class CustomerProfileDocumentUploadFormView(FormView):
	template_name = 'connection_app/customer_profile_document_upload.html'
	form_class = CustomerProfileDocumentUploadForm
	success_url = '.'

	def get_object(self, queryset=None):
		try:
			obj = CustomerProfile.objects.get(pk=self.kwargs.get('pk'))
		except:
			raise Http404(
				"No %(verbose_name)s found matching the query" %
				{'verbose_name': queryset.model._meta.verbose_name}
			)
		return obj

	def dispatch(self, request, *args, **kwargs):
		customer_profile = self.get_object()

		if customer_profile.documents.filter(type=ConnectionApplicationDocumentsEnum.BANK_SUBSIDY_CERTIFICATE_PHOTO).first():
			messages.add_message(self.request, messages.INFO,
								 f"Bank Subsidy Certificate Document Already Submitted.")
			return redirect("customer_profile", pk=self.get_object().pk)
		return super().dispatch(request, *args, **kwargs)

	def form_valid(self, form):
		data = form.cleaned_data

		customer_profile = self.get_object()
		customer_profile.documents.create(
			type=data['document_type'], link=data['document_link']
		)
		messages.add_message(self.request, messages.INFO, f"{data['document_type']} Document Uploaded Successfully.")
		return redirect("customer_profile", pk=self.get_object().pk)

	def get_context_data(self, **kwargs):
		context = super().get_context_data()
		context.update({
			"customer_profile": self.get_object()
		})
		return context

	def get_form_kwargs(self):
		kwargs = super().get_form_kwargs()
		kwargs['initial'] = {'document_type': ConnectionApplicationDocumentsEnum.BANK_SUBSIDY_CERTIFICATE_PHOTO}
		return kwargs


@method_decorator(login_required, 'dispatch')
class DashboardView(TemplateView):
	template_name = "connection_app/dashboard.html"

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		user = get_current_user()

		context.update({
			"user": user
			# "sales_order_portability_queryset": SalesOrderPortability.objects.filter(user=get_current_user()),
			# "sales_order_portability_status": SalesOrderPortabilityStatusEnum.choices
		})
		return context


class SalesOrderFilter(django_filters.FilterSet):
	class Meta:
		model = SalesOrder
		fields = ['sales_order', 'consumer_name', 'hide_from_view']


@method_decorator(login_required, 'dispatch')
class SalesOrderListView(FilterView):
	model = SalesOrder
	template_name = 'connection_app/sales-order/sales_order_listview.html'

	paginate_by = 10
	permission = 'has_view_permission'
	filterset_class = SalesOrderFilter

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		queryset = self.get_queryset()
		paginator = Paginator(queryset, self.paginate_by)
		page_number = self.request.GET.get('page')
		page_obj = paginator.get_page(page_number)
		context['page_obj'] = page_obj
		return context

	def get_queryset(self):
		current_user = get_current_user()
		qs = SalesOrder.objects.filter(auto_generated=True).order_by('order_date')

		if self.request.GET.get('show_hidden_records') != 'on':
			qs = qs.exclude(hide_from_view=True)

		if current_user.is_superuser:
			return qs

		sdms_user: SDMSUser = SDMSUser.objects.filter(
			parent__user=current_user,
			distributor__name='Arun Indane'
		).first()

		if not sdms_user:
			return SalesOrder.objects.none()

		qs = qs.objects.filter(delivery_boy_login=sdms_user.delivery_boy_login)

		return qs.order_by('order_date')

 
@method_decorator(login_required, 'dispatch')
@method_decorator(csrf_exempt, 'dispatch')
class SalesOrderDetailFormView(FormView):
	template_name = 'connection_app/sales-order/sales_order_detail_view.html'
	form_class = SalesOrderDetailViewForm
	success_url = '.'

	def get_object(self, queryset=None):
		try:
			obj = SalesOrder.objects.get(pk=self.kwargs.get('pk'))
		except:
			raise Http404(
				"No %(verbose_name)s found matching the query" %
				{'verbose_name': queryset.model._meta.verbose_name}
			)
		return obj

	def form_valid(self, form):
		data = form.cleaned_data
		so_obj = self.get_object()
		so_obj.parent.do_not_auto_generate = data['cancel_auto_booking']
		so_obj.parent.save()
		return redirect("sales_order_list")

	def get_context_data(self, **kwargs):
		context = super().get_context_data()
		context.update({
			"sales_order": self.get_object()
		})
		return context


@method_decorator(login_required, 'dispatch')
class CustomerProfileContactsView(TemplateView):

	template_name = "connection_app/customer_profile_contacts.html"

	def get_object(self, queryset=None):
		try:
			obj = CustomerProfile.objects.get(pk=self.kwargs.get('pk'))
		except:
			raise Http404(
				"No %(verbose_name)s found matching the query" %
				{'verbose_name': queryset.model._meta.verbose_name}
			)
		return obj

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context.update({
			"obj": self.get_object()
		})
		return context


@method_decorator(login_required, 'dispatch')
class CustomerProfileSettingsView(FormView):
	form_class = CustomerProfileSettingsForm
	template_name = "connection_app/customer-profile/customer_profile_settings.html"

	def get_object(self, queryset=None):
		try:
			obj = CustomerProfile.objects.get(pk=self.kwargs.get('pk'))
		except:
			raise Http404(
				"No %(verbose_name)s found matching the query" %
				{'verbose_name': queryset.model._meta.verbose_name}
			)
		return obj

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context.update({
			"obj": self.get_object()
		})
		return context

	def get_form_kwargs(self):
		kwargs = super().get_form_kwargs()
		cps_obj = CustomerProfileSettings.objects.filter(parent=self.get_object()).first()
		if cps_obj is not None:
			kwargs['initial'] = {
				'is_dirty': self.get_object().is_dirty,
				'do_not_auto_generate_sales_order': cps_obj.do_not_auto_generate_sales_order
			}
		return kwargs


	def form_valid(self, form):
		data = form.cleaned_data
		customer_profile: CustomerProfile = self.get_object()
		customer_profile.is_dirty = data['is_dirty']
		customer_profile.save()
		cps_obj = CustomerProfileSettings.objects.filter(parent=customer_profile).first()
		if cps_obj is not None:
			cps_obj.do_not_auto_generate_sales_order = data['do_not_auto_generate_sales_order']
			cps_obj.save()
		else:
			CustomerProfileSettings.objects.create(
				parent=customer_profile,
				do_not_auto_generate_sales_order=data['do_not_auto_generate_sales_order']
			)
		return redirect("customer_profile", pk=customer_profile.pk)


@method_decorator(login_required, 'dispatch')
@method_decorator(csrf_exempt, 'dispatch')
class SalesOrderPortabilityFormView(FormView):
	template_name = 'connection_app/sales-order/sales_order_portability.html'
	form_class = SalesOrderPortabilityForm
	success_url = '.'

	def get_object(self, queryset=None):
		try:
			obj = SalesOrder.objects.get(pk=self.kwargs.get('pk'))
		except:
			raise Http404(
				"No %(verbose_name)s found matching the query" %
				{'verbose_name': queryset.model._meta.verbose_name}
			)
		return obj

	def form_valid(self, form):
		data = form.cleaned_data
		sop_obj: SalesOrderPortability = SalesOrderPortability.objects.create(
			sales_order_number=data['sales_order_number'],
			user=get_current_user(),
			distributor_id=data['distributor']
		)
		messages.add_message(self.request, messages.INFO,
							 f"Sales Order Portability Request Initiated. Request Id: {sop_obj.pk}")
		django_rq.enqueue(start_sales_order_portability_process, args=(sop_obj.id,))
		return redirect("connection_app:sales_order_grid_menu_view")

	def get_form_kwargs(self):
		kwargs = super().get_form_kwargs()
		distributor_list = [('', 'Please Select Distributor')]
		distributor_list.extend([
				(obj.id, f"{obj.code} - {obj.name}") for obj in Distributor.objects.all()
			])
		kwargs['distributor_list'] = distributor_list
		return kwargs


class CustomerGridMenuView(TemplateView):
	template_name = 'connection_app/grid_menu.html'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)

		menu = {
			"name": "Customer",
			"items": [
				{
					"name": "Customer Profile",
					"icon": "fa-user",
					"url": reverse("connection_app:customer_profile_search"),
				},
				{
					"name": "Generate Lead",
					"icon": "fa-star",
					"url": reverse("connection_app:customer_profile_search"),
				},
			]
		}

		context.update({
			"menu": menu
		})
		return context


class InspectionGridMenuView(TemplateView):
	template_name = 'connection_app/grid_menu.html'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)

		menu = {
			"name": "Inspection",
			"items": [
				{
					"name": "Start Post Inspection",
					"icon": "fa-user-secret",
					"url": reverse("connection_app:post_inspection_start"),
				},
				{
					"name": "Post Inspection List",
					"icon": "fa-bars",
					"url": reverse("connection_app:post_inspection_list"),
				},
			]
		}

		context.update({
			"menu": menu
		})
		return context


class SalesOrderGridMenuView(TemplateView):
	template_name = 'connection_app/grid_menu.html'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)

		menu = {
			"name": "Sales Order",
			"items": [
				{
					"name": "Sales Order List",
					"icon": "fa-book",
					"url": reverse("connection_app:sales_order_list"),
				},
				{
					"name": "Invoice Sales Order",
					"icon": "fa-credit-card",
					"url": reverse("connection_app:sales_order_portability"),
				},
				{
					"name": "Portability List",
					"icon": "fa-bars",
					"url": reverse("connection_app:sales_order_portability_list"),
				},
				{
					"name": "Customer List",
					"icon": "fa-bars",
					"url": reverse("connection_app:customer_profile_list"),
				},
				{
					"name": "Override Sale",
					"icon": "fa-bars",
					"url": reverse("connection_app:override_sale"),
				},
				{
					"name": "Override Sale List",
					"icon": "fa-bars",
					"url": reverse("connection_app:override_sale_list"),
				}
			]
		}

		context.update({
			"menu": menu
		})
		return context


@method_decorator(login_required, 'dispatch')
class AdminToolsGridMenuView(TemplateView):
	template_name = 'connection_app/grid_menu.html'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)

		menu = {
			"name": "Import",
			"items": [
				{
					"name": "Import Data",
					"icon": "fa-user-secret",
					"url": reverse("connection_app:import_data"),
				},
				{
					"name": "Cancel Auto Sales Order",
					"icon": "fa-user-secret",
					"url": reverse("connection_app:cancel_sales_order_list"),
				},
				{
					"name": "Book Sales Order",
					"icon": "fa-user-secret",
					"url": reverse("connection_app:book_sales_order_list"),
				},
				# {
				# 	"name": "Update Distributor Password",
				# 	"icon": "fa-user-secret",
				# 	"url": reverse("connection_app:update_distributor_login_details"),
				# },
			]
		}

		context.update({
			"menu": menu
		})
		return context


@method_decorator(login_required, 'dispatch')
class SalesGridMenuView(TemplateView):
	template_name = 'connection_app/grid_menu.html'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)

		menu = {
			"name": "Promotional Sale",
			"items": [
				{
					"name": "Promotional Sale",
					"icon": "fa-user-secret",
					"url": reverse("connection_app:promotional_sale"),
				},
				{
					"name": "Promotional Sale List",
					"icon": "fa-bars",
					"url": reverse("connection_app:promotional_sale_list"),
				},
				{
					"name": "Prize Allocation List",
					"icon": "fa-bars",
					"url": reverse("connection_app:prize_allocation_list"),
				}
			]
		}

		context.update({
			"menu": menu
		})
		return context


@method_decorator(login_required, 'dispatch')
class SalesOrderPortabilityListView(ListView):
	model = SalesOrderPortability
	template_name = 'connection_app/sales-order/sales_order_portability_listview.html'

	paginate_by = 20
	permission = 'has_view_permission'

	#
	# def dispatch(self, request, *args, **kwargs):
	# 	if request.method == 'POST':
	# 		return redirect(reverse("connection_app:sales_order_list") + "?hide_from_view={}".format("on"))
	# 	return super().dispatch(request, *args, **kwargs)

	def get_queryset(self):
		current_user = get_current_user()

		if current_user.is_superuser:
			return SalesOrderPortability.objects.all()
		else:
			return SalesOrderPortability.objects.filter(user=get_current_user())

	def get_context_data(self, *, object_list=None, **kwargs):
		context = super().get_context_data(object_list=object_list, **kwargs)
		list_qs = self.get_queryset()
		paginator = Paginator(list_qs, self.paginate_by)

		page = self.request.GET.get('page')

		try:
			list_qs = paginator.page(page)
		except PageNotAnInteger:
			list_qs = paginator.page(1)
		except EmptyPage:
			list_qs = paginator.page(paginator.num_pages)
		context['list_qs'] = list_qs

		return context


@method_decorator(login_required, 'dispatch')
class CustomerProfileListView(ListView):
	model = CustomerProfile
	template_name = 'connection_app/customer-profile/customer_profile_listview.html'

	paginate_by = 20
	permission = 'has_view_permission'

	def __init__(self, **kwargs):
		super().__init__(**kwargs)
		self.service_area_list = []
		self.distributor_list = []
		self.inactive_customer_list = []

	def dispatch(self, request, *args, **kwargs):
		current_user = get_current_user()
		user_profile = UserProfile.objects.get(user=current_user)

		if not user_profile:
			return

		return super().dispatch(request, *args, **kwargs)

	# def get_queryset(self):
	# 	current_user = get_current_user()
	# 	user_profile = UserProfile.objects.get(user=current_user)
	#
	# 	self.service_area_list = user_profile.sdms_service_areas.values_list('area_name', flat=True)
	# 	self.distributor_list = user_profile.sdmsuser_set.values_list('distributor__code', flat=True)
	#
	# 	if self.request.method == 'GET':
	# 		self.service_area_list = self.request.GET.getlist('sdms_service_area') if self.request.GET.getlist(
	# 			'sdms_service_area') else self.service_area_list
	# 		self.distributor_list = self.request.GET.getlist('distributor') if self.request.GET.getlist(
	# 			'distributor') else self.distributor_list
	#
	# 	# Filter CustomerProfile based on the distributor and service area lists
	# 	queryset = CustomerProfile.objects.filter(
	# 		distributor_code__in=self.distributor_list,
	# 		service_area__in=self.service_area_list,
	# 	)
	#
	# 	# Get the current date
	# 	current_date = datetime.datetime.now().date()
	#
	# 	# Annotate with the number of days since the last order
	# 	queryset = queryset.filter(
	# 		salesorder__order_date__isnull=False,
	# 		salesorder__order_status__in=[
	# 			SalesOrderStatusEnum.INVOICED, SalesOrderStatusEnum.INVOICING_IN_PROGRESS
	# 		]
	# 	).annotate(last_order_date=F('salesorder__order_date')).annotate(
	# 		days_since_last_order=ExpressionWrapper(
	# 			current_date - F('last_order_date'),
	# 			output_field=fields.DurationField()
	# 		)
	# 	).order_by('salesorder__order_date')
	# 	# Limit to the first 10 records
	# 	queryset = queryset[:10]
	#
	# 	return queryset
	def get_queryset(self):
		current_user = get_current_user()
		user_profile = UserProfile.objects.get(user=current_user)
		days = self.request.GET.get('days', "30")
		days_ago = datetime.datetime.now() - datetime.timedelta(days=int(days) if days else 30)

		self.service_area_list = user_profile.sdms_service_areas.values_list('area_name', flat=True)
		self.distributor_list = user_profile.sdmsuser_set.values_list('distributor__code', flat=True)

		# Apply filters from the request (GET method)
		if self.request.method == 'GET':
			self.service_area_list = self.request.GET.getlist('sdms_service_area') or self.service_area_list
			self.distributor_list = self.request.GET.getlist('distributor') or self.distributor_list

		# Get recent sales orders (placed in the last X days)
		recent_sales_orders = SalesOrder.objects.filter(order_date__gte=days_ago).values("parent_id")

		# Filter active customers (placed orders in the last 30 days)
		active_customers = CustomerProfile.objects.filter(
			distributor_code__in=self.distributor_list,
			service_area__in=self.service_area_list,
			id__in=recent_sales_orders
		).distinct().order_by("id")

		# Filter CustomerProfile based on the distributor and service area lists
		queryset = CustomerProfile.objects.filter(
			distributor_code__in=self.distributor_list,
			service_area__in=self.service_area_list,
		)
		# Filter inactive customers (no orders in the last 30 days)
		self.inactive_customer_list = CustomerProfile.objects.filter(
			distributor_code__in=self.distributor_list,
			service_area__in=self.service_area_list
		).exclude(
			id__in=recent_sales_orders
		).order_by("id")

		return active_customers

		# Get the current date
		current_date = datetime.datetime.now().date()

		# Filter to get records where the last order date is 30 days or more before the current date
		thirty_days_ago = current_date - datetime.timedelta(days=30)

		# Annotate with the number of days since the last order and filter by last order date
		queryset = queryset.filter(
			salesorder__order_date__isnull=False,
			salesorder__order_status__in=[
				SalesOrderStatusEnum.INVOICED, SalesOrderStatusEnum.INVOICING_IN_PROGRESS
			]
		).annotate(last_order_date=F('salesorder__order_date')).annotate(
			days_since_last_order=ExpressionWrapper(
				current_date - F('last_order_date'),
				output_field=fields.DurationField()
			)
		).filter(
			last_order_date__lte=thirty_days_ago  # Filter for orders older than 30 days
		).order_by('salesorder__order_date')

		# Limit to the first 10 records
		queryset = queryset[:10]

		return queryset

	def get_context_data(self, *, object_list=None, **kwargs):
		context = super().get_context_data(object_list=object_list, **kwargs)
		initial_data = {
			'sdms_service_area': self.request.GET.getlist('sdms_service_area')
		}
		context['filter_form'] = SDMSServiceAreaForm(
			user_profile=UserProfile.objects.get(user=get_current_user()), data=initial_data
		)

		# Paginate active customers
		active_customers = self.get_queryset()
		active_paginator = Paginator(active_customers, self.paginate_by)
		active_page = self.request.GET.get('page')
		try:
			active_customers = active_paginator.page(active_page)
		except PageNotAnInteger:
			active_customers = active_paginator.page(1)
		except EmptyPage:
			active_customers = active_paginator.page(active_paginator.num_pages)
		context['list_qs'] = active_customers

		# Paginate inactive customers
		inactive_customers = self.inactive_customer_list
		inactive_paginator = Paginator(inactive_customers, self.paginate_by)
		inactive_page = self.request.GET.get('inactive_page')
		try:
			inactive_customers = inactive_paginator.page(inactive_page)
		except PageNotAnInteger:
			inactive_customers = inactive_paginator.page(1)
		except EmptyPage:
			inactive_customers = inactive_paginator.page(1)  # Redirect to first page on error
		context['inactive_customer_list'] = inactive_customers

		# Preserve all query parameters except page and inactive_page
		query_params = self.request.GET.copy()
		query_params.pop('page', None)
		query_params.pop('inactive_page', None)
		context['query_params'] = query_params.urlencode()

		# Add additional filters info
		context['filters'] = {
			"Distributor": ", ".join(self.distributor_list),
			"Service Area": ", ".join(self.service_area_list)
		}

		return context


class UploadDataView(FormView):
	form_class = UploadDataForm
	template_name = "connection_app/upload_data.html"

	def get_success_url(self):
		return "/"

	def form_valid(self, form):
		form_data = form.cleaned_data
		csv_file = form_data.get('file')
		# csv_file_wrapper = io.TextIOWrapper(csv_file.file, encoding='utf-8')
		csv_file_wrapper = io.TextIOWrapper(csv_file.file, encoding='ISO-8859-1')
		reader = csv.DictReader(csv_file_wrapper)

		# Store the rows in a list of dictionaries
		csv_data = []
		for row in reader:
			try:
				csv_data.append(row)
			except Exception as e:
				print(e)
				continue
		# res = django_rq.enqueue(schedule_upload_data, args=(form_data.get('template'), csv_data))
		# messages.add_message(self.request, messages.INFO, "Job Scheduled: {}".format(res.id))
		schedule_upload_data(form_data.get('template'), csv_data)
		return redirect(self.get_success_url())


class ImportDataView(FormView):
	form_class = ImportDataForm
	template_name = "connection_app/upload_data.html"

	def get_success_url(self):
		return "/"

	def form_valid(self, form):
		form_data = form.cleaned_data
		csv_file = form_data.get('file')
		# Determine the save path for the file
		save_path = os.path.join(settings.MEDIA_ROOT, 'import_data',
								 "import_{}_{}".format(datetime.datetime.now().strftime("%Y%m%d_%H%M%S"), csv_file.name))

		# Save the file to the filesystem
		with open(save_path, 'wb+') as destination:
			for chunk in csv_file.chunks():
				destination.write(chunk)
		id_obj = ImportData.objects.create(import_data_template=form_data.get('template'), file_path=save_path)
		# res = django_rq.enqueue(schedule_upload_data, args=(form_data.get('template'), id_obj))
		# messages.add_message(self.request, messages.INFO, "Job Scheduled: {}".format(res.id))
		schedule_upload_data(form_data.get('template'), id_obj)
		return redirect(self.get_success_url())


class DownloadImportedFileView(View):

	def get(self, request, pk, *args, **kwargs):
		# Retrieve the ImportData instance by primary key (pk)
		import_data = ImportData.objects.get(pk=pk)
		file_path = import_data.file_path

		# Check if file exists
		if not os.path.exists(file_path):
			raise Http404("The requested file does not exist.")

		# Determine the file's MIME type
		mime_type, _ = mimetypes.guess_type(file_path)

		# Open the file in binary mode and prepare the response
		with open(file_path, 'rb') as f:
			response = HttpResponse(f.read(), content_type=mime_type)
			response['Content-Disposition'] = f'attachment; filename={os.path.basename(file_path)}'
		return response


class CancelSalesOrderListView(FormView):
	form_class = CancelAutoGeneratedSalesOrderForm
	template_name = "connection_app/sales-order/cancel_auto_generated_sales_order_listview.html"
	permission = 'has_view_permission'
	paginate_by = 10  # Number of items per page

	def qs(self):
		three_days_ago = datetime.datetime.now().date() - datetime.timedelta(days=3)
		so_list = SalesOrder.objects.filter(
			# auto_generated=True,
			order_date__date__lte=three_days_ago,
			cancellation_camunda_pid__isnull=True,
			order_status__in=[
				SalesOrderStatusEnum.INVOICED,
				SalesOrderStatusEnum.OPEN,
				SalesOrderStatusEnum.RETURNED
			],
			portability_flag=False
		).order_by('order_date')

		return so_list

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)

		sales_orders = self.qs()

		paginator = Paginator(sales_orders, self.paginate_by)
		page = self.request.GET.get('page')

		try:
			sales_orders_page = paginator.page(page)
		except PageNotAnInteger:
			sales_orders_page = paginator.page(1)
		except EmptyPage:
			sales_orders_page = paginator.page(paginator.num_pages)

		context['object_list'] = sales_orders_page
		context['page_obj'] = sales_orders_page
		return context

	def form_valid(self, form):
		# Production Code
		# django_rq.enqueue(
		# 	start_processes_for_return_sales_order_list,
		# 	args=(
		# 		self.qs().values_list('id', flat=True)
		# 	)
		# )

		# Local Code
		start_processes_for_return_sales_order_list(self.qs().values_list('id', flat=True))

		return HttpResponseRedirect(reverse('connection_app:cancel_sales_order_list'))


class BookSalesOrderListView(FormView):
	form_class = BookSalesOrderForm
	template_name = "connection_app/sales-order/book_sales_order_listview.html"
	permission = 'has_view_permission'
	paginate_by = 10  # Number of items per page

	def qs(self):
		return BookSalesOrder.objects.filter(camunda_process_id__isnull=True, error_log__isnull=True)

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)

		sales_orders = self.qs()

		paginator = Paginator(sales_orders, self.paginate_by)
		page = self.request.GET.get('page')

		try:
			sales_orders_page = paginator.page(page)
		except PageNotAnInteger:
			sales_orders_page = paginator.page(1)
		except EmptyPage:
			sales_orders_page = paginator.page(paginator.num_pages)

		context['object_list'] = sales_orders_page
		context['page_obj'] = sales_orders_page
		return context

	def form_valid(self, form):
		# Production Code
		django_rq.enqueue(start_book_sales_order_camunda_process)

		# Local Code
		# start_book_sales_order_camunda_process()
		return HttpResponseRedirect(reverse('connection_app:book_sales_order_list'))


@method_decorator(login_required, 'dispatch')
class OverrideSaleView(FormView):
	form_class = OverrideSalesForm
	template_name = "connection_app/override-sale/override_sale.html"

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		return context

	def form_valid(self, form):
		cleaned_data = form.cleaned_data
		OverrideSale.objects.create(
			phone_no=cleaned_data.get('phone_no'),
			customer_photo=cleaned_data.get('customer_photo'),
			sold_by=get_current_user()
		)
		messages.add_message(self.request, messages.INFO, "Sale Overridden Successfully")
		return HttpResponseRedirect(reverse("connection_app:sales_order_grid_menu_view"))


class OverrideSaleListView(ListView):
	model = OverrideSale
	template_name = "connection_app/override-sale/override_sale_listview.html"
	permission = 'has_view_permission'
	paginate_by = 10  # Number of items per page

	def get_queryset(self):
		return OverrideSale.objects.filter(sold_by=get_current_user()).order_by('-created_on')

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		sales_orders = self.get_queryset()

		paginator = Paginator(sales_orders, self.paginate_by)
		page = self.request.GET.get('page')

		try:
			sales_orders_page = paginator.page(page)
		except PageNotAnInteger:
			sales_orders_page = paginator.page(1)
		except EmptyPage:
			sales_orders_page = paginator.page(paginator.num_pages)

		context['object_list'] = sales_orders_page
		context['page_obj'] = sales_orders_page
		return context


@method_decorator(login_required, 'dispatch')
class PromotionalSaleView(FormView):
	form_class = PromotionalSaleForm
	template_name = "connection_app/promotional-sale/promotional_sale.html"

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		return context

	def form_valid(self, form):
		cleaned_data = form.cleaned_data
		customer: PromotionalSaleCustomer = PromotionalSaleCustomer.objects.filter(
			consumer_id=cleaned_data.get('consumer_id')).first()

		if not customer:
			customer = PromotionalSaleCustomer.objects.create(
				consumer_id=cleaned_data.get('consumer_id'),
				# phone_no=cleaned_data.get('phone_no'),
				customer_name=cleaned_data.get('customer_name'),
				customer_address=cleaned_data.get('customer_address'),
				onboard_by=get_current_user()
			)
		customer.promotional_sales.create(
			phone_no=cleaned_data.get('phone_no'),
			sale_order_no=cleaned_data.get('sale_order_no'),
			cylinder_type=cleaned_data.get('cylinder_type'),
			sold_by=get_current_user(),
			customer_photo=cleaned_data.get('customer_photo'),
			agency_name=cleaned_data.get('agency_name'),
		)
		messages.add_message(self.request, messages.INFO, "Promotional Sale Added Successfully")
		return HttpResponseRedirect(reverse("connection_app:sales_grid_menu_view"))


class PromotionalSaleListView(ListView):
	model = PromotionalSale
	template_name = "connection_app/promotional-sale/promotional_sale_listview.html"
	permission = 'has_view_permission'
	paginate_by = 10  # Number of items per page

	def get_queryset(self):
		# Group by `parent` and count the number of `cylinder_type` where `prize_allocated` is False
		sales = (
			PromotionalSale.objects
			.filter(sold_by=self.request.user, prize_allocated=False)
			.values('parent', 'parent__customer_name', 'parent__customer_address', 'parent__consumer_id', 'cylinder_type')
			.annotate(cylinder_count=Count('cylinder_type'))
			.order_by('-cylinder_count')
		)

		return sales

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		sales_orders = self.get_queryset()

		paginator = Paginator(sales_orders, self.paginate_by)
		page = self.request.GET.get('page')

		try:
			sales_orders_page = paginator.page(page)
		except PageNotAnInteger:
			sales_orders_page = paginator.page(1)
		except EmptyPage:
			sales_orders_page = paginator.page(paginator.num_pages)

		context['object_list'] = sales_orders_page
		context['page_obj'] = sales_orders_page
		return context


class PrizeAllocationListView(ListView):
	model = PrizeAllocation
	template_name = "connection_app/promotional-sale/prize_allocation_listview.html"
	permission = 'has_view_permission'
	paginate_by = 10  # Number of items per page

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		sales_orders = self.get_queryset()

		paginator = Paginator(sales_orders, self.paginate_by)
		page = self.request.GET.get('page')

		try:
			sales_orders_page = paginator.page(page)
		except PageNotAnInteger:
			sales_orders_page = paginator.page(1)
		except EmptyPage:
			sales_orders_page = paginator.page(paginator.num_pages)

		context['object_list'] = sales_orders_page
		context['page_obj'] = sales_orders_page
		return context


@method_decorator(login_required, 'dispatch')
class PromotionalSalePrizeAllocationView(FormView):
	form_class = PromotionalSalePrizeAllocationForm
	template_name = "connection_app/promotional-sale/promotional_sale_prize_allocation.html"

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['promotional_sale_customer'] = PromotionalSaleCustomer.objects.get(id=self.kwargs.get('parent'))
		context['promotional_sales'] = PromotionalSale.objects.filter(
			cylinder_type=self.kwargs.get('cylinder_type'),
			prize_allocated=False, parent_id=self.kwargs.get('parent')).all()
		return context

	def get_form_kwargs(self):
		kwargs = super().get_form_kwargs()

		kwargs['promotional_sale_customer'] = PromotionalSaleCustomer.objects.get(id=self.kwargs.get('parent'))
		kwargs['cylinder_type'] = self.kwargs.get('cylinder_type')
		kwargs['promotional_sales'] = PromotionalSale.objects.filter(
					cylinder_type=self.kwargs.get('cylinder_type'),
					prize_allocated=False, parent_id=self.kwargs.get('parent')).all()
		return kwargs

	def form_invalid(self, form):
		print(form.errors)

	def form_valid(self, form):
		cleaned_data = form.cleaned_data

		pa_obj = PrizeAllocation.objects.create(parent=form.promotional_sale_customer,
		                                        proof_type=cleaned_data.get('proof_type'),
		                                        proof_id_no=cleaned_data.get('proof_id_no'),
		                                        proof_photo_1=cleaned_data.get('proof_photo_1'),
		                                        proof_photo_2=cleaned_data.get('proof_photo_2'),
		                                        prize_given_photo=cleaned_data.get('prize_given_photo'),
		                                        allocated_by=get_current_user())

		for obj in form.promotional_sales:
			obj.prize_allocation = pa_obj
			obj.prize_allocated = True
			obj.save()

		messages.add_message(self.request, messages.INFO, "Promotional Sale Prize Allocated Added Successfully")

		return HttpResponseRedirect(reverse("connection_app:sales_grid_menu_view"))


@method_decorator(login_required, 'dispatch')
class PrizeAllocationView(TemplateView):
	template_name = "connection_app/promotional-sale/prize_allocation.html"

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['prize_allocation'] = PrizeAllocation.objects.get(id=kwargs.get('pk'))
		context['promotional_sales'] = PromotionalSale.objects.filter(prize_allocation_id=kwargs.get('pk')).all()
		return context


def get_customer_details(request):
	phone_no = request.GET.get('phone_no')
	if not phone_no:
		return JsonResponse({'exists': False}, safe=False)

	try:
		customer = PromotionalSaleCustomer.objects.get(phone_no=phone_no)
		return JsonResponse({
			'exists': True,
			'customer_name': customer.customer_name,
			'customer_address': customer.customer_address,
		}, safe=False)
	except PromotionalSale.DoesNotExist:
		return JsonResponse({'exists': False}, safe=False)


def get_customer_details_from_consumer_id(request):
	consumer_id = request.GET.get('consumer_id')
	if not consumer_id:
		return JsonResponse({'exists': False}, safe=False)

	try:
		customer_profile = CustomerProfile.objects.get(consumer_id=consumer_id)

		return JsonResponse({
			'exists': True,
			'customer_name': customer_profile.name,
			'customer_address': customer_profile.address,
			'bsc_due_flag': 'No' if customer_profile.x_bsc_date is not None else 'Yes',
			'ekyc': 'Not Done' if customer_profile.ekyc_flag is None or customer_profile.ekyc_flag == False else 'Done',
			'distributor_name': customer_profile.distributor_name,
			'customer_type': customer_profile.customer_type
		}, safe=False)

	except CustomerProfile.DoesNotExist:
		return JsonResponse({'exists': False}, safe=False)


# Todo: Complete Code For Change Address General Customer
class ChangeAddressView(FormView):
	form_class = ChangeAddressForm
	template_name = "connection_app/change_address.html"

	def dispatch(self, request, *args, **kwargs):
		obj = self.get_object()

		connection_app_content_type = ContentType.objects.get(
			app_label='connection_app', model='customerprofile'
		)

		sr_obj = ServiceRequest.objects.filter(
			content_type=connection_app_content_type,
			object_id=obj.id,
			service_request_type=ServiceRequestTypeEnum.UPDATE_ADDRESS,
			status=ServiceRequestTypeStatusEnum.PENDING
		).first()

		if sr_obj:
			message = f"Service Request For Change Address Already Submitted. Service Request Id: {sr_obj.id} Status: {sr_obj.status}"
			return render(
				self.request, "connection_app/response.html",
				{"heading": "Update Address Request Form", "message": message}
			)
		return super().dispatch(request, *args, **kwargs)

	def get_object(self, queryset=None):
		try:
			obj = CustomerProfile.objects.get(pk=self.kwargs.get('pk'))
		except:
			raise Http404(
				"No application with id: {} found.".format(self.kwargs.get('pk'))
			)
		return obj

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		obj = self.get_object()
		context.update({
			"obj": obj,
		})
		return context

	def form_invalid(self, form):
		print(form.errors)
		return super().form_invalid(form)

	def form_valid(self, form):
		obj: ConnectionApplication = self.get_object()
		cleaned_data = form.cleaned_data
		obj.documents.create(type=ConnectionApplicationDocumentsEnum.UPDATE_ADDRESS_PROOF, link=cleaned_data.get('photo_id'))
		address_json = form.clean()
		user = get_current_user()

		connection_app_content_type = ContentType.objects.get(
			app_label='connection_app', model='customerprofile'
		)

		new_address_json = {
			"address_line_1": f"HNo {address_json.get('house_no')}",
			"address_line_2": f"St No {address_json.get('street_no')}",
			"address_line_3": f"{address_json.get('area')} {address_json.get('phone_number')}",
			"landmark": address_json.get('landmark'),
			"urban_rural": "Urban",
			"local_body": "Ludhiana",
			"sub_district": "Ludhiana (East)",
			"pincode": address_json.get('pincode'),
		}

		service_request = ServiceRequest.objects.create(
			service_request_type=ServiceRequestTypeEnum.UPDATE_ADDRESS,
			content_type=connection_app_content_type,
			object_id=obj.id,
			request_by=user,
			form_data={
				"application_id": obj.id,
				"new_address": new_address_json,
				"dca_app": "connection_app",
				"photo_id": cleaned_data.get('photo_id'),
				"photo_id_number": cleaned_data.get('photo_id_number'),
				"address_json": address_json
			}
		)
		from service_request.functions import start_service_request_process_in_camunda

		variables = {
			"new_address": {"value": json.dumps(new_address_json), "type": "string"},
			"address_json": {"value": json.dumps(address_json), "type": "string"},
			"application_id": {"value": obj.id, "type": "long"},
			"name": {"value": obj.name, "type": "string"},
			# "status": {"value": obj.status, "type": "string"},
			"request_by": {"value": f"{user.first_name} {user.last_name}"},
			"service_request_id": {"value": service_request.id, "type": "long"},
			"dca_app": {"value": "connection_app", "type": "String"},
			"request_type": {"value": ServiceRequestTypeEnum.UPDATE_ADDRESS, "type": "String"},
			"consumer_id": {"value": obj.consumer_id, "type": "String"},
			"distributor_code": {"value": obj.distributor.code, "type": "String"},
			"photo_id": {"value": cleaned_data.get('photo_id'), "type": "String"},
			"photo_id_number": {"value": cleaned_data.get('photo_id_number'), "type": "String"},
		}

		create_job_function = partial(
			django_rq.enqueue,
			start_service_request_process_in_camunda,
			service_request_id=service_request.id,
			variables=variables
		)
		transaction.on_commit(create_job_function)
		# start_service_request_process_in_camunda(service_request.id, variables)
		message = "Service Request For Update Address Initiated. Please Wait For Some Time."

		return render(
			self.request, "connection_app/response.html", {"heading": "Update Address Request Form", "message": message}
		)


class VaultSecretAutocompleteView(autocomplete.Select2QuerySetView):
	def get_queryset(self):
		if not self.request.user.is_authenticated:
			return VaultSecret.objects.none()

		queryset = VaultSecret.objects.filter(
			name__icontains=self.q
		)
		return queryset


@method_decorator(login_required, 'dispatch')
class UpdateDistributorLoginDetailsFormView(FormView):
	form_class = UpdateDistributorLoginDetailsForm

	template_name = 'connection_app/update_distributor_login_details.html'

	def dispatch(self, request, *args, **kwargs):
		user: User = get_current_user()
		if not user.has_perm('connection_app.can_update_distributor_password'):
			return render(
				self.request, "connection_app/response.html",
				{"heading": "Update Distributor Login Details",
				 "message": "You do not have permission to access this page"}
			)
		return super().dispatch(request, *args, **kwargs)

	def form_valid(self, form):
		form.save()
		messages.info(self.request, "Distributor Password Updated Successfully")
		return redirect('.')


@method_decorator(login_required, 'dispatch')
class UpdateSDMSUserLoginPasswordFormView(FormView):
	form_class = UpdateSDMSUserLoginPasswordForm

	template_name = 'connection_app/update_sdms_user_login_password.html'

	def form_valid(self, form):
		form.save()
		messages.info(
			self.request,
			"SDMS Login Id {} Password Updated Successfully.".format(
				form.cleaned_data['sdms_user'].delivery_boy_login
			)
		)
		return redirect('.')


def get_template_details(request):
	template_id = request.GET.get("template_id")
	template = get_object_or_404(ImportDataTemplate, id=template_id)

	return JsonResponse({
		"id": template.id,
		"field_list": template.field_list,
		"description": template.description
	})

@method_decorator(login_required, name='dispatch')
class OmcConversionRequestView(FormView):
	form_class = OmcCylinderConversionForm
	template_name = "connection_app/omc_cylinder_change_request_form.html"

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		return context

	def form_valid(self, form):
		form.save()
		messages.success(self.request, "Conversion Request Successfully Submitted.")
		return HttpResponseRedirect(reverse("connection_app:omc_conversion_request_view"))