import csv
import datetime
import io
import mimetypes
import os

import django_filters
import django_rq
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import F, ExpressionWrapper, fields
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import DetailView, ListView, FormView, TemplateView
from django_currentuser.middleware import get_current_user
from django_filters.views import FilterView

from connection_app.camunda_functions import start_process_return_auto_sales_order
from connection_app.enums import PostInspectionStatusEnum, InspectionTypeEnum, PostInspectionActivityTypeEnum, \
	ConnectionApplicationDocumentsEnum, SalesOrderStatusEnum
from connection_app.forms import UpdateAddressForm, PostInspectionStartForm, PreviewPostInspectionForm, \
	KitchenPostInspectionForm, PostInspectionForm, UIDPostInspectionForm, ProfilePhotoPostInspectionForm, \
	SurakshaPipePostInspectionForm, CustomerProfileSearchForm, GenerateLeadForm, GenerateNonCustomerLeadForm, \
	CustomerProfileDocumentUploadForm, SalesOrderDetailViewForm, SalesOrderPortabilityForm, SDMSServiceAreaForm, \
	UploadDataForm, ImportDataForm, CancelAutoGeneratedSalesOrderForm
from connection_app.jobs import start_sales_order_portability_process, schedule_upload_data
from connection_app.models import ConnectionApplication, PostInspection, CustomerProfile, Lead, SalesOrder, \
	SalesOrderPortability, ImportData
from domestic_app import settings
from reference_data.models import ServiceType, Distributor
from teams.models import SDMSUser, UserProfile


def installation_upload_process_gleam_entry_gate(request):
	application_id = request.GET.get("application_id")
	response = render(request, 'connection_app/fblike.html')
	response.set_cookie('application_id_cookie', application_id)
	return response


def installation_upload_process_gleam_entry_gate_completed(request):
	application_id = request.COOKIES.get('application_id_cookie')
	return redirect('installation_start', pk=application_id)


def index(request):
	# return RedirectView.as_view(url='/connection_app/portal/user_dashboard/', permanent=False)
	return render(request, 'connection_app/index.html')


def web_form_view(request):
	return render(request, "connection_app/web_form.html")
	# def get_context_data(self, **kwargs):
	#     context_data = super().get(**kwargs)
	#     form_fill_area_list = FormFillArea.objects.all()
	#     context_data = context_data.update({
	#         "form_fill_area_list": form_fill_area_list
	#     })
	#     return context_data


class ApplicationStatusView(DetailView):
	model = ConnectionApplication

	def get_template_names(self):
		return 'connection_app/status.html'


class ApplicationReuploadView(DetailView):
	model = ConnectionApplication

	def get_template_names(self):
		return 'connection_app/pendingdata.html'


class ApplicationInstallationView(DetailView):
	model = ConnectionApplication

	def get_template_names(self):
		return 'connection_app/kitchenphoto.html'


@method_decorator(login_required, 'dispatch')
class PostInspectionListView(ListView):
	model = PostInspection
	template_name = 'connection_app/post-inspection/post_inspection_listview.html'

	paginate_by = 20
	permission = 'has_view_permission'

	def get_queryset(self):
		user: User = get_current_user()
		filters = {}
		if not user.is_superuser:
			filters.update({'mechanic': user})
		return PostInspection.objects.filter(**filters).order_by('-submitted_on')


@method_decorator(login_required, 'dispatch')
class PostInspectionStartFormView(FormView):
	model = PostInspection
	template_name = 'connection_app/post-inspection/post_inspection_start_form.html'
	form_class = PostInspectionStartForm

	def form_valid(self, form):
		data = form.cleaned_data

		customer_profile: object = None

		if data.get('consumer_id'):
			customer_profile: CustomerProfile = CustomerProfile.objects.filter(
				consumer_id=data.get('consumer_id')
			).first()

		if not customer_profile:
			if data.get('mobile_number'):
				customer_profile: CustomerProfile = CustomerProfile.objects.filter(
					mobile_number=data.get('mobile_number')
				).first()
				if not customer_profile:
					messages.add_message(
						self.request, messages.ERROR, "No customer found for given mobile number"
					)
					return redirect('connection_app:post_inspection_start')
			else:
				messages.add_message(
					self.request, messages.ERROR, "No customer found for given consumer id"
				)
				return redirect('connection_app:post_inspection_start')

		pi_obj = PostInspection.objects.filter(parent=customer_profile).first()
		if not pi_obj:
			pi_obj = PostInspection.objects.create(
				parent=customer_profile,
				status=PostInspectionStatusEnum.STARTED,
				type=InspectionTypeEnum.MECHANIC,
				mechanic=get_current_user()
			)
			pi_obj.activities.create(activity_type=PostInspectionActivityTypeEnum.KITCHEN_PHOTO_UPDATE)
			pi_obj.activities.create(activity_type=PostInspectionActivityTypeEnum.MAIN_GATE_PHOTO_UPDATE)
			pi_obj.activities.create(activity_type=PostInspectionActivityTypeEnum.PROFILE_PHOTO_UPDATE)
			pi_obj.activities.create(activity_type=PostInspectionActivityTypeEnum.ADDRESS_UPDATE)
			pi_obj.activities.create(activity_type=PostInspectionActivityTypeEnum.UID_PHOTO_UPDATE)
			pi_obj.activities.create(activity_type=PostInspectionActivityTypeEnum.SURAKSHA_PIPE_UPDATE)
			pi_obj.save()

		return redirect('post_inspection_form_view', pk=pi_obj.pk)


@method_decorator(login_required, 'dispatch')
@method_decorator(csrf_exempt, 'dispatch')
class PostInspectionView(FormView):
	model = PostInspection
	template_name = 'connection_app/post-inspection/post_inspection_form.html'
	form_class = PostInspectionForm
	success_url = '.'

	def dispatch(self, request, *args, **kwargs):
		post_inspection = self.get_object()
		if post_inspection.status in (
				PostInspectionStatusEnum.SUBMITTED,
				PostInspectionStatusEnum.ACCEPTED,
		):
			return render(self.request, 'connection_app/post-inspection/post_inspection_status.html', context={
				'post_inspection': post_inspection
			})
		return super().dispatch(request, *args, **kwargs)

	def get_object(self, queryset=None):
		try:
			obj = PostInspection.objects.get(pk=self.kwargs.get('pk'))
		except:
			raise Http404(
				"No %(verbose_name)s found matching the query" %
				{'verbose_name': queryset.model._meta.verbose_name}
			)
		return obj

	def form_valid(self, form):
		return HttpResponseRedirect(self.get_success_url())

	def form_invalid(self, form):
		for error in form.errors.get('__all__'):
			messages.add_message(self.request, messages.ERROR, error)
		return HttpResponseRedirect(".")

	def get_form_kwargs(self):
		kwargs = super().get_form_kwargs()
		kwargs['post_inspection'] = self.get_object()
		return kwargs

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		post_inspection = self.get_object()
		context.update({
			'post_inspection': post_inspection,
			'customer_profile': self.get_object().parent,
			'profile_photo_update': post_inspection.activities.filter(
				activity_type=PostInspectionActivityTypeEnum.PROFILE_PHOTO_UPDATE).first(),
			'uid_photo_update': post_inspection.activities.filter(
				activity_type=PostInspectionActivityTypeEnum.UID_PHOTO_UPDATE).first(),
			'address_update': post_inspection.activities.filter(
				activity_type=PostInspectionActivityTypeEnum.ADDRESS_UPDATE).first(),
			'kitchen_photo_update': post_inspection.activities.filter(
				activity_type=PostInspectionActivityTypeEnum.KITCHEN_PHOTO_UPDATE).first(),
			'main_gate_photo_update': post_inspection.activities.filter(
				activity_type=PostInspectionActivityTypeEnum.MAIN_GATE_PHOTO_UPDATE).first(),
			'suraksha_pipe_update': post_inspection.activities.filter(
				activity_type=PostInspectionActivityTypeEnum.SURAKSHA_PIPE_UPDATE).first()
		})
		return context


@method_decorator(login_required, 'dispatch')
@method_decorator(csrf_exempt, 'dispatch')
class PostInspectionAddressUpdateView(FormView):
	model = PostInspection
	template_name = 'connection_app/post-inspection/update_address.html'
	form_class = UpdateAddressForm
	success_url = '.'

	def dispatch(self, request, *args, **kwargs):
		post_inspection = self.get_object()
		if post_inspection.activities.filter(
			activity_type=PostInspectionActivityTypeEnum.ADDRESS_UPDATE).first().completed:
			return render(
				self.request, "connection_app/response.html",
				{"heading": "Post Inspection", "message": "Address Already Updated".format(kwargs.get('pk'))}
			)
		if post_inspection.status in (
				PostInspectionStatusEnum.SUBMITTED,
				PostInspectionStatusEnum.ACCEPTED,
		):
			return render(self.request, 'connection_app/post-inspection/post_inspection_status.html', context={
				'post_inspection': post_inspection
			})
		return super().dispatch(request, *args, **kwargs)

	def get_object(self, queryset=None):
		try:
			obj = PostInspection.objects.get(pk=self.kwargs.get('pk'))
		except:
			raise Http404(
				"No %(verbose_name)s found matching the query" %
				{'verbose_name': queryset.model._meta.verbose_name}
			)
		return obj

	def form_valid(self, form):
		form.save()
		return redirect('post_inspection_form_view', pk=self.get_object().pk)

	def get_form_kwargs(self):
		kwargs = super().get_form_kwargs()
		kwargs['post_inspection'] = self.get_object()
		return kwargs

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		post_inspection = self.get_object()
		context.update({
			'post_inspection': post_inspection,
			'customer_profile': self.get_object().parent,
		})
		return context


@method_decorator(login_required, 'dispatch')
@method_decorator(csrf_exempt, 'dispatch')
class PostInspectionKitchenPhotoUpdateView(FormView):
	model = PostInspection
	template_name = 'connection_app/post-inspection/update_kitchen_photo.html'
	form_class = KitchenPostInspectionForm
	success_url = '.'

	def dispatch(self, request, *args, **kwargs):
		post_inspection = self.get_object()
		if post_inspection.activities.filter(
			activity_type=PostInspectionActivityTypeEnum.KITCHEN_PHOTO_UPDATE).first().completed:
			return render(
				self.request, "connection_app/response.html",
				{"heading": "Post Inspection", "message": "Kitchen Photo Already Updated".format(kwargs.get('pk'))}
			)
		if post_inspection.status in (
				PostInspectionStatusEnum.SUBMITTED,
				PostInspectionStatusEnum.ACCEPTED,
		):
			return render(self.request, 'connection_app/post-inspection/post_inspection_status.html', context={
				'post_inspection': post_inspection
			})
		return super().dispatch(request, *args, **kwargs)

	def get_object(self, queryset=None):
		try:
			obj = PostInspection.objects.get(pk=self.kwargs.get('pk'))
		except:
			raise Http404(
				"No %(verbose_name)s found matching the query" %
				{'verbose_name': queryset.model._meta.verbose_name}
			)
		return obj

	def form_valid(self, form):
		form.save()
		return redirect('post_inspection_form_view', pk=self.get_object().pk)

	def get_form_kwargs(self):
		kwargs = super().get_form_kwargs()
		kwargs['post_inspection'] = self.get_object()
		return kwargs

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		post_inspection = self.get_object()
		context.update({
			'post_inspection': post_inspection,
			'customer_profile': self.get_object().parent,
		})
		return context


@method_decorator(login_required, 'dispatch')
@method_decorator(csrf_exempt, 'dispatch')
class PostInspectionMainGatePhotoUpdateView(FormView):
	model = PostInspection
	template_name = 'connection_app/post-inspection/update_main_gate_photo.html'
	form_class = PreviewPostInspectionForm
	success_url = '.'

	def dispatch(self, request, *args, **kwargs):
		post_inspection = self.get_object()
		if post_inspection.activities.filter(
			activity_type=PostInspectionActivityTypeEnum.MAIN_GATE_PHOTO_UPDATE).first().completed:
			return render(
				self.request, "connection_app/response.html",
				{"heading": "Post Inspection", "message": "Main Gate Photo Already Updated".format(kwargs.get('pk'))}
			)
		if post_inspection.status in (
				PostInspectionStatusEnum.SUBMITTED,
				PostInspectionStatusEnum.ACCEPTED,
		):
			return render(self.request, 'connection_app/post-inspection/post_inspection_status.html', context={
				'post_inspection': post_inspection
			})
		return super().dispatch(request, *args, **kwargs)

	def get_object(self, queryset=None):
		try:
			obj = PostInspection.objects.get(pk=self.kwargs.get('pk'))
		except:
			raise Http404(
				"No %(verbose_name)s found matching the query" %
				{'verbose_name': queryset.model._meta.verbose_name}
			)
		return obj

	def form_valid(self, form):
		form.save()
		return redirect('post_inspection_form_view', pk=self.get_object().pk)

	def get_form_kwargs(self):
		kwargs = super().get_form_kwargs()
		kwargs['post_inspection'] = self.get_object()
		return kwargs

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		post_inspection = self.get_object()
		context.update({
			'post_inspection': post_inspection,
			'customer_profile': self.get_object().parent,
		})
		return context


@method_decorator(login_required, 'dispatch')
@method_decorator(csrf_exempt, 'dispatch')
class PostInspectionUIDPhotoUpdateView(FormView):
	model = PostInspection
	template_name = 'connection_app/post-inspection/update_uid_photo.html'
	form_class = UIDPostInspectionForm
	success_url = '.'

	def dispatch(self, request, *args, **kwargs):
		post_inspection = self.get_object()
		if post_inspection.activities.filter(
			activity_type=PostInspectionActivityTypeEnum.UID_PHOTO_UPDATE).first().completed:
			return render(
				self.request, "connection_app/response.html",
				{"heading": "Post Inspection", "message": "UID Photos Already Updated".format(kwargs.get('pk'))}
			)
		if post_inspection.status in (
				PostInspectionStatusEnum.SUBMITTED,
				PostInspectionStatusEnum.ACCEPTED,
		):
			return render(self.request, 'connection_app/post-inspection/post_inspection_status.html', context={
				'post_inspection': post_inspection
			})
		return super().dispatch(request, *args, **kwargs)

	def get_object(self, queryset=None):
		try:
			obj = PostInspection.objects.get(pk=self.kwargs.get('pk'))
		except:
			raise Http404(
				"No %(verbose_name)s found matching the query" %
				{'verbose_name': queryset.model._meta.verbose_name}
			)
		return obj

	def form_valid(self, form):
		form.save()
		return redirect('post_inspection_form_view', pk=self.get_object().pk)

	def get_form_kwargs(self):
		kwargs = super().get_form_kwargs()
		kwargs['post_inspection'] = self.get_object()
		return kwargs

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		post_inspection = self.get_object()
		context.update({
			'post_inspection': post_inspection,
			'customer_profile': self.get_object().parent,
		})
		return context


@method_decorator(login_required, 'dispatch')
@method_decorator(csrf_exempt, 'dispatch')
class PostInspectionProfilePhotoUpdateView(FormView):
	model = PostInspection
	template_name = 'connection_app/post-inspection/update_profile_photo.html'
	form_class = ProfilePhotoPostInspectionForm
	success_url = '.'

	def dispatch(self, request, *args, **kwargs):
		post_inspection = self.get_object()
		if post_inspection.activities.filter(
			activity_type=PostInspectionActivityTypeEnum.PROFILE_PHOTO_UPDATE).first().completed:
			return render(
				self.request, "connection_app/response.html",
				{"heading": "Post Inspection", "message": "Profile Photo Already Updated".format(kwargs.get('pk'))}
			)
		if post_inspection.status in (
				PostInspectionStatusEnum.SUBMITTED,
				PostInspectionStatusEnum.ACCEPTED,
		):
			return render(self.request, 'connection_app/post-inspection/post_inspection_status.html', context={
				'post_inspection': post_inspection
			})
		return super().dispatch(request, *args, **kwargs)

	def get_object(self, queryset=None):
		try:
			obj = PostInspection.objects.get(pk=self.kwargs.get('pk'))
		except:
			raise Http404(
				"No %(verbose_name)s found matching the query" %
				{'verbose_name': queryset.model._meta.verbose_name}
			)
		return obj

	def form_valid(self, form):
		form.save()
		return redirect('post_inspection_form_view', pk=self.get_object().pk)

	def get_form_kwargs(self):
		kwargs = super().get_form_kwargs()
		kwargs['post_inspection'] = self.get_object()
		return kwargs

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		post_inspection = self.get_object()
		context.update({
			'post_inspection': post_inspection,
			'customer_profile': self.get_object().parent,
		})
		return context


@method_decorator(login_required, 'dispatch')
@method_decorator(csrf_exempt, 'dispatch')
class PostInspectionSurakshaPipeUpdateView(FormView):
	model = PostInspection
	template_name = 'connection_app/post-inspection/update_suraksha_pipe.html'
	form_class = SurakshaPipePostInspectionForm
	success_url = '.'

	def dispatch(self, request, *args, **kwargs):
		post_inspection = self.get_object()
		if post_inspection.activities.filter(
			activity_type=PostInspectionActivityTypeEnum.SURAKSHA_PIPE_UPDATE).first().completed:
			return render(
				self.request, "connection_app/response.html",
				{"heading": "Post Inspection", "message": "Suraksha Pipe Already Updated".format(kwargs.get('pk'))}
			)

		if post_inspection.status in (
				PostInspectionStatusEnum.SUBMITTED,
				PostInspectionStatusEnum.ACCEPTED,
		):
			return render(self.request, 'connection_app/post-inspection/post_inspection_status.html', context={
				'post_inspection': post_inspection
			})
		return super().dispatch(request, *args, **kwargs)

	def get_object(self, queryset=None):
		try:
			obj = PostInspection.objects.get(pk=self.kwargs.get('pk'))
		except:
			raise Http404(
				"No %(verbose_name)s found matching the query" %
				{'verbose_name': queryset.model._meta.verbose_name}
			)
		return obj

	def form_valid(self, form):
		form.save()
		return redirect('post_inspection_form_view', pk=self.get_object().pk)

	def form_invalid(self, form):
		print(form.errors)
		return redirect('post_inspection_form_view', pk=self.get_object().pk)

	def get_form_kwargs(self):
		kwargs = super().get_form_kwargs()
		kwargs['post_inspection'] = self.get_object()
		return kwargs

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		post_inspection = self.get_object()
		context.update({
			'post_inspection': post_inspection,
			'customer_profile': self.get_object().parent,
		})
		return context


@method_decorator(login_required, 'dispatch')
class CustomerProfileSearchView(FormView):
	template_name = "connection_app/customer_profile_search.html"
	form_class = CustomerProfileSearchForm

	def form_valid(self, form):
		data = form.cleaned_data

		cp_obj = None
		if data.get('consumer_id'):
			cp_obj = CustomerProfile.objects.filter(consumer_id=data.get('consumer_id')).first()
		elif data.get('mobile_number'):
			cp_obj = CustomerProfile.objects.filter(mobile_number=data.get('mobile_number')).first()
		# elif data.get('customer_profile_id'):
		# 	cp_obj = CustomerProfile.objects.filter(pk=data.get('customer_profile_id')).first()

		if not cp_obj:
			messages.add_message(
				self.request, messages.ERROR, "No Record Found For Given Consumer Id or Mobile Number"
			)
			return HttpResponseRedirect(".")

		return redirect('customer_profile', pk=cp_obj.pk)


@method_decorator(login_required, 'dispatch')
class CustomerProfileView(TemplateView):
	template_name = 'connection_app/customer_profile.html'

	def get_object(self, queryset=None):
		try:
			obj = CustomerProfile.objects.get(pk=self.kwargs.get('pk'))
		except:
			raise Http404(
				"No Customer Profile Exist For Given Id"
			)
		return obj

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)

		obj: CustomerProfile = self.get_object()
		context.update({
			"obj": obj,
		})
		return context


@method_decorator(login_required, 'dispatch')
@method_decorator(csrf_exempt, 'dispatch')
class GenerateLeadFormView(FormView):
	model = CustomerProfile
	template_name = 'connection_app/generate_lead_form.html'
	form_class = GenerateLeadForm
	success_url = '.'

	def get_object(self, queryset=None):
		try:
			obj = CustomerProfile.objects.get(pk=self.kwargs.get('pk'))
		except:
			raise Http404(
				"No %(verbose_name)s found matching the query" %
				{'verbose_name': queryset.model._meta.verbose_name}
			)
		return obj

	def form_valid(self, form):
		data = form.cleaned_data
		customer_profile = self.get_object()
		for service_type in data['service_list']:
			Lead.objects.create(
				parent=self.get_object(),
				generated_by=get_current_user(),
				service_type=ServiceType.objects.get(name=service_type),
				name=customer_profile.name,
				mobile_number=customer_profile.mobile_number
			)
		messages.add_message(self.request, messages.INFO,
							 message="Generated Lead Successfully For {}".format(", ".join(data['service_list'])))
		return redirect("customer_profile", pk=self.get_object().pk)

	def get_form_kwargs(self):
		kwargs = super().get_form_kwargs()
		kwargs['service_type_choices'] = tuple(ServiceType.objects.all().values_list('name', 'name'))
		return kwargs

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context.update({
			'customer_profile': self.get_object(),
		})
		return context


@method_decorator(login_required, 'dispatch')
@method_decorator(csrf_exempt, 'dispatch')
class GenerateNonCustomerLeadFormView(FormView):
	template_name = 'connection_app/generate_non_customer_lead_form.html'
	form_class = GenerateNonCustomerLeadForm
	success_url = '.'

	def form_valid(self, form):
		data = form.cleaned_data
		for service_type in data['service_list']:
			Lead.objects.create(
				parent=self.get_object(),
				generated_by=get_current_user(),
				service_type=ServiceType.objects.get(name=service_type),
				name=data['name'],
				mobile_number=data['mobile_number']
			)
		messages.add_message(self.request, messages.INFO,
							 message="Generated Lead Successfully For {}".format(", ".join(data['service_list'])))
		return redirect("customer_profile", pk=self.get_object().pk)

	def get_form_kwargs(self):
		kwargs = super().get_form_kwargs()
		kwargs['service_type_choices'] = tuple(ServiceType.objects.all().values_list('name', 'name'))
		return kwargs


@method_decorator(login_required, 'dispatch')
@method_decorator(csrf_exempt, 'dispatch')
class CustomerProfileDocumentUploadFormView(FormView):
	template_name = 'connection_app/customer_profile_document_upload.html'
	form_class = CustomerProfileDocumentUploadForm
	success_url = '.'

	def get_object(self, queryset=None):
		try:
			obj = CustomerProfile.objects.get(pk=self.kwargs.get('pk'))
		except:
			raise Http404(
				"No %(verbose_name)s found matching the query" %
				{'verbose_name': queryset.model._meta.verbose_name}
			)
		return obj

	def dispatch(self, request, *args, **kwargs):
		customer_profile = self.get_object()

		if customer_profile.documents.filter(type=ConnectionApplicationDocumentsEnum.BANK_SUBSIDY_CERTIFICATE_PHOTO).first():
			messages.add_message(self.request, messages.INFO,
								 f"Bank Subsidy Certificate Document Already Submitted.")
			return redirect("customer_profile", pk=self.get_object().pk)
		return super().dispatch(request, *args, **kwargs)

	def form_valid(self, form):
		data = form.cleaned_data

		customer_profile = self.get_object()
		customer_profile.documents.create(
			type=data['document_type'], link=data['document_link']
		)
		messages.add_message(self.request, messages.INFO, f"{data['document_type']} Document Uploaded Successfully.")
		return redirect("customer_profile", pk=self.get_object().pk)

	def get_context_data(self, **kwargs):
		context = super().get_context_data()
		context.update({
			"customer_profile": self.get_object()
		})
		return context

	def get_form_kwargs(self):
		kwargs = super().get_form_kwargs()
		kwargs['initial'] = {'document_type': ConnectionApplicationDocumentsEnum.BANK_SUBSIDY_CERTIFICATE_PHOTO}
		return kwargs


@method_decorator(login_required, 'dispatch')
class DashboardView(TemplateView):
	template_name = "connection_app/dashboard.html"

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		user = get_current_user()

		context.update({
			"user": user
			# "sales_order_portability_queryset": SalesOrderPortability.objects.filter(user=get_current_user()),
			# "sales_order_portability_status": SalesOrderPortabilityStatusEnum.choices
		})
		return context


class SalesOrderFilter(django_filters.FilterSet):
	class Meta:
		model = SalesOrder
		fields = ['sales_order', 'consumer_name', 'hide_from_view']


@method_decorator(login_required, 'dispatch')
class SalesOrderListView(FilterView):
	model = SalesOrder
	template_name = 'connection_app/sales-order/sales_order_listview.html'

	paginate_by = 10
	permission = 'has_view_permission'
	filterset_class = SalesOrderFilter

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		queryset = self.get_queryset()
		paginator = Paginator(queryset, self.paginate_by)
		page_number = self.request.GET.get('page')
		page_obj = paginator.get_page(page_number)
		context['page_obj'] = page_obj
		return context

	def get_queryset(self):
		current_user = get_current_user()
		qs = SalesOrder.objects.filter(auto_generated=True).order_by('order_date')

		if self.request.GET.get('show_hidden_records') != 'on':
			qs = qs.exclude(hide_from_view=True)

		if current_user.is_superuser:
			return qs

		sdms_user: SDMSUser = SDMSUser.objects.filter(
			parent__user=current_user,
			distributor__name='Arun Indane'
		).first()

		if not sdms_user:
			return SalesOrder.objects.none()

		qs = qs.objects.filter(delivery_boy_login=sdms_user.delivery_boy_login)

		return qs.order_by('order_date')

 
@method_decorator(login_required, 'dispatch')
@method_decorator(csrf_exempt, 'dispatch')
class SalesOrderDetailFormView(FormView):
	template_name = 'connection_app/sales-order/sales_order_detail_view.html'
	form_class = SalesOrderDetailViewForm
	success_url = '.'

	def get_object(self, queryset=None):
		try:
			obj = SalesOrder.objects.get(pk=self.kwargs.get('pk'))
		except:
			raise Http404(
				"No %(verbose_name)s found matching the query" %
				{'verbose_name': queryset.model._meta.verbose_name}
			)
		return obj

	def form_valid(self, form):
		data = form.cleaned_data
		so_obj = self.get_object()
		so_obj.parent.do_not_auto_generate = data['cancel_auto_booking']
		so_obj.parent.save()
		return redirect("sales_order_list")

	def get_context_data(self, **kwargs):
		context = super().get_context_data()
		context.update({
			"sales_order": self.get_object()
		})
		return context


@method_decorator(login_required, 'dispatch')
class CustomerProfileContactsView(TemplateView):

	template_name = "connection_app/customer_profile_contacts.html"

	def get_object(self, queryset=None):
		try:
			obj = CustomerProfile.objects.get(pk=self.kwargs.get('pk'))
		except:
			raise Http404(
				"No %(verbose_name)s found matching the query" %
				{'verbose_name': queryset.model._meta.verbose_name}
			)
		return obj

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context.update({
			"obj": self.get_object()
		})
		return context


@method_decorator(login_required, 'dispatch')
@method_decorator(csrf_exempt, 'dispatch')
class SalesOrderPortabilityFormView(FormView):
	template_name = 'connection_app/sales-order/sales_order_portability.html'
	form_class = SalesOrderPortabilityForm
	success_url = '.'

	def get_object(self, queryset=None):
		try:
			obj = SalesOrder.objects.get(pk=self.kwargs.get('pk'))
		except:
			raise Http404(
				"No %(verbose_name)s found matching the query" %
				{'verbose_name': queryset.model._meta.verbose_name}
			)
		return obj

	def form_valid(self, form):
		data = form.cleaned_data
		sop_obj: SalesOrderPortability = SalesOrderPortability.objects.create(
			sales_order_number=data['sales_order_number'],
			user=get_current_user(),
			distributor_id=data['distributor']
		)
		messages.add_message(self.request, messages.INFO,
							 f"Sales Order Portability Request Initiated. Request Id: {sop_obj.pk}")
		django_rq.enqueue(start_sales_order_portability_process, args=(sop_obj.id,))
		return redirect("connection_app:sales_order_grid_menu_view")

	def get_form_kwargs(self):
		kwargs = super().get_form_kwargs()
		distributor_list = [('', 'Please Select Distributor')]
		distributor_list.extend([
				(obj.id, f"{obj.code} - {obj.name}") for obj in Distributor.objects.all()
			])
		kwargs['distributor_list'] = distributor_list
		return kwargs


class CustomerGridMenuView(TemplateView):
	template_name = 'connection_app/grid_menu.html'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)

		menu = {
			"name": "Customer",
			"items": [
				{
					"name": "Customer Profile",
					"icon": "fa-user",
					"url": reverse("connection_app:customer_profile_search"),
				},
				{
					"name": "Generate Lead",
					"icon": "fa-star",
					"url": reverse("connection_app:customer_profile_search"),
				},
			]
		}

		context.update({
			"menu": menu
		})
		return context


class InspectionGridMenuView(TemplateView):
	template_name = 'connection_app/grid_menu.html'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)

		menu = {
			"name": "Inspection",
			"items": [
				{
					"name": "Start Post Inspection",
					"icon": "fa-user-secret",
					"url": reverse("connection_app:post_inspection_start"),
				},
				{
					"name": "Post Inspection List",
					"icon": "fa-bars",
					"url": reverse("connection_app:post_inspection_list"),
				},
			]
		}

		context.update({
			"menu": menu
		})
		return context


class SalesOrderGridMenuView(TemplateView):
	template_name = 'connection_app/grid_menu.html'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)

		menu = {
			"name": "Sales Order",
			"items": [
				{
					"name": "Sales Order List",
					"icon": "fa-book",
					"url": reverse("connection_app:sales_order_list"),
				},
				{
					"name": "Invoice Sales Order",
					"icon": "fa-credit-card",
					"url": reverse("connection_app:sales_order_portability"),
				},
				{
					"name": "Portability List",
					"icon": "fa-bars",
					"url": reverse("connection_app:sales_order_portability_list"),
				},
				{
					"name": "Customer List",
					"icon": "fa-bars",
					"url": reverse("connection_app:customer_profile_list"),
				}
			]
		}

		context.update({
			"menu": menu
		})
		return context


@method_decorator(login_required, 'dispatch')
class AdminToolsGridMenuView(TemplateView):
	template_name = 'connection_app/grid_menu.html'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)

		menu = {
			"name": "Import",
			"items": [
				{
					"name": "Import Data",
					"icon": "fa-user-secret",
					"url": reverse("connection_app:import_data"),
				},
				{
					"name": "Cancel Auto Sales Order",
					"icon": "fa-user-secret",
					"url": reverse("connection_app:cancel_auto_sales_order_list"),
				},
			]
		}

		context.update({
			"menu": menu
		})
		return context


@method_decorator(login_required, 'dispatch')
class SalesOrderPortabilityListView(ListView):
	model = SalesOrderPortability
	template_name = 'connection_app/sales-order/sales_order_portability_listview.html'

	paginate_by = 20
	permission = 'has_view_permission'

	#
	# def dispatch(self, request, *args, **kwargs):
	# 	if request.method == 'POST':
	# 		return redirect(reverse("connection_app:sales_order_list") + "?hide_from_view={}".format("on"))
	# 	return super().dispatch(request, *args, **kwargs)

	def get_queryset(self):
		current_user = get_current_user()

		if current_user.is_superuser:
			return SalesOrderPortability.objects.all()
		else:
			return SalesOrderPortability.objects.filter(user=get_current_user())

	def get_context_data(self, *, object_list=None, **kwargs):
		context = super().get_context_data(object_list=object_list, **kwargs)
		list_qs = self.get_queryset()
		paginator = Paginator(list_qs, self.paginate_by)

		page = self.request.GET.get('page')

		try:
			list_qs = paginator.page(page)
		except PageNotAnInteger:
			list_qs = paginator.page(1)
		except EmptyPage:
			list_qs = paginator.page(paginator.num_pages)
		context['list_qs'] = list_qs

		return context


@method_decorator(login_required, 'dispatch')
class CustomerProfileListView(ListView):
	model = CustomerProfile
	template_name = 'connection_app/customer-profile/customer_profile_listview.html'

	paginate_by = 20
	permission = 'has_view_permission'

	def __init__(self, **kwargs):
		super().__init__(**kwargs)
		self.service_area_list = []
		self.distributor_list = []

	def dispatch(self, request, *args, **kwargs):
		current_user = get_current_user()
		user_profile = UserProfile.objects.get(user=current_user)

		if not user_profile:
			return

		return super().dispatch(request, *args, **kwargs)

	def get_queryset(self):
		current_user = get_current_user()
		user_profile = UserProfile.objects.get(user=current_user)

		self.service_area_list = user_profile.sdms_service_areas.values_list('area_name', flat=True)
		self.distributor_list = user_profile.sdmsuser_set.values_list('distributor__code', flat=True)

		if self.request.method == 'GET':
			self.service_area_list = self.request.GET.getlist('sdms_service_area') if self.request.GET.getlist(
				'sdms_service_area') else self.service_area_list
			self.distributor_list = self.request.GET.getlist('distributor') if self.request.GET.getlist(
				'distributor') else self.distributor_list

		# Filter CustomerProfile based on the distributor and service area lists
		queryset = CustomerProfile.objects.filter(
			distributor_code__in=self.distributor_list,
			service_area__in=self.service_area_list,
		)

		# Get the current date
		current_date = datetime.datetime.now().date()

		# Annotate with the number of days since the last order
		queryset = queryset.filter(
			salesorder__order_date__isnull=False,
			salesorder__order_status__in=[
				SalesOrderStatusEnum.INVOICED, SalesOrderStatusEnum.INVOICING_IN_PROGRESS
			]
		).annotate(last_order_date=F('salesorder__order_date')).annotate(
			days_since_last_order=ExpressionWrapper(
				current_date - F('last_order_date'),
				output_field=fields.DurationField()
			)
		).order_by('salesorder__order_date')
		# Limit to the first 10 records
		queryset = queryset[:10]

		return queryset

	def get_context_data(self, *, object_list=None, **kwargs):
		context = super().get_context_data(object_list=object_list, **kwargs)
		initial_data = {
			'sdms_service_area': self.request.GET.getlist('sdms_service_area')
		}
		context['filter_form'] = SDMSServiceAreaForm(
			user_profile=UserProfile.objects.get(user=get_current_user()), data=initial_data
		)
		list_qs = self.get_queryset()
		paginator = Paginator(list_qs, self.paginate_by)

		page = self.request.GET.get('page')

		try:
			list_qs = paginator.page(page)
		except PageNotAnInteger:
			list_qs = paginator.page(1)
		except EmptyPage:
			list_qs = paginator.page(paginator.num_pages)
		context['list_qs'] = list_qs

		# Preserve all query parameters
		query_params = self.request.GET.copy()
		if query_params.get('page'):
			query_params.pop('page')
		context['query_params'] = query_params.urlencode()
		context['filters'] = {
			"Distributor": "{}".format(", ".join(self.distributor_list)),
			"Service Area": "{}".format(", ".join(self.service_area_list))
		}

		return context


class UploadDataView(FormView):
	form_class = UploadDataForm
	template_name = "connection_app/upload_data.html"

	def get_success_url(self):
		return "/"

	def form_valid(self, form):
		form_data = form.cleaned_data
		csv_file = form_data.get('file')
		# csv_file_wrapper = io.TextIOWrapper(csv_file.file, encoding='utf-8')
		csv_file_wrapper = io.TextIOWrapper(csv_file.file, encoding='ISO-8859-1')
		reader = csv.DictReader(csv_file_wrapper)

		# Store the rows in a list of dictionaries
		csv_data = []
		for row in reader:
			try:
				csv_data.append(row)
			except Exception as e:
				print(e)
				continue
		# res = django_rq.enqueue(schedule_upload_data, args=(form_data.get('template'), csv_data))
		# messages.add_message(self.request, messages.INFO, "Job Scheduled: {}".format(res.id))
		schedule_upload_data(form_data.get('template'), csv_data)
		return redirect(self.get_success_url())


class ImportDataView(FormView):
	form_class = ImportDataForm
	template_name = "connection_app/upload_data.html"

	def get_success_url(self):
		return "/"

	def form_valid(self, form):
		form_data = form.cleaned_data
		csv_file = form_data.get('file')
		# Determine the save path for the file
		save_path = os.path.join(settings.MEDIA_ROOT, 'import_data',
								 "import_{}_{}".format(datetime.datetime.now().strftime("%Y%m%d_%H%M%S"), csv_file.name))

		# Save the file to the filesystem
		with open(save_path, 'wb+') as destination:
			for chunk in csv_file.chunks():
				destination.write(chunk)
		# res = django_rq.enqueue(schedule_upload_data, args=(form_data.get('template'), id_obj))
		# messages.add_message(self.request, messages.INFO, "Job Scheduled: {}".format(res.id))
		id_obj = ImportData.objects.create(template=form_data.get('template'), file_path=save_path)
		schedule_upload_data(form_data.get('template'), id_obj)
		return redirect(self.get_success_url())


class DownloadImportedFileView(View):

	def get(self, request, pk, *args, **kwargs):
		# Retrieve the ImportData instance by primary key (pk)
		import_data = ImportData.objects.get(pk=pk)
		file_path = import_data.file_path

		# Check if file exists
		if not os.path.exists(file_path):
			raise Http404("The requested file does not exist.")

		# Determine the file's MIME type
		mime_type, _ = mimetypes.guess_type(file_path)

		# Open the file in binary mode and prepare the response
		with open(file_path, 'rb') as f:
			response = HttpResponse(f.read(), content_type=mime_type)
			response['Content-Disposition'] = f'attachment; filename={os.path.basename(file_path)}'
		return response


class CancelAutoGeneratedSalesOrderListView(FormView):
	form_class = CancelAutoGeneratedSalesOrderForm
	template_name = "connection_app/sales-order/cancel_auto_generated_sales_order_listview.html"
	permission = 'has_view_permission'
	paginate_by = 10  # Number of items per page

	def qs(self):
		two_days_ago = datetime.datetime.now().date() - datetime.timedelta(days=2)
		return SalesOrder.objects.filter(
			auto_generated=True,
			order_date__lte=two_days_ago,
			cancellation_camunda_pid__isnull=True
		).exclude(
			order_status__in=[
				SalesOrderStatusEnum.COMPLETED,
				SalesOrderStatusEnum.CANCELLED,
				SalesOrderStatusEnum.NOT_FOUND
			]
		).order_by('order_date')

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)

		sales_orders = self.qs()

		paginator = Paginator(sales_orders, self.paginate_by)
		page = self.request.GET.get('page')

		try:
			sales_orders_page = paginator.page(page)
		except PageNotAnInteger:
			sales_orders_page = paginator.page(1)
		except EmptyPage:
			sales_orders_page = paginator.page(paginator.num_pages)

		context['object_list'] = sales_orders_page
		context['page_obj'] = sales_orders_page
		return context

	def form_valid(self, form):
		for so in self.qs():
			django_rq.enqueue(start_process_return_auto_sales_order, args=(so.id, so.parent.distributor_code,))
		return HttpResponseRedirect(reverse('connection_app:cancel_auto_sales_order_list'))
