# Generated by Django 3.2.12 on 2022-04-18 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0004_organizationinvitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FIXED', 'Fixed'), ('PORTABLE', 'Portable')], max_length=25)),
                ('start_working_hours', models.TimeField()),
                ('end_working_hours', models.TimeField()),
                ('address', models.TextField()),
                ('lat_long', models.CharField(max_length=256)),
                ('enabled', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_locations', to='organizations.organization')),
            ],
        ),
    ]
