# Generated by Django 3.2.12 on 2025-04-22 11:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import djgeojson.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0004_organizationinvitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAreaHex',
            fields=[
                ('hex_bound', models.CharField(blank=True, max_length=512, null=True)),
                ('hex_centroid', models.CharField(blank=True, max_length=512, null=True)),
                ('public_place_point', models.CharField(blank=True, max_length=512, null=True)),
                ('public_place_name', models.CharField(blank=True, max_length=512, null=True)),
                ('public_place_link', models.CharField(blank=True, max_length=512, null=True)),
                ('hex_id', models.CharField(blank=True, max_length=64, null=True)),
                ('cluster_name', models.CharField(blank=True, max_length=256, null=True)),
                ('hex_resolution', models.IntegerField(blank=True, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('service_area', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'service_area_hex',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SDMSServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('area_code', models.CharField(blank=True, max_length=52, null=True)),
                ('area_name', models.CharField(max_length=128)),
                ('distributor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reference_data.distributor')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tn_ancestors_pks', models.TextField(blank=True, default='', editable=False, verbose_name='Ancestors pks')),
                ('tn_ancestors_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Ancestors count')),
                ('tn_children_pks', models.TextField(blank=True, default='', editable=False, verbose_name='Children pks')),
                ('tn_children_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Children count')),
                ('tn_depth', models.PositiveIntegerField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Depth')),
                ('tn_descendants_pks', models.TextField(blank=True, default='', editable=False, verbose_name='Descendants pks')),
                ('tn_descendants_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Descendants count')),
                ('tn_index', models.PositiveIntegerField(default=0, editable=False, verbose_name='Index')),
                ('tn_level', models.PositiveIntegerField(default=1, editable=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Level')),
                ('tn_priority', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='Priority')),
                ('tn_order', models.PositiveIntegerField(default=0, editable=False, verbose_name='Order')),
                ('tn_siblings_pks', models.TextField(blank=True, default='', editable=False, verbose_name='Siblings pks')),
                ('tn_siblings_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Siblings count')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('tn_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tn_children', to='teams.servicearea', verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'Service Area',
                'verbose_name_plural': 'Service Areas',
                'ordering': ['tn_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DELIVERY_BOY', 'Delivery Boy'), ('POS', 'Point Of Sale'), ('STAFF', 'Staff'), ('MANAGER', 'Manager'), ('VOLUNTEER', 'Volunteer')], max_length=32)),
                ('vehicle_no', models.CharField(blank=True, max_length=10, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('sdms_service_areas', models.ManyToManyField(blank=True, null=True, to='teams.SDMSServiceArea')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PROFILE_PHOTO', 'Profile Photo'), ('VEHICLE_PHOTO', 'Vehicle Photo')], max_length=128)),
                ('link', models.URLField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teams.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('type', models.CharField(choices=[('FIXED', 'Fixed'), ('PORTABLE', 'Portable')], max_length=25)),
                ('start_working_hours', models.TimeField()),
                ('end_working_hours', models.TimeField()),
                ('phone_numbers', models.JSONField(blank=True, null=True)),
                ('address', models.TextField()),
                ('enabled', models.BooleanField(default=True)),
                ('entry_point', djgeojson.fields.PointField()),
                ('location_polygon', djgeojson.fields.PolygonField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_locations', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceAreaUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_area', to='teams.servicearea')),
                ('user_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='teams.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SDMSUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_boy_login', models.CharField(max_length=32)),
                ('delivery_boy_password', models.CharField(max_length=128)),
                ('delivery_boy_full_name', models.CharField(blank=True, max_length=256, null=True)),
                ('password_error', models.BooleanField(default=False)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference_data.distributor')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teams.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FormFillArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('service_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_locations', to='teams.servicelocations')),
            ],
        ),
    ]
