# Generated by Django 3.2.12 on 2022-08-13 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0002_servicearea_servicemechanic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicearea',
            name='enabled',
        ),
        migrations.AddField(
            model_name='servicearea',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='mechanic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mechanic', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.DeleteModel(
            name='ServiceMechanic',
        ),
    ]
