# Generated by Django 3.2.12 on 2022-08-13 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0003_auto_20220813_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicearea',
            name='mechanic',
        ),
        migrations.CreateModel(
            name='ServiceAreaMechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mechanic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mechanic', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_area', to='teams.servicearea')),
            ],
        ),
    ]
