# Generated by Django 3.2.12 on 2022-09-19 10:23

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_serviceareamechanic'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelocations',
            name='entry_point',
            field=djgeojson.fields.PointField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicelocations',
            name='location_polygon',
            field=djgeojson.fields.PolygonField(default=1),
            preserve_default=False,
        ),
    ]
