# Generated by Django 3.2.12 on 2022-09-19 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_auto_20220919_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicelocations',
            name='lat_long',
        ),
    ]
