# Generated by Django 3.2.12 on 2022-09-19 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organizationinvitation'),
        ('teams', '0008_remove_servicelocations_lat_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicelocations',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_locations', to='organizations.organization'),
        ),
    ]
