# Generated by Django 3.2.12 on 2022-09-24 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_alter_servicelocations_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormFillArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_locations', to='teams.servicelocations')),
            ],
        ),
    ]
