# Generated by Django 3.2.12 on 2022-09-24 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_formfillarea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formfillarea',
            name='parent',
        ),
        migrations.AddField(
            model_name='formfillarea',
            name='service_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_locations', to='teams.servicelocations'),
        ),
    ]
