# Generated by Django 3.2.12 on 2022-10-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_auto_20220924_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAreaHex',
            fields=[
                ('hex_bound', models.CharField(blank=True, max_length=512, null=True)),
                ('hex_centroid', models.CharField(blank=True, max_length=512, null=True)),
                ('public_place_point', models.CharField(blank=True, max_length=512, null=True)),
                ('public_place_name', models.CharField(blank=True, max_length=512, null=True)),
                ('public_place_link', models.CharField(blank=True, max_length=512, null=True)),
                ('hex_id', models.CharField(blank=True, max_length=64, null=True)),
                ('cluster_name', models.CharField(blank=True, max_length=256, null=True)),
                ('hex_resolution', models.IntegerField(blank=True, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('service_area', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
