# Generated by Django 3.2.12 on 2022-10-15 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0012_serviceareahex'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceareahex',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DELIVERY_BOY', 'Delivery Boy'), ('POS', 'Point Of Sale'), ('STAFF', 'Staff'), ('MANAGER', 'Manager'), ('VOLUNTEER', 'Volunteer')], max_length=32)),
                ('photo', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
