# Generated by Django 3.2.12 on 2022-10-15 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0013_auto_20221015_0936'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='serviceareahex',
            table='service_area_hex',
        ),
    ]
