# Generated by Django 3.2.12 on 2024-05-04 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0014_alter_serviceareahex_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='photo',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vehicle_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='UserProfileDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PROFILE_PHOTO', 'Profile Photo'), ('VEHICLE_PHOTO', 'Vehicle Photo')], max_length=128)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teams.userprofile')),
            ],
        ),
    ]
