# Generated by Django 3.2.12 on 2022-06-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('reference_number', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('otp', models.CharField(max_length=8)),
                ('mobile', models.CharField(max_length=16)),
                ('channel', models.CharField(choices=[('SMS', 'Sms'), ('VOICE', 'Voice'), ('WHATSAPP', 'Whatsapp')], max_length=32)),
                ('extra', models.JSONField()),
                ('variables', models.JSONField()),
                ('valid_till', models.DateTimeField()),
                ('closed', models.BooleanField(default=False)),
            ],
        ),
    ]
