# Generated by Django 3.2.12 on 2025-04-22 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('reference_number', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('otp', models.CharField(max_length=8)),
                ('mobile', models.CharField(max_length=16)),
                ('channel', models.CharField(choices=[('SMS', 'Sms'), ('VOICE', 'Voice'), ('WHATSAPP', 'Whatsapp')], max_length=32)),
                ('extra', models.JSONField()),
                ('variables', models.JSONField(blank=True, null=True)),
                ('valid_till', models.DateTimeField()),
                ('closed', models.BooleanField(default=False)),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('transition', models.CharField(blank=True, max_length=256, null=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
