# Generated by Django 3.2.12 on 2025-04-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OMCDedup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captcha_text', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'verbose_name': 'OMC Dedup Captcha',
            },
        ),
        migrations.CreateModel(
            name='SdmsCustomerRecord',
            fields=[
                ('consumer_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('kyc_date', models.DateField()),
                ('name', models.CharField(max_length=256)),
                ('waitlist_status', models.CharField(max_length=64)),
                ('nic_status', models.CharField(max_length=64)),
                ('omc_status', models.CharField(max_length=64)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SdmsFamilyMemberRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_id', models.CharField(max_length=64)),
                ('dca_id', models.IntegerField()),
                ('relation', models.CharField(max_length=64)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('dob', models.DateField()),
            ],
        ),
    ]
