# Generated by Django 3.2.12 on 2022-07-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SdmsCustomerRecord',
            fields=[
                ('consumer_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('kyc_date', models.DateField()),
                ('waitlist_status', models.CharField(max_length=64)),
                ('nic_status', models.CharField(max_length=64)),
                ('kyc_status', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=256)),
                ('address', models.TextField()),
            ],
        ),
    ]
