# Generated by Django 3.2.12 on 2022-07-07 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sdmscustomerrecord',
            old_name='kyc_status',
            new_name='omc_status',
        ),
    ]
