# Generated by Django 3.2.12 on 2022-07-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdms', '0002_rename_kyc_status_sdmscustomerrecord_omc_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdmscustomerrecord',
            name='contact_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
