# Generated by Django 3.2.12 on 2022-09-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdms', '0003_sdmscustomerrecord_contact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SdmsFamilyMemberRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_id', models.CharField(max_length=64)),
                ('relation', models.CharField(max_length=64)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
            ],
        ),
    ]
