# Generated by Django 3.2.12 on 2022-09-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdms', '0004_sdmsfamilymemberrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdmsfamilymemberrecord',
            name='dca_id',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
