# Generated by Django 3.2.12 on 2025-03-12 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0002_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
