# Generated by Django 4.0.2 on 2022-02-02 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('mobile', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('application_type', models.CharField(choices=[('NEW_CONNECTION', 'New Connection'), ('BLUE_BOOK', 'Blue Book')], max_length=25)),
                ('item_code', models.CharField(choices=[('FC5', '5 KGs Cylinder'), ('FC14', '14 KGs Cylinder')], max_length=25)),
                ('connection_type', models.CharField(choices=[('SINGLE', 'Single'), ('DOUBLE', 'Double')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ConnectionApplicationDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('UID_FRONT', 'UID - Aadhar Card Front'), ('UID_BACK', 'UID - Aadhar Card Back'), ('CUSTOMER_PHOTO', 'Customer Photo'), ('BANK_DETAIL', 'Bank Detail'), ('SV', 'Subscription Voucher'), ('CONNECTION_DETAIL', 'Connection Detail')], max_length=25)),
                ('link', models.URLField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='connection_app.connectionapplication')),
            ],
        ),
    ]
