# Generated by Django 4.0.2 on 2022-02-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionapplication',
            name='camunda_process_id',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
        migrations.AddField(
            model_name='connectionapplication',
            name='referral_code',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
