# Generated by Django 4.0.2 on 2022-02-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_app', '0002_connectionapplication_camunda_process_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionapplication',
            name='state',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
