# Generated by Django 4.0.2 on 2022-02-03 11:17

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('connection_app', '0003_connectionapplication_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionapplication',
            name='status',
            field=django_fsm.FSMField(choices=[('DRAFT', 'Draft'), ('READY_TO_CALL', 'Ready To Call')], default='DRAFT', max_length=50),
        ),
        migrations.AlterField(
            model_name='connectionapplicationdocuments',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='connection_app.connectionapplication'),
        ),
    ]
