# Generated by Django 4.0.2 on 2022-02-03 12:06

from django.db import migrations, models
import django.utils.timezone
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('connection_app', '0004_connectionapplication_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionapplication',
            name='applicant_remarks',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='connectionapplication',
            name='process_type',
            field=models.CharField(choices=[('NEW_CONNECTION', 'New Connection'), ('REGULARISATION', 'Regularisation'), ('REEVALUATION', 'Re-Evaluation')], default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='connectionapplication',
            name='required_by',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='connectionapplication',
            name='status',
            field=django_fsm.FSMField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('NOT_INTERESTED', 'Not Interested'), ('BACK_OFFICE', 'Back Office'), ('FRONT_OFFICE', 'Front Office'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=50),
        ),
    ]
