# Generated by Django 4.0.2 on 2022-02-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_app', '0005_connectionapplication_applicant_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionapplication',
            name='applicant_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='connectionapplication',
            name='process_type',
            field=models.CharField(blank=True, choices=[('NEW_CONNECTION', 'New Connection'), ('REGULARISATION', 'Regularisation'), ('REEVALUATION', 'Re-Evaluation')], max_length=25, null=True),
        ),
    ]
