# Generated by Django 4.0.2 on 2022-02-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_app', '0006_alter_connectionapplication_applicant_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionapplication',
            name='consumer_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='connectionapplication',
            name='process_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
