# Generated by Django 4.0.2 on 2022-02-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_app', '0007_connectionapplication_consumer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionapplication',
            name='consumer_id',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='connectionapplication',
            name='process_type',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
