# Generated by Django 4.0.2 on 2022-02-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_app', '0008_alter_connectionapplication_consumer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionapplication',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
