# Generated by Django 3.2.12 on 2022-02-04 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connection_app', '0009_connectionapplication_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectionapplication',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='connectionapplication',
            name='state',
        ),
    ]
