# Generated by Django 3.2.12 on 2022-02-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_app', '0010_auto_20220204_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectionapplication',
            name='camunda_process_id',
        ),
        migrations.AlterField(
            model_name='connectionapplication',
            name='process_type',
            field=models.CharField(blank=True, choices=[('NEW_CONNECTION', 'New Connection'), ('REGULARISATION', 'Regularisation'), ('REEVALUATION', 'Re-Evaluation')], max_length=25, null=True),
        ),
    ]
