# Generated by Django 3.2.12 on 2022-02-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_app', '0011_auto_20220204_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionapplication',
            name='communication_mode',
            field=models.CharField(blank=True, choices=[('WHATSAPP', 'WhatsApp'), ('SMS', 'SMS')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='connectionapplication',
            name='process_type',
            field=models.CharField(blank=True, choices=[('NEW_CONNECTION', 'New Connection'), ('REGULARISATION', 'Regularisation'), ('REACTIVATION', 'Re-Activation')], max_length=25, null=True),
        ),
    ]
