# Generated by Django 3.2.12 on 2022-02-05 12:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('connection_app', '0012_auto_20220205_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionapplication',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='connectionapplication',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
