# Generated by Django 3.2.12 on 2022-02-15 12:54

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('connection_app', '0013_auto_20220205_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionapplication',
            name='status',
            field=django_fsm.FSMField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('NOT_INTERESTED', 'Not Interested'), ('BACK_OFFICE', 'Back Office'), ('FRONT_OFFICE', 'Front Office'), ('FRONT_OFFICE_SV', 'Front Office SV'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=50),
        ),
        migrations.AlterField(
            model_name='connectionapplicationdocuments',
            name='type',
            field=models.CharField(choices=[('UID_FRONT', 'UID - Aadhar Card Front'), ('UID_BACK', 'UID - Aadhar Card Back'), ('CUSTOMER_PHOTO', 'Customer Photo'), ('BANK_DETAIL', 'Bank Detail'), ('OTHER_ID_PROOF', 'Other Id Proof'), ('SV', 'Subscription Voucher'), ('CONNECTION_DETAIL', 'Connection Detail')], max_length=25),
        ),
    ]
