# Generated by Django 3.2.12 on 2022-02-21 11:41

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('connection_app', '0014_auto_20220215_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionapplication',
            name='last_execution_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='connectionapplication',
            name='status',
            field=django_fsm.FSMField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('NOT_INTERESTED', 'Not Interested'), ('BACK_OFFICE', 'Back Office'), ('FRONT_OFFICE', 'Front Office'), ('FRONT_OFFICE_SV', 'Front Office SV'), ('COMPLETED', 'Completed'), ('EDIT_APPLICATION', 'Edit Application')], default='DRAFT', max_length=50),
        ),
    ]
