# Generated by Django 3.2.12 on 2022-03-17 06:57

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('connection_app', '0015_auto_20220221_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionapplication',
            name='installation_status',
            field=django_fsm.FSMField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('ACCEPTED', 'Accepted'), ('REUPLOAD', 'Reupload')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='connectionapplication',
            name='status',
            field=django_fsm.FSMField(choices=[('EDIT_APPLICATION', 'Edit Application'), ('SUBMITTED', 'Submitted'), ('NOT_INTERESTED', 'Not Interested'), ('BACK_OFFICE_START', 'Back Office Start'), ('BACK_OFFICE_END', 'Back Office End'), ('FRONT_OFFICE', 'Front Office'), ('COMPLETED', 'Completed'), ('REUPLOAD', 'Reupload')], default='SUBMITTED', max_length=50),
        ),
    ]
