# Generated by Django 3.2.12 on 2022-03-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_app', '0016_auto_20220317_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionapplication',
            name='documents_required_for_reupload',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connectionapplication',
            name='documents_reupload_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
