# Generated by Django 3.2.12 on 2022-03-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_app', '0017_auto_20220317_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionapplicationdocuments',
            name='type',
            field=models.CharField(choices=[('UID_FRONT', 'UID - Aadhar Card Front'), ('UID_BACK', 'UID - Aadhar Card Back'), ('CUSTOMER_PHOTO', 'Customer Photo'), ('BANK_DETAIL', 'Bank Detail'), ('OTHER_ID_PROOF', 'Other Id Proof'), ('SV', 'Subscription Voucher'), ('CONNECTION_DETAIL', 'Connection Detail'), ('KITCHEN_PHOTO', 'Kitchen Photo')], max_length=25),
        ),
    ]
