# Generated by Django 3.2.12 on 2025-11-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujjwala_v3', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ujjwalav3application',
            name='aadhaar_verification_status',
        ),
        migrations.RemoveField(
            model_name='ujjwalav3application',
            name='address_verification_status',
        ),
        migrations.RemoveField(
            model_name='ujjwalav3application',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='ujjwalav3application',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='ujjwalav3application',
            name='connection_issued_at',
        ),
        migrations.RemoveField(
            model_name='ujjwalav3application',
            name='robo_execution_failed_count',
        ),
        migrations.RemoveField(
            model_name='ujjwalav3application',
            name='verification_started_at',
        ),
        migrations.RemoveField(
            model_name='ujjwalav3familymember',
            name='uid_back_compressed',
        ),
        migrations.RemoveField(
            model_name='ujjwalav3familymember',
            name='uid_front_compressed',
        ),
        migrations.AlterField(
            model_name='ujjwalav3document',
            name='doc_type',
            field=models.CharField(choices=[('CURRENT_ADDRESS_POA', 'Current Address Proof of Address'), ('PERMANENT_ADDRESS_POA', 'Permanent Address Proof of Address'), ('FAMILY_COMPOSITION_DOC', 'Family Composition / Ration Card'), ('MIGRANT_DECLARATION', 'Migrant Declaration (Annexure-I)'), ('DEPRIVATION_DECLARATION', 'Deprivation Declaration'), ('BANK_PROOF', 'Bank Proof (Passbook/Statement/Cheque)'), ('BANK_PASSBOOK', 'Bank Passbook Copy'), ('CANCELLED_CHEQUE', 'Cancelled Cheque'), ('APPLICANT_PHOTO', 'Applicant Photograph'), ('FAMILY_PHOTO', 'Family Photograph'), ('KITCHEN_PHOTO', 'Kitchen Photograph'), ('LPG_INSTALLATION_AREA_PHOTO', 'LPG Installation Area Photo'), ('APPLICANT_SIGNATURE', 'Applicant Signature'), ('IDENTITY_PROOF', 'Identity Proof'), ('CASTE_CERTIFICATE', 'Caste Certificate'), ('INCOME_CERTIFICATE', 'Income Certificate'), ('OTHER', 'Other Supporting Document')], db_index=True, help_text='Type of document', max_length=50),
        ),
    ]
