# Generated by Django 3.2.12 on 2025-11-19 06:44

import django.core.validators
from django.db import migrations, models
import taggit.managers
import ujjwala_v3.validators


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('ujjwala_v3', '0002_add_uid_photo_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ujjwalav3address',
            name='ujjwala_v3_addr_app_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='ujjwalav3address',
            name='ujjwala_v3_addr_state_dist_idx',
        ),
        migrations.RemoveIndex(
            model_name='ujjwalav3address',
            name='ujjwala_v3_addr_pincode_idx',
        ),
        migrations.RemoveIndex(
            model_name='ujjwalav3application',
            name='ujjwala_v3_status_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='ujjwalav3application',
            name='ujjwala_v3_mobile_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='ujjwalav3application',
            name='ujjwala_v3_aadhaar_idx',
        ),
        migrations.RemoveIndex(
            model_name='ujjwalav3application',
            name='ujjwala_v3_app_number_idx',
        ),
        migrations.RemoveIndex(
            model_name='ujjwalav3application',
            name='ujjwala_v3_submitted_idx',
        ),
        migrations.RemoveIndex(
            model_name='ujjwalav3auditlog',
            name='ujjwala_v3_audit_app_act_idx',
        ),
        migrations.RemoveIndex(
            model_name='ujjwalav3auditlog',
            name='ujjwala_v3_audit_actor_idx',
        ),
        migrations.RemoveIndex(
            model_name='ujjwalav3document',
            name='ujjwala_v3_doc_app_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='ujjwalav3document',
            name='ujjwala_v3_doc_fm_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='ujjwalav3document',
            name='ujjwala_v3_doc_addr_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='ujjwalav3document',
            name='ujjwala_v3_doc_verified_idx',
        ),
        migrations.RemoveIndex(
            model_name='ujjwalav3familymember',
            name='ujjwala_v3_fm_app_rel_idx',
        ),
        migrations.RemoveIndex(
            model_name='ujjwalav3familymember',
            name='ujjwala_v3_fm_aadhaar_idx',
        ),
        migrations.AddField(
            model_name='ujjwalav3application',
            name='accuracy',
            field=models.CharField(blank=True, help_text='GPS accuracy of the location coordinates', max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='ujjwalav3application',
            name='ekyc_channel',
            field=models.CharField(blank=True, help_text='Channel through which eKYC was performed (e.g., Aadhaar, DigiLocker)', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='ujjwalav3application',
            name='ekyc_cleared',
            field=models.BooleanField(default=False, help_text='Whether eKYC verification has been cleared/passed'),
        ),
        migrations.AddField(
            model_name='ujjwalav3application',
            name='ekyc_date',
            field=models.DateTimeField(blank=True, help_text='Date and time when eKYC was performed', null=True),
        ),
        migrations.AddField(
            model_name='ujjwalav3application',
            name='ekyc_last_attempt_log',
            field=models.TextField(blank=True, help_text='Log of the last eKYC attempt (error messages, responses)', null=True),
        ),
        migrations.AddField(
            model_name='ujjwalav3application',
            name='latitude',
            field=models.CharField(blank=True, help_text='Latitude coordinate for application location', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='ujjwalav3application',
            name='longitude',
            field=models.CharField(blank=True, help_text='Longitude coordinate for application location', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='ujjwalav3application',
            name='marital_status',
            field=models.CharField(choices=[('MARRIED', 'Married'), ('UNMARRIED', 'Unmarried'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed'), ('SEPARATED', 'Separated')], default='MARRIED', help_text='Marital status of the applicant', max_length=25),
        ),
        migrations.AddField(
            model_name='ujjwalav3application',
            name='marriage_date',
            field=models.DateField(blank=True, help_text='Date of marriage (if applicable)', null=True),
        ),
        migrations.AddField(
            model_name='ujjwalav3application',
            name='robo_execution_failed_count',
            field=models.IntegerField(blank=True, default=0, help_text='Count of failed robotic process automation attempts', null=True),
        ),
        migrations.AddField(
            model_name='ujjwalav3application',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Tags for categorization and filtering', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='ujjwalav3application',
            name='version',
            field=models.CharField(default='V3', help_text='Version of the Ujjwala application (V2, V3)', max_length=2),
        ),
        migrations.AlterField(
            model_name='ujjwalav3address',
            name='pincode',
            field=models.CharField(db_index=True, help_text='6-digit pincode', max_length=6, validators=[ujjwala_v3.validators.validate_pincode, django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(6)]),
        ),
        migrations.AlterField(
            model_name='ujjwalav3application',
            name='applicant_aadhaar_number',
            field=models.CharField(db_index=True, help_text='12-digit Aadhaar number (unique)', max_length=12, unique=True, validators=[ujjwala_v3.validators.validate_aadhaar_number, django.core.validators.MinLengthValidator(12), django.core.validators.MaxLengthValidator(12)]),
        ),
        migrations.AlterField(
            model_name='ujjwalav3application',
            name='applicant_dob',
            field=models.DateField(db_index=True, help_text='Date of birth as per Aadhaar (Must be >= 18 years)', validators=[ujjwala_v3.validators.validate_adult_dob, ujjwala_v3.validators.validate_future_date]),
        ),
        migrations.AlterField(
            model_name='ujjwalav3application',
            name='applicant_first_name',
            field=models.CharField(help_text='First name of applicant', max_length=100, validators=[ujjwala_v3.validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='ujjwalav3application',
            name='applicant_full_name',
            field=models.CharField(db_index=True, help_text='Full name of applicant as per Aadhaar', max_length=200, validators=[ujjwala_v3.validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='ujjwalav3application',
            name='applicant_last_name',
            field=models.CharField(blank=True, help_text='Last name of applicant (optional)', max_length=100, null=True, validators=[ujjwala_v3.validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='ujjwalav3application',
            name='applicant_middle_name',
            field=models.CharField(blank=True, help_text='Middle name of applicant (optional)', max_length=100, null=True, validators=[ujjwala_v3.validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='ujjwalav3application',
            name='applicant_mobile',
            field=models.CharField(db_index=True, help_text='10-digit mobile number', max_length=10, validators=[ujjwala_v3.validators.validate_mobile_number, django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='ujjwalav3application',
            name='bank_account_name',
            field=models.CharField(help_text='Account holder name as per bank records', max_length=200, validators=[ujjwala_v3.validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='ujjwalav3application',
            name='bank_account_number',
            field=models.CharField(help_text='Bank account number (9-18 characters)', max_length=18, validators=[ujjwala_v3.validators.validate_bank_account_number]),
        ),
        migrations.AlterField(
            model_name='ujjwalav3application',
            name='bank_ifsc',
            field=models.CharField(db_index=True, help_text='11-character IFSC code', max_length=11, validators=[ujjwala_v3.validators.validate_ifsc_code, django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(11)]),
        ),
        migrations.AlterField(
            model_name='ujjwalav3familymember',
            name='aadhaar_number',
            field=models.CharField(db_index=True, help_text='12-digit Aadhaar number', max_length=12, validators=[ujjwala_v3.validators.validate_aadhaar_number, django.core.validators.MinLengthValidator(12), django.core.validators.MaxLengthValidator(12)]),
        ),
        migrations.AlterField(
            model_name='ujjwalav3familymember',
            name='dob',
            field=models.DateField(help_text='Date of birth as per Aadhaar', validators=[ujjwala_v3.validators.validate_future_date]),
        ),
        migrations.AlterField(
            model_name='ujjwalav3familymember',
            name='full_name',
            field=models.CharField(help_text='Full name as per Aadhaar', max_length=200, validators=[ujjwala_v3.validators.validate_name]),
        ),
        migrations.AddIndex(
            model_name='ujjwalav3address',
            index=models.Index(fields=['application', 'address_type'], name='ujjwala_v3__applica_fba146_idx'),
        ),
        migrations.AddIndex(
            model_name='ujjwalav3address',
            index=models.Index(fields=['state', 'district'], name='ujjwala_v3__state_a6a378_idx'),
        ),
        migrations.AddIndex(
            model_name='ujjwalav3address',
            index=models.Index(fields=['pincode'], name='ujjwala_v3__pincode_fea748_idx'),
        ),
        migrations.AddIndex(
            model_name='ujjwalav3application',
            index=models.Index(fields=['status', 'created_at'], name='ujjwala_v3__status_77e45c_idx'),
        ),
        migrations.AddIndex(
            model_name='ujjwalav3application',
            index=models.Index(fields=['applicant_mobile', 'status'], name='ujjwala_v3__applica_b0f9da_idx'),
        ),
        migrations.AddIndex(
            model_name='ujjwalav3application',
            index=models.Index(fields=['applicant_aadhaar_number'], name='ujjwala_v3__applica_169863_idx'),
        ),
        migrations.AddIndex(
            model_name='ujjwalav3application',
            index=models.Index(fields=['application_number'], name='ujjwala_v3__applica_59c8f1_idx'),
        ),
        migrations.AddIndex(
            model_name='ujjwalav3application',
            index=models.Index(fields=['submitted_at'], name='ujjwala_v3__submitt_fadfdd_idx'),
        ),
        migrations.AddIndex(
            model_name='ujjwalav3auditlog',
            index=models.Index(fields=['application', 'action', '-created_at'], name='ujjwala_v3__applica_97fa3b_idx'),
        ),
        migrations.AddIndex(
            model_name='ujjwalav3auditlog',
            index=models.Index(fields=['actor', '-created_at'], name='ujjwala_v3__actor_i_b0a410_idx'),
        ),
        migrations.AddIndex(
            model_name='ujjwalav3document',
            index=models.Index(fields=['application', 'doc_type'], name='ujjwala_v3__applica_dd7909_idx'),
        ),
        migrations.AddIndex(
            model_name='ujjwalav3document',
            index=models.Index(fields=['family_member', 'doc_type'], name='ujjwala_v3__family__e14195_idx'),
        ),
        migrations.AddIndex(
            model_name='ujjwalav3document',
            index=models.Index(fields=['address', 'doc_type'], name='ujjwala_v3__address_110922_idx'),
        ),
        migrations.AddIndex(
            model_name='ujjwalav3document',
            index=models.Index(fields=['is_verified', 'doc_type'], name='ujjwala_v3__is_veri_fe7961_idx'),
        ),
        migrations.AddIndex(
            model_name='ujjwalav3familymember',
            index=models.Index(fields=['application', 'relation_to_applicant'], name='ujjwala_v3__applica_85c018_idx'),
        ),
        migrations.AddIndex(
            model_name='ujjwalav3familymember',
            index=models.Index(fields=['aadhaar_number'], name='ujjwala_v3__aadhaar_a84cac_idx'),
        ),
    ]
