# Generated by Django 3.2.12 on 2025-04-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InactiveCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('distributor_code', models.CharField(max_length=10, null=True)),
                ('distributor_name', models.CharField(max_length=25, null=True)),
                ('consumer_id', models.CharField(max_length=25, null=True)),
                ('consumer_number', models.CharField(max_length=12, null=True)),
                ('consumer_name', models.CharField(max_length=50)),
                ('order_type', models.CharField(max_length=10, null=True)),
                ('inactive_type', models.CharField(default='DEACTIVATED', max_length=15)),
            ],
        ),
    ]
