# Generated by Django 3.2.12 on 2022-02-21 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inactive_customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inactivecustomer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='inactivecustomer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='inactivecustomer',
            name='phone_number',
        ),
    ]
