# Generated by Django 3.2.12 on 2022-02-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inactive_customers', '0002_auto_20220221_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inactivecustomer',
            name='consumer_id',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='inactivecustomer',
            name='consumer_number',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='inactivecustomer',
            name='distributor_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='inactivecustomer',
            name='distributor_name',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
