"""
Django settings for domestic_app project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/`
For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os # new

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '-kk-(hob87ggtv0cttw13mh_3m%^h7!9nhf$)=leaf&gzyv%+c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'material',
    'material.frontend',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'rest_framework',
    'corsheaders',
    'organizations',
    'communication_log',

    'django_rq',

    'django_fsm',
    'django_fsm_log',
    'fsm_admin2',
    'fsm_admin2_custom',
    'import_export',
    'django_filters',
    'advanced_filters',

    'connection_app',
    'inactive_customers',


    'rangefilter',
    'django_admin_listfilter_dropdown',
    'referral',
    'teams',
    'formtools',
    'otp',
    'ujjwala.apps.UjjwalaAppConfig',
    'sdms'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django_currentuser.middleware.ThreadLocalUserMiddleware',

]

ROOT_URLCONF = 'domestic_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'domestic_app.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3'
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGIN_REDIRECT_URL = '/'

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'


USE_I18N = True

USE_L10N = True

USE_TZ = True


CORS_ORIGIN_ALLOW_ALL = True

INTERAKT_API_KEY = "HmtU2CH6poGN_TU-XqCtwuvef8utPNRJRlamfbWXTwg"

# CAMUNDA_BASE_URL = "http://192.168.1.77:25252/engine-rest"
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/


#DataFlair #Django #Static files
STATIC_URL = '/static/'
#--------------------------------------------------
STATIC_ROOT = os.path.join(BASE_DIR, 'root')
#-----------------------------------------------------
STATICFILES_DIRS = [
        os.path.join(BASE_DIR, 'static'),
]

RQ_QUEUES = {
    'default': {
        'HOST': 'dca.arungas.com',
        'PORT': 56379,
        'DB': 0,
        # 'PASSWORD': 'some-password',
        'DEFAULT_TIMEOUT': 360,
        'ASYNC': False
    }
}

# If you need custom exception handlers
RQ_EXCEPTION_HANDLERS = ['path.to.my.handler']

BASE_URL = 'https://dca.arungas.com'

# MINIO_UPLOAD_URL = "http://files.dca.arungas.com"
MINIO_PUBLIC_URL = "http://localhost:59000"

# MINIO_ENDPOINT = "files.dca.arungas.com"
MINIO_API_ENDPOINT = "localhost:59000"

MINIO_BUCKET_NAME = "domesticconnectionapplicationdocs"

MINIO_CREDENTIAL = {
    "access_key": "A105SYTFQ5D152QNMM4G",
    "secret_key": "i4ETnrqIWHdOABwhOP8xnWcnlZQdLPRbi0T2dCDF"
}

HTML_TO_PDF_SERVER_URL = "http://localhost:58080".format(BASE_URL)

THUMBOR_URL = "http://dca.arungas.com:6988/unsafe/fit-in/1920x1080/filters:quality(75)/"

THUMBOR_URL_INTERNAL = "http://dca.arungas.com:6988/unsafe/fit-in/1520x2688/filters:quality(80)/"

SUBMIT_SMS_TEMPLATE_ID = "1107164508265878553"

SUBMIT_SMS_TEMPLATE = \
    "Dear {name}," \
    "Your application with Id {id} submitted for connection type  {application_details}. " \
    "We will get back to you within {working_days} working days."

VERIFIED_SMS_TEMPLATE = \
    ""

UJJWALA_PRE_INSPECTION_OTP = 'ujjwala_pre_inspection_otp'
