"""
Django settings for domestic_app project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/`
For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import json
import pickle
from pathlib import Path
import os # new
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
from corsheaders.defaults import default_headers, default_methods
from deathbycaptcha import deathbycaptcha
from django.core.cache import cache

BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '-kk-(hob87ggtv0cttw13mh_3m%^h7!9nhf$)=leaf&gzyv%+c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'material',
    'material.frontend',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'rest_framework',
    'corsheaders',
    'organizations',
    'communication_log',
    'django_rq',
    'django_fsm',
    'django_fsm_log',
    'fsm_admin2',
    'fsm_admin2_custom',
    'import_export',
    'django_filters',
    'advanced_filters',
    'scheduler',
    'connection_app.apps.ConnectionAppConfig',
    'inactive_customers',
    'treenode',
    'rangefilter',
    'django_admin_listfilter_dropdown',
    'teams',
    'formtools',
    'ujjwala.apps.UjjwalaAppConfig',
    'sdms',
    'otp',
    'app_utilities',
    'djgeojson',
    'leaflet',
    'reference_data.apps.ReferenceDataConfig',
    'retail_customers',
    # 'domestic.apps.DomesticConfig',
    'erp_invoice_management',
    'django_admin_json_editor',
    'service_request.apps.ServiceRequestAppConfig',
    'csc_services.apps.CSCServicesAppConfig',
    'django_comments_xtd',
    'django_comments',
    'django.contrib.sites',
    'taggit',
    'solo',
    'vicidial',
    'slick_reporting',
    'crispy_forms',
]

CRISPY_TEMPLATE_PACK = "bootstrap4"

SITE_ID = 2

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django_currentuser.middleware.ThreadLocalUserMiddleware',
    'django.contrib.sites.middleware.CurrentSiteMiddleware'
]

ROOT_URLCONF = 'domestic_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "domestic_app.context_processors.thumbor_compression_url",
            ],
        },
    },
]

WSGI_APPLICATION = 'domestic_app.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3'
    # }
    'default': {
        'ATOMIC_REQUESTS': True,
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'dca',
        'USER': 'dca_webapp',
        'PASSWORD': '3ty5JS8sJlqtk3bQ',
        # 'HOST': 'localhost',
        # 'HOST': '10.1.1.132',
        'HOST': '192.168.171.65',
        'PORT': '',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGIN_REDIRECT_URL = '/'

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'


USE_I18N = True

USE_L10N = True

USE_TZ = True


# CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_ALL_ORIGINS = True
CORS_ORIGIN_ALLOW_ALL = True


INTERAKT_API_KEY = "HmtU2CH6poGN_TU-XqCtwuvef8utPNRJRlamfbWXTwg"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/


ADMIN_COMMENTS_SHOW_EMPTY = False

COMMENTS_APP = 'django_comments_xtd'
# COMMENTS_XTD_MODEL = 'reference_data.models.CommentX'
# COMMENTS_XTD_FORM_CLASS = 'reference_data.forms.CommentXForm'

COMMENTS_XTD_CONFIRM_EMAIL = False

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'static_root')

STATICFILES_DIRS = [
        os.path.join(BASE_DIR, 'static'),
]

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

RQ_QUEUES = {
    'default': {
        'HOST': '192.168.171.65',
        'PORT': 56379,
        'DB': 0,
        # 'PASSWORD': 'some-password',
        'DEFAULT_TIMEOUT': 360,
        'ASYNC': True
    }
}

# If you need custom exception handlers

BASE_URL = 'https://dca.arungas.com'

# RQ_EXCEPTION_HANDLERS = ['path.to.my.handler']

MINIO_UPLOAD_URL = "http://files.dca.arungas.com"
MINIO_PUBLIC_URL = "https://files.dca.arungas.com"

# MINIO_ENDPOINT = "arungas.com:59000"
# MINIO_API_ENDPOINT = "arungas.com:59000"

MINIO_ENDPOINT = "arungas.com:59000"
MINIO_API_ENDPOINT = "arungas.com:59000"

MINIO_BUCKET_NAME = "domesticconnectionapplicationdocs"
MINIO_UJJWALA_BUCKET_NAME = "ujjwaladocuments"

MINIO_CREDENTIAL = {
    "access_key": "NS4WU7OHJ9I6TBJSMI0B",
    "secret_key": "JDiZVteYAB0sMD9QM5koKPXT8Xa8w+X2xukaM76O"
}


# Camunda DCA Production URL
# CAMUNDA_WEB_ROOT_URL = "https://camunda.dca.arungas.com"
# CAMUNDA_WEB_ROOT_URL = "https://camunda.dca.arungas.com"


# Camunda Development URL
CAMUNDA_WEB_ROOT_URL = "http://192.168.171.65:38080"

# Camunda Base URL
CAMUNDA_BASE_URL = f"{CAMUNDA_WEB_ROOT_URL}/engine-rest"

# Currently Pointing To Live Project of DCA Using Local Address
HTML_TO_PDF_SERVER_URL = "http://192.168.171.32:58080"

# Old Thumbor URL
# THUMBOR_URL = "http://dca.arungas.com:6988/unsafe/fit-in/1920x1080/filters:quality(75):format(jpeg)/"
# THUMBOR_URL_INTERNAL = "http://dca.arungas.com:6988/unsafe/fit-in/1520x2688/filters:format(webp)/"
# THUMBOR_URL_INTERNAL = "http://dca.arungas.com:6988/unsafe/fit-in/1520x2688/filters:quality(80)/"
# THUMBOR_URL_INTERNAL_WEBP_COMPRESSED = "http://dca.arungas.com:6988/unsafe/fit-in/1520x2688/filters:quality(80):format(webp)/"
# THUMBOR_URL_INTERNAL_WEBP_UNCOMPRESSED = "http://dca.arungas.com:6988/unsafe/fit-in/1520x2688/filters:quality(100):format(webp)/"

THUMBOR_WEB_URL = "http://thumbs.dca.arungas.com"
THUMBOR_URL = f"{THUMBOR_WEB_URL}/unsafe/fit-in/1920x1080/filters:quality(75):format(jpeg)/"

THUMBOR_LOCAL_URL = "http://192.168.171.32:6988"
THUMBOR_LOCAL_COMPRESSION_URL = f"{THUMBOR_LOCAL_URL}/unsafe/fit-in/1920x1080/filters:quality(75):format(jpeg)/"

THUMBOR_URL_INTERNAL = f"{THUMBOR_LOCAL_URL}/unsafe/fit-in/1520x2688/filters:format(webp)/"
THUMBOR_URL_INTERNAL_WEBP_COMPRESSED = f"{THUMBOR_WEB_URL}/unsafe/fit-in/1520x2688/filters:quality(80):format(webp)/"
THUMBOR_URL_LOCAL_INTERNAL_WEBP_COMPRESSED = f"{THUMBOR_LOCAL_URL}/unsafe/fit-in/1520x2688/filters:quality(80):format(webp)/"
THUMBOR_URL_INTERNAL_WEBP_UNCOMPRESSED = f"{THUMBOR_WEB_URL}/unsafe/fit-in/1520x2688/filters:quality(100):format(webp)/"

INFOBIP_URL = "https://4r198.api.infobip.com/sms/2/text/advanced"
INFOBIP_NOTIFY_URL = "https://dca.arungas.com/commlog/infobip/webhook/"

SUBMIT_SMS_TEMPLATE_ID = "1107164508265878553"

SUBMIT_SMS_TEMPLATE = \
    "Dear {name}," \
    "Your application with Id {id} submitted for connection type  {application_details}. " \
    "We will get back to you within {working_days} working days."

GENERIC_SMS_OTP_TEMPLATE = \
    "{otp} is your verification OTP. This OTP will expire in {otp_expire} mins. Do not share it with anyone   -Arun Gas"

# Old Template ID
# GENERIC_SMS_OTP_TEMPLATE_ID = "1107165976858894486"
GENERIC_SMS_OTP_TEMPLATE_ID = "1107169822213183469"

VERIFIED_SMS_TEMPLATE = \
    ""

UJJWALA_PRE_INSPECTION_OTP = 'ujjwala_pre_inspection_otp'

X_FRAME_OPTIONS = 'ALLOWALL'

# import sentry_sdk
#
# sentry_sdk.init(
#     dsn="https://3a6bc49af5e0461af09f8818d01e79b0@o4506076265906176.ingest.sentry.io/4506076268331008",
#     # Set traces_sample_rate to 1.0 to capture 100%
#     # of transactions for performance monitoring.
#     traces_sample_rate=1.0,
#     # Set profiles_sample_rate to 1.0 to profile 100%
#     # of sampled transactions.
#     # We recommend adjusting this value in production.
#     profiles_sample_rate=1.0,
# )


CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "unique-dedup_portal",
    }
}

PRE_SURAKSHA_YOUTUBE_VIDEO_URL = 'https://youtu.be/d-XiWg4277E'


def read_private_key_file(filepath):
    with open(filepath, 'r') as file:
        private_key = file.read()
    return private_key


# Define the path to your private key file
PRIVATE_KEY_PATH = os.path.join(BASE_DIR, 'private.pem')

# Read the private key
PRIVATE_KEY = read_private_key_file(PRIVATE_KEY_PATH)

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "./dialogflow_api.json"
os.environ["PRIVATE_KEY"] = PRIVATE_KEY
os.environ["PASSPHRASE"] = "jobnot"
os.environ["APP_SECRET"] = "10bee2967962c7fb6010d8b99764df45"

# cache.get_or_set("dedup_portal", pickled_dedeup_portal, 1000)
# dedup_portal = IoclOmcDedup('305948', 'Inder@1234')
