# Generated by Django 3.2.12 on 2025-04-22 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('event', models.CharField(max_length=48)),
                ('channel', models.CharField(max_length=25)),
                ('channel_subscriber', models.CharField(max_length=10)),
                ('status', models.CharField(default='Initial', max_length=25)),
                ('cron_processed', models.BooleanField(default=False)),
                ('message_id', models.CharField(max_length=64, null=True)),
                ('sent_on', models.DateTimeField(blank=True, null=True)),
                ('delivered_on', models.DateTimeField(blank=True, null=True)),
                ('read_on', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
