# Generated by Django 3.2.12 on 2022-02-16 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('communication_log', '0002_alter_communicationlog_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationlog',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
