# Generated by Django 3.2.12 on 2022-05-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication_log', '0003_alter_communicationlog_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationlog',
            name='channel_subscriber',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
