# Generated by Django 3.2.12 on 2022-07-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication_log', '0004_communicationlog_channel_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationlog',
            name='event',
            field=models.CharField(max_length=30),
        ),
    ]
