# Generated by Django 3.2.12 on 2022-08-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication_log', '0005_alter_communicationlog_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationlog',
            name='event',
            field=models.CharField(max_length=48),
        ),
    ]
