# Generated by Django 3.2.12 on 2023-10-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication_log', '0006_alter_communicationlog_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationlog',
            name='delivered_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='read_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='sent_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
