# Generated by Django 3.2.12 on 2022-04-08 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UjjwalaV2Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marital_status', models.CharField(choices=[('MARRIED', 'Married'), ('UNMARRIED', 'Unmarried'), ('DIVORCED', 'Divorced')], max_length=25)),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('contact_mobile', models.CharField(max_length=10)),
                ('uid_linked_mobile', models.CharField(max_length=10)),
                ('uid_mobile_status', models.CharField(choices=[('LINKED_WITH_SAME_MOBILE', 'Linked With Same Mobile'), ('LINKED_WITH_OTHER_MOBILE', 'Linked With Other Mobile'), ('MOBILE_NOT_AVAILABLE', 'Mobile Not Available')], max_length=25)),
                ('referral_code', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UjjwalaApplicationDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CUSTOMER_PHOTO', 'Customer Photo'), ('BANK_DETAIL', 'Bank Detail'), ('OTHER_ID_PROOF', 'Other Id Proof'), ('SV', 'Subscription Voucher'), ('CONNECTION_DETAIL', 'Connection Detail'), ('KITCHEN_PHOTO', 'Kitchen Photo')], max_length=25)),
                ('link', models.URLField()),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ujjwala.ujjwalav2application')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('relation', models.CharField(choices=[('SELF', 'Self'), ('FATHER', 'Father'), ('MOTHER', 'Mother'), ('HUSBAND', 'Husband'), ('SON', 'Son'), ('DAUGHTER', 'Daughter')], max_length=25)),
                ('dob', models.DateField()),
                ('uid', models.CharField(max_length=12)),
                ('uid_front_link', models.URLField()),
                ('uid_back_link', models.URLField()),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='ujjwala.ujjwalav2application')),
            ],
        ),
    ]
