# Generated by Django 3.2.12 on 2022-06-08 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import ujjwala.communication_models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0004_organizationinvitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(blank=True, max_length=32, null=True)),
                ('longitude', models.CharField(blank=True, max_length=32, null=True)),
                ('accuracy', models.CharField(blank=True, max_length=24, null=True)),
                ('witness_name', models.CharField(blank=True, max_length=256, null=True)),
                ('witness_mobile_number', models.CharField(blank=True, max_length=10, null=True)),
                ('status', django_fsm.FSMField(choices=[('ALLOCATED', 'Allocated'), ('OTP_VERIFIED', 'Otp Verified'), ('KITCHEN_PHOTO', 'Kitchen Photo'), ('SAFETY_AUDIO', 'Safety Audio'), ('PREVIEW_INSPECTION', 'Preview Inspection'), ('SUBMITTED', 'Submitted'), ('ACCEPTED', 'Accepted'), ('REUPLOAD', 'Reupload'), ('REJECTED', 'Rejected')], default='ALLOCATED', max_length=50)),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PROFILE_PHOTO', 'Profile Photo'), ('SIGNATURE', 'Signature')], max_length=25)),
                ('link', models.URLField()),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UjjwalaV2Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('sdms_last_updated_on', models.DateTimeField(null=True)),
                ('rejection_type', models.CharField(blank=True, choices=[('EKYC', 'Ekyc'), ('APPLICATION', 'Application'), ('CONNECTION', 'Connection')], max_length=25, null=True)),
                ('marital_status', models.CharField(choices=[('MARRIED', 'Married'), ('UNMARRIED', 'Unmarried'), ('DIVORCED', 'Divorced'), ('WIDOW', 'Widow')], max_length=25)),
                ('residential_status', models.CharField(blank=True, choices=[('LIVING_ALONE', 'Living Alone'), ('LIVING_WITH_FAMILY', 'Living With Family')], max_length=25, null=True)),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField(blank=True, null=True)),
                ('address_json', models.JSONField(blank=True, null=True)),
                ('contact_mobile', models.CharField(max_length=10)),
                ('consumer_id', models.CharField(blank=True, max_length=16, null=True)),
                ('uid_linked_mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('uid_mobile_status', models.CharField(blank=True, choices=[('LINKED_WITH_SAME_MOBILE', 'Linked With Same Mobile'), ('LINKED_WITH_OTHER_MOBILE', 'Linked With Other Mobile'), ('MOBILE_NOT_AVAILABLE', 'Mobile Not Available')], max_length=25, null=True)),
                ('application_id_kyc_no', models.CharField(blank=True, max_length=24, null=True)),
                ('referral_code', models.CharField(blank=True, max_length=64, null=True)),
                ('version', models.CharField(default='V1', max_length=2)),
                ('latitude', models.CharField(blank=True, max_length=32, null=True)),
                ('longitude', models.CharField(blank=True, max_length=32, null=True)),
                ('accuracy', models.CharField(blank=True, max_length=24, null=True)),
                ('product', models.CharField(blank=True, max_length=256, null=True)),
                ('witness_name', models.CharField(blank=True, max_length=256, null=True)),
                ('witness_mobile_number', models.CharField(blank=True, max_length=10, null=True)),
                ('robo_sdms_dedup', models.CharField(choices=[('NOT_PROCESSED', 'Not Processed'), ('PROCESSED_AND_UNIQUE', 'Processed and Unique'), ('PROCESSED_AND_DUPLICATE', 'Processed and Duplicate'), ('PROCESS_MANUAL', 'Process Manual')], default='NOT_PROCESSED', max_length=25)),
                ('status', django_fsm.FSMField(choices=[('DOCUMENTS_UPLOADED', 'Documents Uploaded'), ('DOCUMENTS_REUPLOAD', 'Documents Reupload'), ('EKYC_REJECTED', 'E-KYC Rejected'), ('EKYC_ACCEPTED', 'E-KYC Accepted'), ('LEGAL_DOCUMENTS_UPLOAD', 'Legal Documents Upload'), ('MANUAL_LEGAL_DOCUMENTS_UPLOAD', 'Manual Legal Documents Upload'), ('LEGAL_DOCUMENTS_COLLECTED', 'Legal Documents Collected'), ('EDIT_APPLICATION', 'Edit Application'), ('APPLICATION_REJECTED', 'Application Rejected'), ('OMC_CLEARED', 'OMC Cleared'), ('OMC_REJECTED', 'OMC Rejected'), ('NIC_ERROR', 'NIC Error'), ('NIC_CLEARED', 'NIC Cleared'), ('INSUFFICIENT_ADDRESS', 'Insufficient Address'), ('DO_MANUAL_OPERATION', 'Do Manual Operation'), ('PRE_INSPECTION_SUBMITTED', 'Pre Inspection Submitted'), ('PRE_INSPECTION_REUPLOAD', 'Pre Inspection Reupload'), ('PRE_INSPECTION_ACCEPTED', 'Pre Inspection Accepted'), ('CONNECTION_RELEASED', 'Connection Released'), ('POST_INSTALLATION_UPLOAD', 'Post Installation Upload'), ('COMPLETED', 'Completed')], default='DOCUMENTS_UPLOADED', max_length=50)),
                ('manual_operation_code', models.CharField(blank=True, max_length=25, null=True)),
                ('legal_documents_upload_status', models.CharField(blank=True, max_length=25, null=True)),
                ('sv', models.CharField(blank=True, max_length=25, null=True)),
                ('documents_required_for_reupload', models.JSONField(blank=True, null=True)),
                ('last_execution_state', models.CharField(blank=True, max_length=50, null=True)),
                ('pre_inspection_done_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pre_inspection_done_by', to=settings.AUTH_USER_MODEL)),
                ('service_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.servicelocations')),
                ('service_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'permissions': (('can_edit_record_transition', 'Can edit record transition'), ('can_do_ekyc', 'Can do ekyc'), ('can_upload_legal_docs', 'Can upload legal docs'), ('can_approve_connection', 'Can approve connection'), ('can_reject_connection', 'Can reject connection'), ('can_collect_legal_documents', 'Can collect legal documents'), ('can_release_connection', 'Can release connection'), ('can_upload_post_installation', 'Can upload post installation'), ('can_reject_application', 'Can reject application')),
            },
            bases=(models.Model, ujjwala.communication_models.UjjwalaWhatsappCommunication),
        ),
        migrations.CreateModel(
            name='UjjwalaApplicationDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CUSTOMER_PHOTO', 'Customer Photo'), ('BANK_DETAIL', 'Bank Detail'), ('OTHER_ID_PROOF', 'Other Id Proof'), ('SV', 'Subscription Voucher'), ('CONNECTION_DETAIL', 'Connection Detail'), ('KITCHEN_PHOTO', 'Kitchen Photo'), ('CUSTOMER_IN_KITCHEN', 'Customer In Kitchen'), ('MAIN_GATE', 'Main Gate'), ('WITNESS_PHOTO', 'Witness Photo'), ('MECHANIC_PHOTO', 'Mechanic Photo'), ('CUSTOMER_SIGNATURE', 'Customer Signature'), ('WITNESS_SIGNATURE', 'Witness Signature'), ('DEATH_CERTIFICATE', 'Death Certificate'), ('DIVORCE_DOCUMENT', 'Divorce Document'), ('SAFETY_AUDIO', 'Safety Audio')], max_length=25)),
                ('link', models.URLField()),
                ('compressed', models.BooleanField(default=False)),
                ('file_size', models.CharField(default='0', max_length=16)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ujjwala.ujjwalav2application')),
            ],
        ),
        migrations.CreateModel(
            name='PreInspectionDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CUSTOMER_PHOTO', 'Customer Photo'), ('BANK_DETAIL', 'Bank Detail'), ('OTHER_ID_PROOF', 'Other Id Proof'), ('SV', 'Subscription Voucher'), ('CONNECTION_DETAIL', 'Connection Detail'), ('KITCHEN_PHOTO', 'Kitchen Photo'), ('CUSTOMER_IN_KITCHEN', 'Customer In Kitchen'), ('MAIN_GATE', 'Main Gate'), ('WITNESS_PHOTO', 'Witness Photo'), ('MECHANIC_PHOTO', 'Mechanic Photo'), ('CUSTOMER_SIGNATURE', 'Customer Signature'), ('WITNESS_SIGNATURE', 'Witness Signature'), ('DEATH_CERTIFICATE', 'Death Certificate'), ('DIVORCE_DOCUMENT', 'Divorce Document'), ('SAFETY_AUDIO', 'Safety Audio')], max_length=25)),
                ('link', models.URLField()),
                ('compressed', models.BooleanField(default=False)),
                ('file_size', models.CharField(default='0', max_length=16)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ujjwala.preinspection')),
            ],
        ),
        migrations.AddField(
            model_name='preinspection',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pre_inspection', to='ujjwala.ujjwalav2application'),
        ),
        migrations.CreateModel(
            name='FamilyMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('relation', models.CharField(choices=[('SELF', 'Self'), ('FATHER', 'Father'), ('MOTHER', 'Mother'), ('HUSBAND', 'Husband'), ('SON', 'Son'), ('DAUGHTER', 'Daughter')], max_length=25)),
                ('dob', models.DateField()),
                ('uid_no', models.CharField(blank=True, max_length=12, null=True)),
                ('uid_front_link', models.URLField()),
                ('uid_back_link', models.URLField()),
                ('uid_check_result', models.JSONField(blank=True, null=True)),
                ('uid_front_compressed', models.BooleanField(default=False)),
                ('uid_back_compressed', models.BooleanField(default=False)),
                ('uid_front_file_size', models.CharField(default='0', max_length=16)),
                ('uid_back_file_size', models.CharField(default='0', max_length=16)),
                ('additional_details', models.JSONField(blank=True, null=True)),
                ('is_valid_uid', models.BooleanField(blank=True, null=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='ujjwala.ujjwalav2application')),
            ],
        ),
        migrations.CreateModel(
            name='Evykati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.JSONField(blank=True, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evyakti', to='ujjwala.ujjwalav2application')),
            ],
        ),
    ]
