# Generated by Django 3.2.12 on 2022-04-08 11:44

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('ujjwala', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ujjwalav2application',
            name='status',
            field=django_fsm.FSMField(choices=[('EDIT_APPLICATION', 'Edit Application'), ('SUBMITTED', 'Submitted'), ('NOT_INTERESTED', 'Not Interested'), ('BACK_OFFICE_START', 'Back Office Start'), ('BACK_OFFICE_END', 'Back Office End'), ('FRONT_OFFICE', 'Front Office'), ('COMPLETED', 'Completed'), ('REUPLOAD', 'Reupload'), ('KITCHEN_PHOTO_UPLOAD', 'Kitchen Photo Upload')], default='SUBMITTED', max_length=50),
        ),
    ]
