# Generated by Django 3.2.12 on 2022-06-08 10:39

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('ujjwala', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionDisbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', django_fsm.FSMField(choices=[('INVITED', 'Invited')], default='INVITED', max_length=50)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='connection_disbursement', to='ujjwala.ujjwalav2application')),
            ],
        ),
        migrations.CreateModel(
            name='ConnectionDisbursementDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CUSTOMER_PHOTO', 'Customer Photo'), ('BANK_DETAIL', 'Bank Detail'), ('OTHER_ID_PROOF', 'Other Id Proof'), ('SV', 'Subscription Voucher'), ('CONNECTION_DETAIL', 'Connection Detail'), ('KITCHEN_PHOTO', 'Kitchen Photo'), ('CUSTOMER_IN_KITCHEN', 'Customer In Kitchen'), ('MAIN_GATE', 'Main Gate'), ('WITNESS_PHOTO', 'Witness Photo'), ('MECHANIC_PHOTO', 'Mechanic Photo'), ('CUSTOMER_SIGNATURE', 'Customer Signature'), ('WITNESS_SIGNATURE', 'Witness Signature'), ('DEATH_CERTIFICATE', 'Death Certificate'), ('DIVORCE_DOCUMENT', 'Divorce Document'), ('SAFETY_AUDIO', 'Safety Audio')], max_length=25)),
                ('link', models.URLField()),
                ('compressed', models.BooleanField(default=False)),
                ('file_size', models.CharField(default='0', max_length=16)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ujjwala.connectiondisbursement')),
            ],
        ),
    ]
