# Generated by Django 3.2.12 on 2022-06-08 11:45

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('ujjwala', '0002_connectiondisbursement_connectiondisbursementdocuments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectiondisbursement',
            name='status',
            field=django_fsm.FSMField(choices=[('LEGAL_DOCUMENTS_UPLOAD', 'Legal Documents Upload'), ('LEGAL_DOCUMENTS_REVIEW', 'Legal Documents Review'), ('LEGAL_DOCUMENTS_ACCEPTED', 'Legal Documents Accepted'), ('LEGAL_DOCUMENTS_REUPLOAD', 'Legal Documents Reupload'), ('INVITED', 'Invited'), ('SV_LABEL_PRINT', 'SV Label Print'), ('DISBURSEMENT_PHOTO_UPLOAD', 'Disbursement Photo Upload'), ('SOCIAL_MEDIA_UPDATES', 'Social Media Updates'), ('MATERIAL_DELIVERED', 'Material Delivered')], default='LEGAL_DOCUMENTS_UPLOAD', max_length=50),
        ),
    ]
