# Generated by Django 3.2.12 on 2022-04-08 12:51

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('ujjwala', '0002_ujjwalav2application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ujjwalav2application',
            name='installation_status',
            field=django_fsm.FSMField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('ACCEPTED', 'Accepted'), ('REUPLOAD', 'Reupload')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='ujjwalav2application',
            name='status',
            field=django_fsm.FSMField(choices=[('DOCUMENTS_UPLOADED', 'Documents Uploaded'), ('DOCUMENTS_REUPLOAD', 'Documents Reupload'), ('EKYC_INITIATED', 'E-KYC Initiated'), ('EKYC_REJECTED', 'E-KYC Rejected'), ('EKYC_ACCEPTED', 'E-KYC Accepted'), ('CONNECTION_REJECTED', 'Connection Rejected'), ('NEW_CONNECTION_ACCEPTED', 'New Connection Accepted'), ('LEGAL_DOCUMENTS_COLLECTED', 'Legal Documents Collected'), ('SV_RELEASED', 'SV Released'), ('COMPLETED', 'Completed')], default='DOCUMENTS_UPLOADED', max_length=50),
        ),
    ]
