# Generated by Django 3.2.12 on 2022-06-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujjwala', '0003_alter_connectiondisbursement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='preinspection',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='preinspection',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
