# Generated by Django 3.2.12 on 2022-04-12 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ujjwala', '0003_auto_20220408_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymembers',
            name='uid',
        ),
    ]
