# Generated by Django 3.2.12 on 2022-04-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujjwala', '0004_remove_familymembers_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ujjwalav2application',
            name='sv',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
