# Generated by Django 3.2.12 on 2022-06-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujjwala', '0004_auto_20220608_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='preinspection',
            name='submitted_on',
            field=models.DateTimeField(null=True),
        ),
    ]
