# Generated by Django 3.2.12 on 2022-04-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujjwala', '0005_ujjwalav2application_sv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ujjwalav2application',
            name='marital_status',
            field=models.CharField(choices=[('MARRIED', 'Married'), ('UNMARRIED', 'Unmarried'), ('DIVORCED', 'Divorced'), ('WIDOW', 'Widow')], max_length=25),
        ),
    ]
