# Generated by Django 3.2.12 on 2022-06-09 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ujjwala', '0005_preinspection_submitted_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ujjwalav2application',
            name='pre_inspection_done_by',
        ),
        migrations.RemoveField(
            model_name='ujjwalav2application',
            name='witness_mobile_number',
        ),
        migrations.RemoveField(
            model_name='ujjwalav2application',
            name='witness_name',
        ),
        migrations.AddField(
            model_name='ujjwalav2application',
            name='pre_inspection_accepted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ujjwala.preinspection'),
        ),
    ]
