# Generated by Django 3.2.12 on 2022-04-16 14:08

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('ujjwala', '0006_alter_ujjwalav2application_marital_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ujjwalav2application',
            name='last_execution_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ujjwalav2application',
            name='status',
            field=django_fsm.FSMField(choices=[('DOCUMENTS_UPLOADED', 'Documents Uploaded'), ('DOCUMENTS_REUPLOAD', 'Documents Reupload'), ('EKYC_INITIATED', 'E-KYC Initiated'), ('EKYC_REJECTED', 'E-KYC Rejected'), ('EKYC_ACCEPTED', 'E-KYC Accepted'), ('CONNECTION_REJECTED', 'Connection Rejected'), ('NEW_CONNECTION_ACCEPTED', 'New Connection Accepted'), ('LEGAL_DOCUMENTS_COLLECTED', 'Legal Documents Collected'), ('SV_RELEASED', 'SV Released'), ('COMPLETED', 'Completed'), ('EDIT_APPLICATION', 'Edit Application')], default='DOCUMENTS_UPLOADED', max_length=50),
        ),
    ]
