# Generated by Django 3.2.12 on 2022-06-09 11:41

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('ujjwala', '0006_auto_20220609_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectiondisbursement',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='connectiondisbursement',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='connectiondisbursement',
            name='status',
            field=django_fsm.FSMField(choices=[('LEGAL_DOCUMENTS_PENDING', 'Legal Documents Pending'), ('LEGAL_DOCUMENTS_REVIEW', 'Legal Documents Review'), ('LEGAL_DOCUMENTS_ACCEPTED', 'Legal Documents Accepted'), ('LEGAL_DOCUMENTS_REUPLOAD', 'Legal Documents Reupload'), ('INVITED', 'Invited'), ('SV_LABEL_PRINT', 'SV Label Print'), ('DISBURSEMENT_PHOTO_UPLOAD', 'Disbursement Photo Upload'), ('SOCIAL_MEDIA_UPDATES', 'Social Media Updates'), ('MATERIAL_DELIVERED', 'Material Delivered')], default='LEGAL_DOCUMENTS_PENDING', max_length=50),
        ),
    ]
