# Generated by Django 3.2.12 on 2022-04-16 14:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ujjwala', '0007_auto_20220416_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='ujjwalav2application',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ujjwalav2application',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
