# Generated by Django 3.2.12 on 2022-06-10 06:54

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('ujjwala', '0007_auto_20220609_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='ujjwalav2application',
            name='connection_disbursement_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ujjwala.connectiondisbursement'),
        ),
        migrations.AlterField(
            model_name='ujjwalav2application',
            name='status',
            field=django_fsm.FSMField(choices=[('DOCUMENTS_UPLOADED', 'Documents Uploaded'), ('DOCUMENTS_REUPLOAD', 'Documents Reupload'), ('EKYC_REJECTED', 'E-KYC Rejected'), ('EKYC_ACCEPTED', 'E-KYC Accepted'), ('LEGAL_DOCUMENTS_UPLOAD', 'Legal Documents Upload'), ('MANUAL_LEGAL_DOCUMENTS_UPLOAD', 'Manual Legal Documents Upload'), ('LEGAL_DOCUMENTS_COLLECTED', 'Legal Documents Collected'), ('EDIT_APPLICATION', 'Edit Application'), ('APPLICATION_REJECTED', 'Application Rejected'), ('OMC_CLEARED', 'OMC Cleared'), ('OMC_REJECTED', 'OMC Rejected'), ('NIC_ERROR', 'NIC Error'), ('NIC_CLEARED', 'NIC Cleared'), ('INSUFFICIENT_ADDRESS', 'Insufficient Address'), ('DO_MANUAL_OPERATION', 'Do Manual Operation'), ('PRE_INSPECTION_ACCEPTED', 'Pre Inspection Accepted'), ('CONNECTION_RELEASED', 'Connection Released'), ('POST_INSTALLATION_UPLOAD', 'Post Installation Upload'), ('COMPLETED', 'Completed')], default='DOCUMENTS_UPLOADED', max_length=50),
        ),
    ]
