# Generated by Django 3.2.12 on 2022-04-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujjwala', '0008_auto_20220416_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='ujjwalav2application',
            name='residential_status',
            field=models.CharField(choices=[('SINGLE', 'Single'), ('LIVING_WITH_FAMILY', 'Living With Family')], default=1, max_length=25),
            preserve_default=False,
        ),
    ]
