# Generated by Django 3.2.12 on 2022-06-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujjwala', '0008_auto_20220610_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectiondisbursementdocuments',
            name='type',
            field=models.CharField(choices=[('CUSTOMER_PHOTO', 'Customer Photo'), ('BANK_DETAIL', 'Bank Detail'), ('OTHER_ID_PROOF', 'Other Id Proof'), ('SV', 'Subscription Voucher'), ('CONNECTION_DETAIL', 'Connection Detail'), ('KITCHEN_PHOTO', 'Kitchen Photo'), ('CUSTOMER_IN_KITCHEN', 'Customer In Kitchen'), ('MAIN_GATE', 'Main Gate'), ('WITNESS_PHOTO', 'Witness Photo'), ('MECHANIC_PHOTO', 'Mechanic Photo'), ('CUSTOMER_SIGNATURE', 'Customer Signature'), ('WITNESS_SIGNATURE', 'Witness Signature'), ('DEATH_CERTIFICATE', 'Death Certificate'), ('DIVORCE_DOCUMENT', 'Divorce Document'), ('SAFETY_AUDIO', 'Safety Audio'), ('LEGAL_DOC_ANNEXURE_14_POINTS', 'Legal Doc Annexure 14 Points'), ('LEGAL_DOC_FAMILY_OCCUPANCY', 'Legal Doc Family Occupancy'), ('LEGAL_DOC_PRE_INSPECTION', 'Legal Doc Pre Inspection')], max_length=32),
        ),
        migrations.AlterField(
            model_name='preinspectiondocuments',
            name='type',
            field=models.CharField(choices=[('CUSTOMER_PHOTO', 'Customer Photo'), ('BANK_DETAIL', 'Bank Detail'), ('OTHER_ID_PROOF', 'Other Id Proof'), ('SV', 'Subscription Voucher'), ('CONNECTION_DETAIL', 'Connection Detail'), ('KITCHEN_PHOTO', 'Kitchen Photo'), ('CUSTOMER_IN_KITCHEN', 'Customer In Kitchen'), ('MAIN_GATE', 'Main Gate'), ('WITNESS_PHOTO', 'Witness Photo'), ('MECHANIC_PHOTO', 'Mechanic Photo'), ('CUSTOMER_SIGNATURE', 'Customer Signature'), ('WITNESS_SIGNATURE', 'Witness Signature'), ('DEATH_CERTIFICATE', 'Death Certificate'), ('DIVORCE_DOCUMENT', 'Divorce Document'), ('SAFETY_AUDIO', 'Safety Audio'), ('LEGAL_DOC_ANNEXURE_14_POINTS', 'Legal Doc Annexure 14 Points'), ('LEGAL_DOC_FAMILY_OCCUPANCY', 'Legal Doc Family Occupancy'), ('LEGAL_DOC_PRE_INSPECTION', 'Legal Doc Pre Inspection')], max_length=32),
        ),
        migrations.AlterField(
            model_name='ujjwalaapplicationdocuments',
            name='type',
            field=models.CharField(choices=[('CUSTOMER_PHOTO', 'Customer Photo'), ('BANK_DETAIL', 'Bank Detail'), ('OTHER_ID_PROOF', 'Other Id Proof'), ('SV', 'Subscription Voucher'), ('CONNECTION_DETAIL', 'Connection Detail'), ('KITCHEN_PHOTO', 'Kitchen Photo'), ('CUSTOMER_IN_KITCHEN', 'Customer In Kitchen'), ('MAIN_GATE', 'Main Gate'), ('WITNESS_PHOTO', 'Witness Photo'), ('MECHANIC_PHOTO', 'Mechanic Photo'), ('CUSTOMER_SIGNATURE', 'Customer Signature'), ('WITNESS_SIGNATURE', 'Witness Signature'), ('DEATH_CERTIFICATE', 'Death Certificate'), ('DIVORCE_DOCUMENT', 'Divorce Document'), ('SAFETY_AUDIO', 'Safety Audio'), ('LEGAL_DOC_ANNEXURE_14_POINTS', 'Legal Doc Annexure 14 Points'), ('LEGAL_DOC_FAMILY_OCCUPANCY', 'Legal Doc Family Occupancy'), ('LEGAL_DOC_PRE_INSPECTION', 'Legal Doc Pre Inspection')], max_length=32),
        ),
        migrations.AlterField(
            model_name='userdocuments',
            name='type',
            field=models.CharField(choices=[('PROFILE_PHOTO', 'Profile Photo'), ('SIGNATURE', 'Signature')], max_length=32),
        ),
    ]
