# Generated by Django 3.2.12 on 2022-04-18 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ujjwala', '0009_ujjwalav2application_residential_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ujjwalav2application',
            name='uid_linked_mobile',
        ),
        migrations.RemoveField(
            model_name='ujjwalav2application',
            name='uid_mobile_status',
        ),
    ]
