# Generated by Django 3.2.12 on 2022-04-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujjwala', '0010_auto_20220418_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='ujjwalav2application',
            name='uid_linked_mobile',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ujjwalav2application',
            name='uid_mobile_status',
            field=models.CharField(choices=[('LINKED_WITH_SAME_MOBILE', 'Linked With Same Mobile'), ('LINKED_WITH_OTHER_MOBILE', 'Linked With Other Mobile'), ('MOBILE_NOT_AVAILABLE', 'Mobile Not Available')], default=1, max_length=25),
            preserve_default=False,
        ),
    ]
