# Generated by Django 3.2.12 on 2022-04-18 12:00

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('ujjwala', '0011_auto_20220418_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ujjwalav2application',
            name='installation_status',
        ),
        migrations.AddField(
            model_name='ujjwalav2application',
            name='pre_inspection_status',
            field=django_fsm.FSMField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('ACCEPTED', 'Accepted'), ('REUPLOAD', 'Reupload')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='ujjwalav2application',
            name='status',
            field=django_fsm.FSMField(choices=[('DOCUMENTS_UPLOADED', 'Documents Uploaded'), ('DOCUMENTS_REUPLOAD', 'Documents Reupload'), ('EKYC_INITIATED', 'E-KYC Initiated'), ('EKYC_REJECTED', 'E-KYC Rejected'), ('EKYC_ACCEPTED', 'E-KYC Accepted'), ('LEGAL_DOCUMENTS_UPLOAD', 'Legal Documents Upload'), ('CONNECTION_APPROVED', 'Connection Approved'), ('CONNECTION_REJECTED', 'Connection Rejected'), ('LEGAL_DOCUMENTS_COLLECTED', 'Legal Documents Collected'), ('CONNECTION_RELEASED', 'Connection Released'), ('POST_INSTALLATION_UPLOAD', 'Post Installation Upload'), ('COMPLETED', 'Completed'), ('EDIT_APPLICATION', 'Edit Application')], default='DOCUMENTS_UPLOADED', max_length=50),
        ),
    ]
