# Generated by Django 3.2.12 on 2022-04-18 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('organizations', '0004_organizationinvitation'),
        ('ujjwala', '0012_auto_20220418_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='ujjwalav2application',
            name='service_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.servicelocations'),
        ),
        migrations.AddField(
            model_name='ujjwalav2application',
            name='service_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
    ]
