# Generated by Django 3.2.12 on 2022-04-19 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organizationinvitation'),
        ('teams', '0001_initial'),
        ('ujjwala', '0013_auto_20220418_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymembers',
            name='uid_no',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ujjwalaapplicationdocuments',
            name='type',
            field=models.CharField(choices=[('CUSTOMER_PHOTO', 'Customer Photo'), ('BANK_DETAIL', 'Bank Detail'), ('OTHER_ID_PROOF', 'Other Id Proof'), ('SV', 'Subscription Voucher'), ('CONNECTION_DETAIL', 'Connection Detail'), ('KITCHEN_PHOTO', 'Kitchen Photo'), ('CUSTOMER_SIGNATURE', 'Customer Signature')], max_length=25),
        ),
        migrations.AlterField(
            model_name='ujjwalav2application',
            name='residential_status',
            field=models.CharField(choices=[('LIVING_ALONE', 'Living Alone'), ('LIVING_WITH_FAMILY', 'Living With Family')], max_length=25),
        ),
        migrations.AlterField(
            model_name='ujjwalav2application',
            name='service_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.servicelocations'),
        ),
        migrations.AlterField(
            model_name='ujjwalav2application',
            name='service_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
    ]
