# Generated by Django 3.2.12 on 2022-04-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujjwala', '0014_auto_20220419_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='ujjwalav2application',
            name='version',
            field=models.CharField(default='V1', max_length=2),
        ),
        migrations.AlterField(
            model_name='familymembers',
            name='uid_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
