# Generated by Django 3.2.12 on 2022-04-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujjwala', '0015_auto_20220419_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ujjwalav2application',
            name='uid_linked_mobile',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
