# Generated by Django 3.2.12 on 2022-04-25 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ujjwala', '0017_auto_20220420_0845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ujjwalav2application',
            options={'permissions': (('can_do_ekyc', 'Can Do Ekyc'), ('can_reject_ekyc', 'Can reject Ekyc'), ('can_accept_ekyc', 'Can accept Ekyc'), ('can_upload_legal_docs', 'Can upload legal docs'), ('can_approve_connection', 'Can approve connection'), ('can_reject_connection', 'Can reject connection'), ('can_collect_legal_documents', 'Can collect legal documents'), ('can_release_connection', 'Can release connection'), ('can_upload_post_installation', 'Can upload post installation'))},
        ),
    ]
