# Generated by Django 3.2.12 on 2022-04-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujjwala', '0020_alter_ujjwalav2application_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ujjwalav2application',
            name='address_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
