# Generated by Django 3.2.12 on 2022-04-26 11:35

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('ujjwala', '0021_ujjwalav2application_address_json'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ujjwalav2application',
            options={'permissions': (('can_edit_record_transition', 'Can edit record transition'), ('can_do_ekyc', 'Can do ekyc'), ('can_upload_legal_docs', 'Can upload legal docs'), ('can_approve_connection', 'Can approve connection'), ('can_reject_connection', 'Can reject connection'), ('can_collect_legal_documents', 'Can collect legal documents'), ('can_release_connection', 'Can release connection'), ('can_upload_post_installation', 'Can upload post installation'), ('can_reject_application', 'Can reject application'))},
        ),
        migrations.AddField(
            model_name='ujjwalav2application',
            name='rejection_type',
            field=models.CharField(choices=[('EKYC', 'Ekyc'), ('APPLICATION', 'Application'), ('CONNECTION', 'Connection')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='ujjwalav2application',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ujjwalav2application',
            name='status',
            field=django_fsm.FSMField(choices=[('DOCUMENTS_UPLOADED', 'Documents Uploaded'), ('DOCUMENTS_REUPLOAD', 'Documents Reupload'), ('EKYC_INITIATED', 'E-KYC Initiated'), ('EKYC_REJECTED', 'E-KYC Rejected'), ('EKYC_ACCEPTED', 'E-KYC Accepted'), ('LEGAL_DOCUMENTS_UPLOAD', 'Legal Documents Upload'), ('CONNECTION_APPROVED', 'Connection Approved'), ('CONNECTION_REJECTED', 'Connection Rejected'), ('LEGAL_DOCUMENTS_COLLECTED', 'Legal Documents Collected'), ('CONNECTION_RELEASED', 'Connection Released'), ('POST_INSTALLATION_UPLOAD', 'Post Installation Upload'), ('COMPLETED', 'Completed'), ('EDIT_APPLICATION', 'Edit Application'), ('APPLICATION_REJECTED', 'Application Rejected')], default='DOCUMENTS_UPLOADED', max_length=50),
        ),
    ]
