# Generated by Django 3.2.12 on 2022-04-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujjwala', '0023_alter_ujjwalav2application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymembers',
            name='uid_check_result',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ujjwalav2application',
            name='sdms_dedup',
            field=models.BooleanField(default=False),
        ),
    ]
