# Generated by Django 3.2.12 on 2022-04-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujjwala', '0024_auto_20220427_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ujjwalav2application',
            name='sdms_dedup',
        ),
        migrations.AddField(
            model_name='ujjwalav2application',
            name='robo_sdms_dedup',
            field=models.CharField(choices=[('NOT_PROCESSED', 'Not Processed'), ('PROCESSED_AND_UNIQUE', 'Processed and Unique'), ('PROCESSED_AND_DUPLICATE', 'Processed and Duplicate')], default='NOT_PROCESSED', max_length=25),
        ),
    ]
