# Generated by Django 3.2.12 on 2022-04-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujjwala', '0025_auto_20220427_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymembers',
            name='uid_back_compressed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='familymembers',
            name='uid_back_file_size',
            field=models.CharField(default='0', max_length=16),
        ),
        migrations.AddField(
            model_name='familymembers',
            name='uid_front_compressed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='familymembers',
            name='uid_front_file_size',
            field=models.CharField(default='0', max_length=16),
        ),
        migrations.AddField(
            model_name='ujjwalaapplicationdocuments',
            name='compressed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ujjwalaapplicationdocuments',
            name='file_size',
            field=models.CharField(default='0', max_length=16),
        ),
        migrations.AlterField(
            model_name='ujjwalav2application',
            name='robo_sdms_dedup',
            field=models.CharField(choices=[('NOT_PROCESSED', 'Not Processed'), ('PROCESSED_AND_UNIQUE', 'Processed and Unique'), ('PROCESSED_AND_DUPLICATE', 'Processed and Duplicate'), ('PROCESS_MANUAL', 'Process Manual')], default='NOT_PROCESSED', max_length=25),
        ),
    ]
