# Generated by Django 3.2.12 on 2022-05-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujjwala', '0026_auto_20220428_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='ujjwalav2application',
            name='legal_documents_upload_status',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
