# Generated by Django 3.2.12 on 2022-05-04 06:32

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('ujjwala', '0027_ujjwalav2application_legal_documents_upload_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ujjwalav2application',
            name='manual_operation_code',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='ujjwalav2application',
            name='status',
            field=django_fsm.FSMField(choices=[('DOCUMENTS_UPLOADED', 'Documents Uploaded'), ('DOCUMENTS_REUPLOAD', 'Documents Reupload'), ('EKYC_REJECTED', 'E-KYC Rejected'), ('EKYC_ACCEPTED', 'E-KYC Accepted'), ('LEGAL_DOCUMENTS_UPLOAD', 'Legal Documents Upload'), ('MANUAL_LEGAL_DOCUMENTS_UPLOAD', 'Manual Legal Documents Upload'), ('CONNECTION_APPROVED', 'Connection Approved'), ('CONNECTION_REJECTED', 'Connection Rejected'), ('LEGAL_DOCUMENTS_COLLECTED', 'Legal Documents Collected'), ('CONNECTION_RELEASED', 'Connection Released'), ('POST_INSTALLATION_UPLOAD', 'Post Installation Upload'), ('COMPLETED', 'Completed'), ('EDIT_APPLICATION', 'Edit Application'), ('APPLICATION_REJECTED', 'Application Rejected'), ('OMC CLEARED', 'OMC Cleared'), ('NIC_DEDUP_PENDING', 'NIC Dedup Pending'), ('NIC_CLEARED', 'NIC Cleared'), ('INSUFFICIENT_ADDRESS', 'Insufficient Address')], default='DOCUMENTS_UPLOADED', max_length=50),
        ),
    ]
