# Generated by Django 3.2.12 on 2022-05-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujjwala', '0028_auto_20220504_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ujjwalav2application',
            name='rejection_type',
            field=models.CharField(blank=True, choices=[('EKYC', 'Ekyc'), ('APPLICATION', 'Application'), ('CONNECTION', 'Connection')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='ujjwalav2application',
            name='residential_status',
            field=models.CharField(blank=True, choices=[('LIVING_ALONE', 'Living Alone'), ('LIVING_WITH_FAMILY', 'Living With Family')], max_length=25, null=True),
        ),
    ]
