# Generated by Django 3.2.12 on 2022-05-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujjwala', '0030_alter_ujjwalav2application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ujjwalav2application',
            name='application_id_kyc_no',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
