# Generated by Django 3.2.12 on 2022-05-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujjwala', '0032_auto_20220510_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='ujjwalav2application',
            name='sdms_last_updated_on',
            field=models.DateTimeField(null=True),
        ),
    ]
