# Generated by Django 3.2.12 on 2022-05-13 07:53

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('ujjwala', '0033_ujjwalav2application_sdms_last_updated_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ujjwalav2application',
            name='pre_inspection_status',
        ),
        migrations.AddField(
            model_name='ujjwalav2application',
            name='accuracy',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='ujjwalav2application',
            name='product',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='ujjwalav2application',
            name='status',
            field=django_fsm.FSMField(choices=[('DOCUMENTS_UPLOADED', 'Documents Uploaded'), ('DOCUMENTS_REUPLOAD', 'Documents Reupload'), ('EKYC_REJECTED', 'E-KYC Rejected'), ('EKYC_ACCEPTED', 'E-KYC Accepted'), ('LEGAL_DOCUMENTS_UPLOAD', 'Legal Documents Upload'), ('MANUAL_LEGAL_DOCUMENTS_UPLOAD', 'Manual Legal Documents Upload'), ('CONNECTION_APPROVED', 'Connection Approved'), ('CONNECTION_REJECTED', 'Connection Rejected'), ('LEGAL_DOCUMENTS_COLLECTED', 'Legal Documents Collected'), ('CONNECTION_RELEASED', 'Connection Released'), ('POST_INSTALLATION_UPLOAD', 'Post Installation Upload'), ('COMPLETED', 'Completed'), ('EDIT_APPLICATION', 'Edit Application'), ('APPLICATION_REJECTED', 'Application Rejected'), ('OMC_CLEARED', 'OMC Cleared'), ('OMC_REJECTED', 'OMC Rejected'), ('NIC_ERROR', 'NIC Error'), ('NIC_CLEARED', 'NIC Cleared'), ('INSUFFICIENT_ADDRESS', 'Insufficient Address'), ('DO_MANUAL_OPERATION', 'Do Manual Operation'), ('PRE_INSPECTION_SUBMITTED', 'Pre Inspection Submitted'), ('PRE_INSPECTION_ACCEPTED', 'Pre Inspection Accepted'), ('PRE_INSPECTION_REJECTED', 'Pre Inspection Rejected')], default='DOCUMENTS_UPLOADED', max_length=50),
        ),
    ]
