# Generated by Django 3.2.12 on 2022-05-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujjwala', '0034_auto_20220513_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ujjwalaapplicationdocuments',
            name='type',
            field=models.CharField(choices=[('CUSTOMER_PHOTO', 'Customer Photo'), ('BANK_DETAIL', 'Bank Detail'), ('OTHER_ID_PROOF', 'Other Id Proof'), ('SV', 'Subscription Voucher'), ('CONNECTION_DETAIL', 'Connection Detail'), ('KITCHEN_PHOTO', 'Kitchen Photo'), ('MAIN_GATE', 'Main Gate'), ('CUSTOMER_SIGNATURE', 'Customer Signature'), ('DEATH_CERTIFICATE', 'Death Certificate'), ('DIVORCE_DOCUMENT', 'Divorce Document')], max_length=25),
        ),
    ]
