# Generated by Django 3.2.12 on 2022-05-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujjwala', '0035_alter_ujjwalaapplicationdocuments_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ujjwalav2application',
            name='referral_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
