# Generated by Django 3.2.12 on 2022-05-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujjwala', '0036_alter_ujjwalav2application_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ujjwalav2application',
            name='witness_mobile_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ujjwalav2application',
            name='witness_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='ujjwalaapplicationdocuments',
            name='type',
            field=models.CharField(choices=[('CUSTOMER_PHOTO', 'Customer Photo'), ('BANK_DETAIL', 'Bank Detail'), ('OTHER_ID_PROOF', 'Other Id Proof'), ('SV', 'Subscription Voucher'), ('CONNECTION_DETAIL', 'Connection Detail'), ('KITCHEN_PHOTO', 'Kitchen Photo'), ('CUSTOMER_IN_KITCHEN', 'Customer In Kitchen'), ('MAIN_GATE', 'Main Gate'), ('WITNESS_PHOTO', 'Witness Photo'), ('MECHANIC_PHOTO', 'Mechanic Photo'), ('CUSTOMER_SIGNATURE', 'Customer Signature'), ('DEATH_CERTIFICATE', 'Death Certificate'), ('DIVORCE_DOCUMENT', 'Divorce Document')], max_length=25),
        ),
    ]
