# Generated by Django 3.2.12 on 2022-05-14 11:11

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('ujjwala', '0037_auto_20220513_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ujjwalaapplicationdocuments',
            name='type',
            field=models.CharField(choices=[('CUSTOMER_PHOTO', 'Customer Photo'), ('BANK_DETAIL', 'Bank Detail'), ('OTHER_ID_PROOF', 'Other Id Proof'), ('SV', 'Subscription Voucher'), ('CONNECTION_DETAIL', 'Condnection Detail'), ('KITCHEN_PHOTO', 'Kitchen Photo'), ('CUSTOMER_IN_KITCHEN', 'Customer In Kitchen'), ('MAIN_GATE', 'Main Gate'), ('WITNESS_PHOTO', 'Witness Photo'), ('MECHANIC_PHOTO', 'Mechanic Photo'), ('CUSTOMER_SIGNATURE', 'Customer Signature'), ('DEATH_CERTIFICATE', 'Death Certificate'), ('DIVORCE_DOCUMENT', 'Divorce Document')], max_length=25),
        ),
        migrations.AlterField(
            model_name='ujjwalav2application',
            name='status',
            field=django_fsm.FSMField(choices=[('DOCUMENTS_UPLOADED', 'Documents Uploaded'), ('DOCUMENTS_REUPLOAD', 'Documents Reupload'), ('EKYC_REJECTED', 'E-KYC Rejected'), ('EKYC_ACCEPTED', 'E-KYC Accepted'), ('LEGAL_DOCUMENTS_UPLOAD', 'Legal Documents Upload'), ('MANUAL_LEGAL_DOCUMENTS_UPLOAD', 'Manual Legal Documents Upload'), ('LEGAL_DOCUMENTS_COLLECTED', 'Legal Documents Collected'), ('EDIT_APPLICATION', 'Edit Application'), ('APPLICATION_REJECTED', 'Application Rejected'), ('OMC_CLEARED', 'OMC Cleared'), ('OMC_REJECTED', 'OMC Rejected'), ('NIC_ERROR', 'NIC Error'), ('NIC_CLEARED', 'NIC Cleared'), ('INSUFFICIENT_ADDRESS', 'Insufficient Address'), ('DO_MANUAL_OPERATION', 'Do Manual Operation'), ('PRE_INSPECTION_SUBMITTED', 'Pre Inspection Submitted'), ('PRE_INSPECTION_REUPLOAD', 'Pre Inspection Reupload'), ('PRE_INSPECTION_ACCEPTED', 'Pre Inspection Accepted'), ('CONNECTION_RELEASED', 'Connection Released'), ('POST_INSTALLATION_UPLOAD', 'Post Installation Upload'), ('COMPLETED', 'Completed')], default='DOCUMENTS_UPLOADED', max_length=50),
        ),
    ]
