# Generated by Django 3.2.12 on 2022-05-20 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ujjwala', '0040_userdocuments'),
    ]

    operations = [
        migrations.AddField(
            model_name='ujjwalav2application',
            name='pre_inspection_done_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pre_inspection_done_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
