# Generated by Django 3.2.12 on 2022-05-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujjwala', '0041_ujjwalav2application_pre_inspection_done_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ujjwalav2application',
            name='accuracy',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
