# Generated by Django 3.2.12 on 2022-05-23 10:46

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('ujjwala', '0043_alter_ujjwalav2application_accuracy'),
    ]

    operations = [
        migrations.AddField(
            model_name='ujjwalav2application',
            name='otp_status',
            field=django_fsm.FSMField(choices=[('SENT', 'Sent'), ('RESENT', 'Resent'), ('SUBMITTED', 'Submitted'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='SENT', max_length=50),
        ),
    ]
