# Generated by Django 3.2.12 on 2022-05-24 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ujjwala', '0044_ujjwalav2application_otp_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ujjwalav2application',
            name='otp_status',
        ),
    ]
