# Generated by Django 3.2.12 on 2022-05-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujjwala', '0045_remove_ujjwalav2application_otp_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymembers',
            name='additional_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
