# Generated by Django 3.2.12 on 2022-05-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujjwala', '0046_familymembers_additional_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymembers',
            name='is_valid_uid',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
