# Generated by Django 3.2.12 on 2022-05-31 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujjwala', '0047_familymembers_is_valid_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ujjwalav2application',
            name='uid_mobile_status',
            field=models.CharField(blank=True, choices=[('LINKED_WITH_SAME_MOBILE', 'Linked With Same Mobile'), ('LINKED_WITH_OTHER_MOBILE', 'Linked With Other Mobile'), ('MOBILE_NOT_AVAILABLE', 'Mobile Not Available')], max_length=25, null=True),
        ),
    ]
