# Generated by Django 3.2.12 on 2022-06-01 07:29

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('ujjwala', '0048_alter_ujjwalav2application_uid_mobile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(blank=True, max_length=16, null=True)),
                ('longitude', models.CharField(blank=True, max_length=16, null=True)),
                ('accuracy', models.CharField(blank=True, max_length=24, null=True)),
                ('witness_name', models.CharField(blank=True, max_length=256, null=True)),
                ('witness_mobile_number', models.CharField(blank=True, max_length=10, null=True)),
                ('status', django_fsm.FSMField(choices=[('INITIAL', 'Initial'), ('OTP_CONFIRMATION', 'Otp Confirmation'), ('OTP_VERIFIED', 'Otp Verified')], default='INITIAL', max_length=50)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pre_inspection', to='ujjwala.ujjwalav2application')),
            ],
        ),
        migrations.CreateModel(
            name='PreInspectionDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CUSTOMER_PHOTO', 'Customer Photo'), ('BANK_DETAIL', 'Bank Detail'), ('OTHER_ID_PROOF', 'Other Id Proof'), ('SV', 'Subscription Voucher'), ('CONNECTION_DETAIL', 'Connection Detail'), ('KITCHEN_PHOTO', 'Kitchen Photo'), ('CUSTOMER_IN_KITCHEN', 'Customer In Kitchen'), ('MAIN_GATE', 'Main Gate'), ('WITNESS_PHOTO', 'Witness Photo'), ('MECHANIC_PHOTO', 'Mechanic Photo'), ('CUSTOMER_SIGNATURE', 'Customer Signature'), ('DEATH_CERTIFICATE', 'Death Certificate'), ('DIVORCE_DOCUMENT', 'Divorce Document')], max_length=25)),
                ('link', models.URLField()),
                ('compressed', models.BooleanField(default=False)),
                ('file_size', models.CharField(default='0', max_length=16)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ujjwala.preinspection')),
            ],
        ),
        migrations.CreateModel(
            name='Evykati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.JSONField(blank=True, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evyakti', to='ujjwala.ujjwalav2application')),
            ],
        ),
    ]
