# Generated by Django 3.2.12 on 2022-06-01 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ujjwala', '0049_evykati_preinspection_preinspectiondocuments'),
    ]

    operations = [
        migrations.AddField(
            model_name='preinspection',
            name='mechanic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
            preserve_default=False,
        ),
    ]
