# Generated by Django 3.2.12 on 2022-06-03 11:03

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('ujjwala', '0050_preinspection_mechanic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preinspection',
            name='status',
            field=django_fsm.FSMField(choices=[('KITCHEN_PHOTO', 'Kitchen Photo'), ('SAFETY_AUDIO', 'Safety Audio'), ('PREVIEW_INSPECTION', 'Preview Inspection'), ('SUBMITTED', 'Submitted'), ('ACCEPTED', 'Accepted'), ('REUPLOAD', 'Reupload')], default='KITCHEN_PHOTO', max_length=50),
        ),
        migrations.AlterField(
            model_name='preinspectiondocuments',
            name='type',
            field=models.CharField(choices=[('CUSTOMER_PHOTO', 'Customer Photo'), ('BANK_DETAIL', 'Bank Detail'), ('OTHER_ID_PROOF', 'Other Id Proof'), ('SV', 'Subscription Voucher'), ('CONNECTION_DETAIL', 'Connection Detail'), ('KITCHEN_PHOTO', 'Kitchen Photo'), ('CUSTOMER_IN_KITCHEN', 'Customer In Kitchen'), ('MAIN_GATE', 'Main Gate'), ('WITNESS_PHOTO', 'Witness Photo'), ('MECHANIC_PHOTO', 'Mechanic Photo'), ('CUSTOMER_SIGNATURE', 'Customer Signature'), ('WITNESS_SIGNATURE', 'Witness Signature'), ('DEATH_CERTIFICATE', 'Death Certificate'), ('DIVORCE_DOCUMENT', 'Divorce Document')], max_length=25),
        ),
        migrations.AlterField(
            model_name='ujjwalaapplicationdocuments',
            name='type',
            field=models.CharField(choices=[('CUSTOMER_PHOTO', 'Customer Photo'), ('BANK_DETAIL', 'Bank Detail'), ('OTHER_ID_PROOF', 'Other Id Proof'), ('SV', 'Subscription Voucher'), ('CONNECTION_DETAIL', 'Connection Detail'), ('KITCHEN_PHOTO', 'Kitchen Photo'), ('CUSTOMER_IN_KITCHEN', 'Customer In Kitchen'), ('MAIN_GATE', 'Main Gate'), ('WITNESS_PHOTO', 'Witness Photo'), ('MECHANIC_PHOTO', 'Mechanic Photo'), ('CUSTOMER_SIGNATURE', 'Customer Signature'), ('WITNESS_SIGNATURE', 'Witness Signature'), ('DEATH_CERTIFICATE', 'Death Certificate'), ('DIVORCE_DOCUMENT', 'Divorce Document')], max_length=25),
        ),
    ]
