# Generated by Django 3.2.12 on 2022-06-07 07:19

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('ujjwala', '0052_auto_20220607_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preinspection',
            name='status',
            field=django_fsm.FSMField(choices=[('ALLOCATED', 'Allocated'), ('OTP_VERIFIED', 'Otp Verified'), ('KITCHEN_PHOTO', 'Kitchen Photo'), ('SAFETY_AUDIO', 'Safety Audio'), ('PREVIEW_INSPECTION', 'Preview Inspection'), ('SUBMITTED', 'Submitted'), ('ACCEPTED', 'Accepted'), ('REUPLOAD', 'Reupload'), ('REJECTED', 'Rejected')], default='KITCHEN_PHOTO', max_length=50),
        ),
    ]
