error_mapping = {
    "CBE0001": "Mandatory Tags values are missing.",
    "CBE0002": "Scheme Code does not exist in PFMS.",
    "CBE0003": "Beneficiary Type does not exist in PFMS or does not belong to the provided Scheme.",
    "CBE0004": "Same Scheme Specific ID/LPG ID already exists in PFMS for same Scheme and Beneficiary Type.",
    "CBE0005": "Duplicate Batch ID/Message ID not allowed.",
    "CBE0006": "AADHAAR Number should be of 12 digits and must pass the algorithm provided by UIDAI.",
    "CBE0007": "AADHAAR Number already exists for same Beneficiary Type and Scheme.",
    "CBE0008": "Duplicate Beneficiary Name, Bank Account No and Bank Name not allowed for same scheme.",
    "CBE0009": "Rejected by Bank, as Bank Account Number is Invalid.",
    "CBE0010": "Bank Name is not as per PFMS Bank Master.",
    "CBE0011": "Invalid Gender Value, It should be F/M/T.",
    "CBE0012": "One of AADHAAR Number or Bank Account details are mandatory.",
    "CBE0013": "Invalid Address Columns/LGD code, It should be as PFMS Master.",
    "CBE0014": "Date of Birth should be in format as CB (Source System Date).",
    "CBE0015": "Mobile number/Phone Number should be of 10 digits only.",
    "CBE0016": "Invalid Batch Format, it should be as CB (Source System Id) DDMMYY (4-digit Sequence).",
    "CBE0017": "Batch File should be in the unique Agency Code of PFMS agency.",
    "CBE0018": "Both Town and Village code have been provided which are mutually exclusive.",
    "CBE0020": "Invalid value for Purpose, it should be A/U/D.",
    "CBE0021": "Invalid PFMS Beneficiary Code.",
    "CBE0022": "Invalid IFSC Code.",
    "CBE0023": "Invalid Country Id.",
    "CBE0024": "Wrong Data Type/Length Format.",
    "CBE0025": "Pincode Code should be numeric value.",
    "CBE0027": "Error in reading file, File is malformed or Failed during schema validation.",
    "CBE0028": "Rejected by Bank, Account No does not exist in Bank.",
    "CBE0029": "Scheme code is not uniform for all records.",
    "CBE0030": "Rejected by Bank, Account status is closed.",
    "CBE0031": "Duplicate Aadhaar Number Found In The File.",
    "CBE0032": "Duplicate Beneficiary Details [BeneficiaryAccountNo, BeneficiaryBIFCI, BeneficiaryName, BeneficiaryType, SchemeCode, BankCode, BankName].",
    "CBE0034": "Blocked Account.",
    "CBE0035": "One or more mandatory tags values are missing.",
    "CBE0036": "Beneficiary Category not in PFMS.",
    "CBE0039": "Invalid Location Code, it should be as LGD Location Code Master.",
    "CBE0040": "Beneficiary Aadhaar No. + Application No. Combination already exists in PFMS.",
    "CBE0045": "Aadhaar Number is not seeded in NPCI.",
    "CBE0047": "Beneficiary Code does not exist in PFMS for this data source.",
    "CBE0048": "IFSC Code either not present or currently inactive in tblBankBranch.",
    "CBE0049": "Beneficiary Name Len is greater than 100.",
    "CBE0050": "Only one beneficiary type is allowed in a file.",
    "CBE0051": "Invalid Account, Validation Pending Since Last 6 Month from Bank.",
    "CBE0052": "UID And Account Both Are Invalid.",
    "CBE0053": "Bank Not Responded.",
    "CBE0054": "Rejected due to no response received from banks within specified days.",
    "CBE0055": "UID is Invalid and account is Rejected due to no response received from bank within specified days.",
    "CBE0046": "UID is Invalid and account is closed.",
    "CPE0047": "UID is Invalid and account is blocked.",
    "CPE0048": "UID is Invalid and account is inactive.",
    "CPW0001": "Beneficiary Created based on UID, but account is Invalid.",
    "CPW0002": "Beneficiary Created based on UID, but account is Closed.",
    "CPW0003": "Beneficiary Created based on UID, but account is Blocked.",
    "CPW0004": "Beneficiary Created based on UID, but account did not receive response from Bank.",
    "CPW0005": "Beneficiary Created based on UID, but IFSC code not match with bank.",
    "CPW0006": "UID is enabled for DBT and beneficiary has been created based on account.",
    "CPW0007": "UID is disable for DBT and beneficiary has been created based on account.",
    "CPW0008": "UID never enabled for DBT and beneficiary has been created based on account.",
    "CPW0009": "UID is cancelled by UIDAI and beneficiary has been created based on account.",
    "CBE0056": "Beneficiary bank account not allowed in this bank.",
    "CBE0057": "Beneficiary Registration is rejected as Beneficiary Account Type is not in 'SB', 'SBA' or 'JD' as received from bank. Note: This error code is valid for PM Kisan only.",
    "CBE0060": "UID is Disable for DBT",
    "CBE0061": "UID NEVER ENABLE FOR DBT",
    "CBE0062": "UID is CANCELLED BY UIDAI",
    "CBE0063": "UID is Disable for DBT and account is closed.",
    "CBE0064": "UID NEVER ENABLE FOR DBT and account is closed.",
    "CBE0065": "UID is CANCELLED BY UIDAI and account is closed.",
    "CBE0066": "UID is Disable for DBT and account is blocked.",
    "CBE0067": "UID NEVER ENABLE FOR DBT and account is blocked.",
    "CBE0068": "UID is CANCELLED BY UIDAI and account is blocked.",
    "CBE0069": "UID is Disable for DBT and account is inactive.",
    "CBE0070": "UID NEVER ENABLE FOR DBT and account is inactive.",
    "CBE0071": "UID is CANCELLED BY UIDAI and account is inactive.",
    "CBE0072": "UID is Disable for DBT and account is invalid.",
    "CBE0073": "UID NEVER ENABLE FOR DBT and account is invalid.",
    "CBE0074": "UID is CANCELLED BY UIDAI and account is invalid.",
    "CBE0075": "UID is Disable for DBT and account is Rejected due to no response received from bank within specified days.",
    "CBE0076": "UID NEVER ENABLE FOR DBT and account is Rejected due to no response received from bank within specified days.",
    "CBE0077": "UID is CANCELLED BY UIDAI and account is Rejected due to no response received from bank within specified days.",
    "CBW0062": "Beneficiary UID / Account ID already exists in another OMC",
    "CBW0063": "No response received from concerned bank within 3 days, therefore PFMS has Created Beneficiary based on information shared on request file."
}
