# Generated by Django 3.2.12 on 2025-04-22 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_comments_xtd', '0008_auto_20200920_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentX',
            fields=[
                ('xtdcomment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_comments_xtd.xtdcomment')),
                ('comment_type', models.CharField(choices=[('ADDRESS_CHANGE', 'Address Change'), ('OTHERS', 'Others')], default='OTHERS', max_length=52)),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'ordering': ('submit_date',),
                'permissions': [('can_moderate', 'Can moderate comments')],
                'abstract': False,
            },
            bases=('django_comments_xtd.xtdcomment',),
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=48)),
                ('name', models.CharField(max_length=128)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=128)),
                ('html_content', models.TextField()),
                ('variable_list', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HTMLTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=52)),
                ('html_file_name', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='IFSCodeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_ifscode', models.CharField(max_length=32)),
                ('new_ifscode', models.CharField(max_length=32)),
                ('main_branch', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=48)),
                ('name', models.CharField(max_length=128)),
                ('unit', models.CharField(choices=[('NOS', 'Nos')], default='NOS', max_length=52)),
                ('price', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RTGSList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255)),
                ('ifscode', models.CharField(max_length=12)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SDMSServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('ADDRESS UPDATE', 'Address Update')], max_length=52)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TokensExcluded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('gender', models.CharField(choices=[('FEMALE', 'Female'), ('MALE', 'Male')], default='MALE', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=48)),
                ('description', models.CharField(max_length=128)),
                ('forms', models.ManyToManyField(related_name='service_types', to='reference_data.Form')),
            ],
        ),
        migrations.CreateModel(
            name='HTMLTemplateVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=52)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference_data.htmltemplate')),
            ],
        ),
    ]
