# Generated by Django 3.2.12 on 2023-12-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('service_request_type', models.CharField(choices=[('CHANGE_PHONE_NUMBER', 'Change Phone Number')], max_length=128)),
                ('camunda_process_id', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
