# Generated by Django 3.2.12 on 2025-04-22 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('service_request_type', models.CharField(choices=[('CHANGE_PHONE_NUMBER', 'Change Phone Number'), ('UID_UPLOAD_FOR_EKYC', 'UID Upload For EKyc'), ('UPDATE_ADDRESS', 'Update Address'), ('UPDATE_BANK_DETAILS', 'Update Bank Details'), ('CHANGE_CYLINDER_TYPE', 'Change Cylinder Type')], max_length=128)),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('camunda_process_id', models.TextField(blank=True, null=True)),
                ('form_data', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'COMPLETED'), ('REJECTED', 'Rejected')], default='PENDING', max_length=128)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('reviewed_on', models.DateTimeField(null=True)),
                ('sdms_ticket_number', models.CharField(blank=True, max_length=52, null=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('request_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_resolve_service_request', 'Can Resolve Service Request'),),
            },
        ),
    ]
