# Generated by Django 3.2.12 on 2023-07-05 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RetailCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('shop_name', models.CharField(max_length=128)),
                ('shop_type', models.CharField(max_length=128)),
                ('mobile_number', models.CharField(max_length=10)),
                ('whatsapp_number', models.CharField(max_length=10)),
                ('referral_code', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RetailCustomernDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PAN_NUMBER', 'Pan Number'), ('GST_NUMBER', 'Gst Number'), ('MCLICENSE', 'Mclicense')], max_length=25)),
                ('link', models.URLField()),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='retail_customers.retailcustomer')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128)),
                ('floor', models.CharField(max_length=32)),
                ('street_no', models.IntegerField()),
                ('landmark', models.CharField(max_length=128)),
                ('locality', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=48)),
                ('pincode', models.CharField(max_length=10)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='retail_customers.retailcustomer')),
            ],
        ),
    ]
