# Generated by Django 3.2.12 on 2025-04-22 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RetailCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('unit_name', models.CharField(max_length=128)),
                ('shop_type', models.CharField(max_length=128)),
                ('mobile_number', models.CharField(max_length=10)),
                ('whatsapp_number', models.CharField(max_length=10)),
                ('referral_code', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RetailCustomerDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SHOP_PHOTO', 'Shop Photo'), ('PAN_PHOTO', 'PAN Photo'), ('GST_PHOTO', 'GST Photo'), ('MCLICENSE_PHOTO', 'Mclicense Photo')], max_length=25)),
                ('link', models.URLField()),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='retail_customers.retailcustomer')),
            ],
        ),
        migrations.CreateModel(
            name='RetailCustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128, null=True)),
                ('floor', models.CharField(max_length=32)),
                ('street_no', models.IntegerField()),
                ('landmark', models.CharField(max_length=128)),
                ('locality', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=48)),
                ('pincode', models.CharField(max_length=10)),
                ('latitude', models.CharField(blank=True, max_length=32, null=True)),
                ('longitude', models.CharField(blank=True, max_length=32, null=True)),
                ('accuracy', models.CharField(blank=True, max_length=24, null=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='retail_customers.retailcustomer')),
            ],
        ),
    ]
