# Generated by Django 3.2.12 on 2023-07-08 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retail_customers', '0002_rename_retailcustomerndocuments_retailcustomerdocuments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='RetailCustomerAddress',
        ),
    ]
