# Generated by Django 3.2.12 on 2023-07-10 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retail_customers', '0003_rename_address_retailcustomeraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailcustomeraddress',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='retail_customers.retailcustomer'),
        ),
        migrations.AlterField(
            model_name='retailcustomeraddress',
            name='title',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='retailcustomerdocuments',
            name='type',
            field=models.CharField(choices=[('PAN_PHOTO', 'PAN Photo'), ('GST_PHOTO', 'GST Photo'), ('MCLICENSE_PHOTO', 'Mclicense Photo')], max_length=25),
        ),
    ]
